### ISSUE TITLE
Grid features that are used in MOVIE+MCAN

### ISSUE THREAD

**Issue by ifmaq1** [facebookresearch/mmf#1000]
## ❓ Questions and Help
could you please help me out regarding this confusion.

**1-)** I am unable to read/open the whole **.pth file of grid image features**.

**2-)** Unlike **region features** that select top bounding boxes **Grid features** are based upon the image size right? 

I checked the tensor size of one **image feature file** which displays [1, 2048, 19, 29]. Does it means we have total number of features **19*29=551**. Can I make less number of features file by making clusters of similar features from **.pth** file? 

**3-)** Does .pth features files only contains weights? or any other information as well. I am unable to read the complete file but only can see few weights.

**Comment by apsdehal** [comment]
Hi,
This seems like an issue for grid-features repo rather than MMF.

1) Please open up an issue on grid-features repo.
2) Yes, you should be able to do various kind of poolings on top of the features.
3) Probably yes.

**Comment by ifmaq1** [comment]
Thank you for your response
