### ISSUE TITLE
How to generate the answer vocabulary of KRISP

### ISSUE THREAD

**Issue by Fen9** [facebookresearch/mmf#1031]
## ❓ Questions and Help
Dear authors,

Thank you for sharing the code. After carefully looking into the code, I found the answer vocabulary that KRISP used is much smaller than the one that is extracted from OK-VQA. Do you mind sharing how to generate the vocabulary that KRISP is using? Thanks.

Best
Feng

**Comment by KMarino** [comment]
I don’t know what you mean by it being much smaller than the one extracted on OK-VQA, I think it’s about the same as in the original paper. 

You can generate by running the answers through 
from mmf.utils.text import word_tokenize

And then filtering answers that don’t occur more than 10 times in train.

**Comment by KMarino** [comment]
Also, just checked on answer vocab size. It's a size of 2253 versus 3000 in the original OKVQA dataset paper. We did try a lower threshold for KRISP (count 5) but that did slightly worse in our preliminary experiments.

**Comment by apsdehal** [comment]
Closing this as responded.
