### ISSUE TITLE
extracted COCO image features are inconsistent with thoes proviced by the project

### ISSUE THREAD

**Issue by PengY1625** [facebookresearch/mmf#1038]
## ❓ Questions and Help
Hi，
I‘m trying to do some experiments on COCO dataset using m4c_captioner model.  By using "detectron.lmdb" that provided by the project, the experiment results perfectly match those in your paper. However, when I use features that were extracted from scratch by myself, Bleu4 drops from 0.34 to 0.31 (using the same seed). I have compared several image features that I extracted with the ones that provided by the project, I found them similar but not exactly the same. Here are some keypoints when I extract image featuers and perform experiments, and I'm wondering is there anything I have done wrong:
1. use mmf-master/tools/scripts/features/extract_features_vmb.py
2. use model X-101, download from: "https://dl.fbaipublicfiles.com/pythia/detectron_model/detectron_model.pth"  
3. use default parameters and run: python extract_features_vmb.py --model_file=./detectron_model.pth --config_file=./detectron_model.yaml --image_dir=./input/coco_trainval2014_karpathy --output_folder=./output/coco_trainval2014_karpathy/  --background
4. transform .npy files into lmdb files: python lmdb_conversion.py --mode convert --lmdb_path ./features/detectron_my.lmdb/  --features_folder ./output/coco_trainval2014_karpathy/
5. when training and evaluating the model, use the original annotation files that provided by the project

Looking forward to your reply, thank you!

**Comment by ronghanghu** [comment]
Hi @PengY1625, perhaps there has been come backward-incompatible changes in the feature extraction script. Could you try out the feature extraction script in project/m4c branch (https://github.com/facebookresearch/mmf/blob/project/m4c/pythia/scripts/features/extract_features_vmb.py)? This was what I used for the M4C and M4C-Captioner experiments.

**Comment by PengY1625** [comment]
Hi, @ronghanghu thank you for your reply. I have tried the script you mentioned above, the extracted features seems different to both those extracted by the former script, and those provided by the project, while still send me nowhere close to score of 0.34 (Bleu4) in experiment. I guess maybe there are other details that I have not got right, could you please help me to get clear of the following confusions? Thanks in advance!
Q1: Is X-101 the exact model to use? I notice that in a former issue (https://github.com/facebookresearch/mmf/issues/663) , @apsdehal mentioned that the default model is ResNext152.
Q2: Were the COCO image features provided by the project extracted with maskrcnn-benchmark or with Caffe2?  I found a related description in https://mmf.sh/docs/projects/m4c_captioner, which says the performs various with these two kinds of image features.
Q3: When building annotation files, I compute the "org_normalize_boxes" as infos['bbox'] / [image_width, image_height, image_width, image_height], is that the right process?

**Comment by PengY1625** [comment]
@ronghanghu Thank you! I have tried that script and got a Bleu4 score closer to the one reported in your paper.
