### ISSUE TITLE
Some Questions regarding loss variables and image encoders

### ISSUE THREAD

**Issue by RishabhMaheshwary** [facebookresearch/mmf#1061]
## ❓ Questions and Help
I was training visual_bert on the vizwiz datast. I had some questions.

1. Is the ```train/total_loss``` and the ```train/vizwiz/logit_bce``` the same or different? 
2. Also, is the ```val/total_loss``` and ```val/vizwiz/logit_bce``` also same?

Also, I am not aware about image encoders so I wanted to known what is the function of image feature encoders? 
Like, in the pythia we use ```finetune_faster_rcnn_fpn_fc7``` and there are also other encoders like ```identity```, ```default```, etc.

**Comment by apsdehal** [comment]
Hi @RishabhMaheshwary,

1. Yes. If vizwiz is the only dataset you are using and logit_bce is the only loss you are using, then yes
2. Same as 1.

So, the pipeline for most models is built using image feature encoders. In configuration file, you can them to any of the types that are available and they should work. For example, if you don't want the fc7 layer from fasterRcnn, then you can change that image feature encoder to `identity` type and it should skip.

**Comment by RishabhMaheshwary** [comment]
Thanks for the reply!
