### ISSUE TITLE
Image Region Features

### ISSUE THREAD

**Issue by harshraj22** [facebookresearch/mmf#1105]
## ❓ Questions and Help
Hello, I would like to use the repo's code, which extracts the image's region features (as bottom up attention) in my personal project. I would like to add it to my architecture such that it is end to end trainable. Can someone guide me which file/ class to take ?

I went through the [official documentation](https://mmf.sh/docs/tutorials/image_feature_extraction), but it seems, this would not make the architecture end to end trainable.

**Comment by TownWilliam** [comment]
Hello, it seems that the python scripts extracting the features is in the location  : **mmf/tools/scripts/features/extract_features_vmb.py**. 

This script provides several params and Resnet checkpoint files to get the wanted features results. It could covert the original image files into corresponding region features.

![image](https://user-images.githubusercontent.com/49356039/143879084-5a0e8138-2055-4033-ab8d-2c45d228f05c.png)
