### ISSUE TITLE
Failed pytest 

### ISSUE THREAD

**Issue by soon22** [facebookresearch/mmf#1108]
## ❓ Questions and Help
Hi, I ran `pytest` after installation and encountered failure on this two part.
Appreciate it if anyone can look into it, thanks
```
tests/configs/test_zoo_urls.py .F

tests/configs/test_zoo_urls.py .F
```

Full error log:
https://github.com/soon22/logs/blob/main/mmf_pytest_failure

**Comment by Ryan-Qiyu-Jiang** [comment]
Hi thanks for bringing this up!
It seems like the MM-IMDB download links are down. 
Will make a pr to use https://archive.org/download/mmimdb/mmimdb.tar.gz
Otherwise if thats the only error you got from pytest your installation should be good!

**Comment by Ryan-Qiyu-Jiang** [comment]
PR for zoo_urls merged https://github.com/facebookresearch/mmf/commit/842c4d18ac8ee62a879fdb25ff75e91706a5d187
