### ISSUE TITLE
How to get object bounding boxes for TextVQA

### ISSUE THREAD

**Issue by soonchangAI** [facebookresearch/mmf#1117]
## ❓ Questions and Help
Hi, according to paper, 100 top scored objects were obtained per image. I found the bounding boxes were given in ``` obj_normalized_boxes```
I would like to use new images. 
Is there script to generate these bounding boxes?
Thanks.

**Comment by apsdehal** [comment]
Hi.

These have been extracted using the tutorial here: https://mmf.sh/docs/tutorials/image_feature_extraction. For lmdb, we have a tool in MMF: https://github.com/facebookresearch/mmf/blob/master/tools/scripts/features/lmdb_conversion.py

**Comment by soon22** [comment]
@apsdehal thanks 🤣🙏

**Comment by leonodelee** [comment]
> Hi.
> 
> These have been extracted using the tutorial here: https://mmf.sh/docs/tutorials/image_feature_extraction. For lmdb, we have a tool in MMF: https://github.com/facebookresearch/mmf/blob/master/tools/scripts/features/lmdb_conversion.py

Sorry to interrupt, I want to extract image features for  Pythia framework, as in /data/open_images/detectron_fix_100/fc6;I wonder what should I do if I got only 66 bounding boxes, less than the normal 100.
