### ISSUE TITLE
URGENT: What next after running extract_ocr_frcn_feature.py in m4c ?

### ISSUE THREAD

**Issue by shwetkm** [facebookresearch/mmf#1243]
## ❓ Questions and Help
I have made some changes in the feature computation of [extract_ocr_frcn_feature](https://github.com/facebookresearch/mmf/blob/main/projects/m4c/scripts/extract_ocr_frcn_feature.py). This script has created 2 .npy files for each image. 
Now, how to use those npy files for training? 
Does this need to be used in place of the ocr_en_frcn_features.lmdb folder somehow? If yes, then how to convert the folder with npy files to lmdb?

I am stuck at this step and will highly appreciate any help.
@ronghanghu

**Comment by ronghanghu** [comment]
Hi, you need to use https://github.com/facebookresearch/mmf/blob/master/tools/scripts/features/lmdb_conversion.py to convert your "*.npy" feature files to lmdb. You can follow the procedure in https://github.com/facebookresearch/mmf/issues/663#issuecomment-883000371

**Comment by shwetkm** [comment]
Thanks, @ronghanghu. This is helpful.
