### ISSUE TITLE
Support GQA dataset

### ISSUE THREAD

**Issue by mathfinder** [facebookresearch/mmf#128]
Will you provide a dataloader for GQA?

https://cs.stanford.edu/people/dorarad/gqa/download.html

**Comment by meetshah1995** [comment]
Hi @mathfinder

A script to convert GQA into a Pythia-consumable dataset is available [here](https://github.com/facebookresearch/pythia/tree/master/pythia/scripts/gqa) 

@apsdehal - I think it would be great to have a registered dataset class for GQA?
