### ISSUE TITLE
[Questions] Could you please offer the location info for the detected objects?

### ISSUE THREAD

**Issue by ayumiymk** [facebookresearch/mmf#141]
## ❓ Questions and Help
Hi, thanks for such great work. I want to conduct some experiments on TextVQA. From the released code, I find the location info of OCR results is given. How about the detected objects? I think it is important to take the location info into consideration for this task.

**Comment by apsdehal** [comment]
Let me get back to you. I will have to extract them out and upload them unless you want to extract them out yourselves using https://github.com/facebookresearch/pythia/blob/master/pythia/scripts/features/extract_features_vmb.py

**Comment by ayumiymk** [comment]
Thank you very much! I will also do it. But could you please also offer the predicted category of each box? I have some troubles while using detectron. Of course, I will keep trying `extract_features_vmb.py` to process my own datasets.
