### ISSUE TITLE
[docs] Add FAQ for segmentation fault. 

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/mmf#151]
## 🚀 Feature
Add information about debugging segmentation fault to README and docs FAQ.

A lot of people are getting this error. It should be easy to debug this using htop memory output.

**Comment by rajpratyush** [comment]
Can I take up this issue?

**Comment by apsdehal** [comment]
@rajpratyush  Sure. Go ahead!

**Comment by rajpratyush** [comment]
can you tell me which files to be changed?

**Comment by ria-19** [comment]
If this issue is open, I would like to work on this.

**Comment by srijit2021** [comment]
I am trying to work on it

**Comment by apsdehal** [comment]
@ria-19 Are you working on this? If not, can @srijit2021  take over?

**Comment by ria-19** [comment]
Yes, just give me today. Thanks!

**Comment by ria-19** [comment]
I have created a pull request. Kindly check if that was the intended change.

**Comment by pree-T** [comment]
Is this issue still open? I would like to work on this.
