### ISSUE TITLE
TopDownAttentionLSTM not working for Visual QA

### ISSUE THREAD

**Issue by vikshree** [facebookresearch/mmf#157]
## ❓ Questions and Help
Earlier, I trained Pythia for VQA with **NonLinearElementMultiply()** function for combining text and image features, and it worked fine. However, using the **TopDownAttentionLSTM()** function spits an error in the **layers.py** file. Apparently, there is no item in the registry which ends with the name "_lstm_state". So, the function call in **line 318** returns a **None**. Do I need to change something else to use the **TopDownAttentionLSTM()** function?

![image](https://user-images.githubusercontent.com/40926569/63305102-91a5af80-c2b3-11e9-815a-f7cdf3ab7248.png)

**Comment by vedanuj** [comment]
`TopDownAttentionLSTM` is used in BUTD captioning model. You need to initiate the LSTM hidden states if you want to use `TopDownAttentionLSTM` as done in `butd.py` model `get_data_t` method.

**Comment by vikshree** [comment]
Thanks!

**Comment by vikshree** [comment]
For the VQA task, based on your experience, is it possible to get performance boost by using `TopDownAttentionLSTM` or `TwoLayerElementMultiply`, rather than `NonLinearElementMultiply`?

**Comment by apsdehal** [comment]
We don't have results of replacing `NonLinearElementMultiply` with `TwoLayerElementMultiply` but we already using a variant of `Top Down Attention` which contains `NonLinearElementMultiply`.
