### ISSUE TITLE
[feature] Add fusion techniques

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/mmf#162]
## 🚀 Feature

Fusion techniques for multimodal fusion are an important component of VQA models. Remi's repo https://github.com/Cadene/block.bootstrap.pytorch has most of them implemented beforehand. We can add it as a dependency and import whatever is required.

**Comment by pushkalkatara** [comment]
Hi, can I work on this issue? 
I notice that in the models fusion layers are imported from [modules/layers.py](https://github.com/facebookresearch/pythia/blob/37b2dc5d745fd752ba0c574e246856f03e49fb6d/pythia/modules/layers.py#L165). Do these need to be replaced by remi's repo?

**Comment by apsdehal** [comment]
Hi,
Thanks for working on this. You don't have to replace that file. Instead, you have to expose layers from Remi's repo into this file. So, that one can directly import these from pythia. It might be better to create a new file in modules folder named fusions
