### ISSUE TITLE
[docs] Add a table for current best model in the repo for particular datasets

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/mmf#167]
For e.g. it is not clear to people that LoRRA is the best model for VQA2.0 inside the repo and not pythia. We need a table for clarifying this.

**Comment by madamalarevanth** [comment]
Hello @apsdehal, I happy to work on it. If someone else working on it please let me know

**Comment by madamalarevanth** [comment]
> Hello @apsdehal, I happy to work on it. If someone else working on it please let me know

Is there any CLA I need to sign please let me know. I am new to the open source contribution

**Comment by ankitasankars** [comment]
Hello, Is this issue still opened?
