### ISSUE TITLE
[feature] ParlAI Integration on Pythia side

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/mmf#171]
## 🚀 Feature

This has been a long requested feature internally. With current architecture and SampleList, this should be really easy to tackle. ParlAI datasets all have build function.  For #163, this should be looked into first.

**Comment by abhinav-bohra** [comment]
Hello @apsdehal, I would like to work on this feature. This will be my first open-source contribution, and it would be fantastic if you could give me some advice on how to proceed.

**Comment by apsdehal** [comment]
@abhinav-bohra This is probably out of scope as of now. If possible would you like to look at https://github.com/facebookresearch/mmf/issues/1044? I can also provide or create new issues as per MMF's requirements if you are not interested in 1044.
