### ISSUE TITLE
fast_read problem (doesn't help training speed)

### ISSUE THREAD

**Issue by dtchantao** [facebookresearch/mmf#180]
## ❓ Questions and Help

Hi. I'm currently training my own network. Initially, fast_read = false and the training speed is quite slow and GPU_util is quite low. I thought it is due to data loading bottleneck. After I set fast_read=true, the training speed doesn't change. I thought it should speed up the training speed since all the data have been loaded at the beginning right? Anything I missed out?

**Comment by apsdehal** [comment]
I would suggest using distributed mode and start using torch.distributed.launch with `training_parameters.distributed True` appended at the end of the command. `.to('cuda')` calls are expensive and take a lot of time. Another thing that I can suggest is setting `training_parameters.pin_memory` to True.

**Comment by dtchantao** [comment]
> I would suggest using distributed mode and start using torch.distributed.launch with `training_parameters.distributed True` appended at the end of the command. `.to('cuda')` calls are expensive and take a lot of time. Another thing that I can suggest is setting `training_parameters.pin_memory` to True.

Thanks for your quick reply. Could I ask what does the "fast_read" do? Should the training speed become faster? Thanks!!

**Comment by apsdehal** [comment]
It does what you wrote initially i.e. preload all of the samples (including features). You will only get speedup if you io bound. I am working on performance bottleneck and will probably land changes by next week into v0.4 if you can wait that long.

**Comment by dtchantao** [comment]
> I would suggest using distributed mode and start using torch.distributed.launch with `training_parameters.distributed True` appended at the end of the command. `.to('cuda')` calls are expensive and take a lot of time. Another thing that I can suggest is setting `training_parameters.pin_memory` to True.

After I enabled "distributed", error happened: 
![image](https://user-images.githubusercontent.com/44595164/66178896-7fcc7000-e699-11e9-9446-2c0b586ed4bc.png)

But when change to "data_parallel", it works fine.

**Comment by apsdehal** [comment]
Sorry about that can you add this above that line in taskloader:

`batch = SampleList(batch)` 

Import Samplelist from `pythia.common.sample` if needed.

**Comment by dtchantao** [comment]
> Sorry about that can you add this above that line in taskloader:
> 
> `batch = SampleList(batch)`
> 
> Import Samplelist from `pythia.common.sample` if needed.

This error happened aft I add this line. 
![image](https://user-images.githubusercontent.com/44595164/66186060-d5157b00-e6b3-11e9-902a-075c05afd231.png)

I have 4 gpus, it seems the code only see 1 GPU.

**Comment by apsdehal** [comment]
How did you launch your job?

**Comment by dtchantao** [comment]
![image](https://user-images.githubusercontent.com/44595164/66186555-21ad8600-e6b5-11e9-9d9b-f8a47089b4c0.png)


![image](https://user-images.githubusercontent.com/44595164/66186503-fc207c80-e6b4-11e9-8299-40dc4e38e0a5.png)

This is what I did.

**Comment by dtchantao** [comment]
> How did you launch your job?

![image](https://user-images.githubusercontent.com/44595164/66186597-40138180-e6b5-11e9-92ff-a7bdd71f5d62.png)
![image](https://user-images.githubusercontent.com/44595164/66186602-443f9f00-e6b5-11e9-8072-09d84925d867.png)

This is what I did.

**Comment by apsdehal** [comment]
Run it like this:

```
python -m torch.distributed.launch --nproc_per_node 4 tools/run.py [rest of your command here]
```

**Comment by apsdehal** [comment]
nproc_per_node is usually equal to number of gpus you have.

Also, an easy way to update config is to use command line override, like for enabling distributed, you would append `training_parameters.distributed True` to the end of your command.

**Comment by dtchantao** [comment]
> Run it like this:
> 
> ```
> python -m torch.distributed.launch --nproc_per_node 4 tools/run.py [rest of your command here]
> ```

Thanks for your suggestions! I tried in the following two cases:

1. fast_read = true. It seems the size of the read data becomes 4 times as large as the previously (without distributed enabled). It is normal? 4 GPU distributed -> 4 X dataset size? 
The dataset is too large and therefore stuck.

2. fast_read = false 
following error appears
![image](https://user-images.githubusercontent.com/44595164/66284186-498d2b80-e8f9-11e9-8fec-02a026249f8a.png)

**Comment by apsdehal** [comment]
Can you post the full error log which is cut from your screenshot?

**Comment by dtchantao** [comment]
> Can you post the full error log which is cut from your screenshot?

hi I attached my error.log for your information
[error.log](https://github.com/facebookresearch/pythia/files/3695660/error.log)

**Comment by dtchantao** [comment]
> Can you post the full error log which is cut from your screenshot?

Attached my error log for your information
[error.log](https://github.com/facebookresearch/pythia/files/3695666/error.log)

**Comment by apsdehal** [comment]
Thanks for the log. At the line https://github.com/facebookresearch/pythia/blob/master/pythia/trainers/base_trainer.py#L135 can you add parameter to DistributedDataParallel `find_unused_parameters=True`.

These kind of issues are fixed in v0.4 but there are lot of breaking changes.

**Comment by dtchantao** [comment]
> Thanks for the log. At the line https://github.com/facebookresearch/pythia/blob/master/pythia/trainers/base_trainer.py#L135 can you add parameter to DistributedDataParallel `find_unused_parameters=True`.
> 
> These kind of issues are fixed in v0.4 but there are lot of breaking changes.

Thanks! I will try that. And for the case 1, in the distributed mode, is it true that the dataset will copied/read for 4 times? Means if I have 4 GPU, every GPU will need copy 1 dataset?

**Comment by apsdehal** [comment]
Yes. DDP requires spawning one process per GPU so each process will have its own copy. So, don't fast read.

**Comment by teslacool** [comment]
After adding `find_unused_parameters=True` and replacing `broadcast_scalar` function, this code can run successfully.

**Comment by dtchantao** [comment]
> 
> 
> Can you replace https://github.com/facebookresearch/pythia/blob/master/pythia/utils/distributed_utils.py#L52 with https://github.com/facebookresearch/pythia/blob/v0.4/pythia/utils/distributed_utils.py#L52?

Hi, thanks for your solution. It works for single dataset training. But when I change to multiple dataset training, it gets stuck. 

My command:
![image](https://user-images.githubusercontent.com/44595164/68564371-67672680-048b-11ea-8f82-61c7459623d5.png)

Result:
![image](https://user-images.githubusercontent.com/44595164/68564421-89f93f80-048b-11ea-9e66-28ec1e616902.png)

And only one GPU is being used:
![image](https://user-images.githubusercontent.com/44595164/68564460-a85f3b00-048b-11ea-96f5-3774bb4df776.png)

**Comment by apsdehal** [comment]
Hmm, let me see what is the issue and I will get back to you after some time.
