### ISSUE TITLE
[Minor] validation time calculation during training

### ISSUE THREAD

**Issue by ronghanghu** [facebookresearch/mmf#182]
## Misleading display in "validation time"

The current implementation displays "validation time" as the time elapsed for all the training and validation iterations between two full validation runs. I find this a bit misleading.

It's my understanding that to compute the actual time spent on running a full validation, this line (https://github.com/facebookresearch/pythia/blob/d6c4c52dea0dd3fe36000ff2654ef479abfd4246/pythia/trainers/base_trainer.py#L368) should be moved before the evaluation line (https://github.com/facebookresearch/pythia/blob/d6c4c52dea0dd3fe36000ff2654ef479abfd4246/pythia/trainers/base_trainer.py#L356).

I suggest either changing the name to "time elapsed between validations", or moving L368 before L356 to compute the actual validation time.

**Comment by apsdehal** [comment]
Thanks. This was fixed in dev version and should land in next version. I will keep it open until then.
