### ISSUE TITLE
About text_processor and answer_processor in vqa2.yml

### ISSUE THREAD

**Issue by cylvzj** [facebookresearch/mmf#195]
## ❓ Questions and Help
Hello, ask a question. What is the role of text_processor and answer_processor in vqa2.yml, and the corresponding vocab_file: vocabs/vocabulary_100k.txt and vocab_file: vocabs/answers_vqa.txt What is the use?

**Comment by apsdehal** [comment]
Hi,
text processor processes question with vocab vocab_100k.txt (a bigger vocab to cover lot of words that can be in question) and answer processor is used processing answers which are 3129 for VQA 2.0 and contained in answers vqa.txt

**Comment by cylvzj** [comment]
Hello, thank you for your reply.
The text processor handles the problem and is a big vocab.
The answer processor handles the answer and is also a vocab, just a little bit smaller. Ask, why use two vocabs?

If I want to use pythia's 1.Pythia VQA. 2.BUTD Captioning. How to modify it in China? (I translated the VQA 2.0 ImDB and COCO Caption data sets into Chinese)

**Comment by cylvzj** [comment]
Hi,
Both the text processor and the answer processor use vocabulary_100k.txt. Is this vocab not working?

**Comment by cylvzj** [comment]
Hi,
Does vocabulary_100k.txt cover all the vocabulary (the data set has been added since then, this file does not need to change)?
Answer_vqa.txt contains the vocabulary in all the answers?

If you subsequently add a new dataset and continue training on the previous model, answer_vqx.txt may change and the answering dictionary (self.answer_dict) will change. Does this conflict with the model?

**Comment by apsdehal** [comment]
>Ask, why use two vocabs?
You can use same, but then final classifier will be really huge and hard to learn directly
> If I want to use pythia's 1.Pythia VQA. 2.BUTD Captioning. How to modify it in China?
For text processor, convert vocab_100k.txt to chinese and then use a glove vectors for chinese. Also, modify answers directly to chines.

> Both the text processor and the answer processor use vocabulary_100k.txt. Is this vocab not working?
No, answer processor uses a different vocabulary which is answers_vqa.txt

> If you subsequently add a new dataset and continue training on the previous model, answer_vqx.txt may change and the answering dictionary (self.answer_dict) will change. Does this conflict with the model?
Yes, this will conflict as model's parameters and architecture will change, you can keep some part of the models same by loading it as a pretrained model but classifier or embedding will change if you change vocabs.

**Comment by cylvzj** [comment]
Hi, thank you for your reply.
In practical applications, the model must be constantly adding new data sets for training optimization, then the text processor (vocabulary_100k.txt) and answer processor (answer_vqa.txt) will continue to add new vocabulary so that classifiers or embedding will occur. Variety. Can I train a new dataset under the previous model, or do I need to restart training all the datasets (previous and added)?

**Comment by cylvzj** [comment]
please teach me,
If I need to use VQA and Image Captioning. Is it necessary to train the pythia-vqa2 and butd-coco data sets?
What GPU configuration is required to train VQA and Image Captioning, and how long does it take to train?

**Comment by cylvzj** [comment]
I want to ask another question.
How is vocabulary_100k.txt and answers_vqa.txt generated?

Sorry, my foundation is poor.

**Comment by apsdehal** [comment]
You can use the pretrained models as specified in the documentation if you are looking to do inference. You can also use the colab demos we have linked in the readme and documentation. 
Normally, on 2 Quadro GP100 (16GB) on 512 batch size for 22k iterations it takes 8 hours. 

Vocabulary_100k.txt is just the normal glove vocabulary, and answers_vqa are answers in vqa 2.0 dataset that appear more than 5 times. There are 3129 of these.

**Comment by cylvzj** [comment]
Thank you for your reply,
Then ask, how to train a new data set on the pre-training model?
There may be new words。

**Comment by cylvzj** [comment]
@apsdehal

**Comment by apsdehal** [comment]
I don't think there is a direct way of doing this. Since, you are changing the input vocabulary which will update the first layer of word embeddings, it will have downstream effects on everything. So, you can try with not copying the first and last layer from the pretrained model and copy everything else. 

Another alternative is to just append your new vocab to the original vocab at the end. Then, you can copy the weights for the original word embedding for the original vocabulary and initialize rest of them from pretrained chinese glove or randomly. There is no definite answer to this. You should also try to train from scratch and see how it works.

**Comment by cylvzj** [comment]
Thank you for your reply,

1. If you want to add a new dataset (possibly with new vocabulary), do you need to restart the training model pair?

2. Is it possible to make answer_vqa.txt and vocabulary_100k.txt as large as possible (including all vocabulary as much as possible) so that you don't have to worry about adding new vocabulary when adding a dataset. So you can train new data sets on pre-trained models?


3. I use demos (Pythia VQA, BUTD Captioning.) in colab (11G memory). It takes about 6 seconds to return the result. What kind of GPU configuration is needed, so that the result can be returned in 1-2 seconds?

**Comment by cylvzj** [comment]
@apsdehal

**Comment by cylvzj** [comment]
@apsdehal

**Comment by cylvzj** [comment]
@apsdehal  Thank you for your reply,

The application we are working on will continuously collect some images and manually mark them to make the predictions more accurate.

Originally, I hoped to be able to train on the basis of the original model, because each time it was time-consuming from scratch (there may be words that are not available in answer.txt), I think your company's R&D team should consider this issue?

**Comment by apsdehal** [comment]
Yes, that's a nice research problem but out-of-scope for the current project. Closing this one for now. Please open up a new issue if you face any more problems.
