### ISSUE TITLE
Pythia for image captioning

### ISSUE THREAD

**Issue by aoxolotl** [facebookresearch/mmf#201]
## ❓ Questions and Help
Hi,
I have a custom dataset of annotated images. So far I have managed to generate the detectron features for the images, the vocabulary for the captions and set up the config files correctly. When I try to train on using a butd model I encounter an error:
```
AttributeError: Key answers not found in the SampleList. Valid choices are ['text', 'caption_len', 'image_id', 'image_feature_0', 'dataset_type', 'dataset_name']
```
which I think is because my dataset only contains captions and there are no question-answer segments associated with it. 
My question is that can Pythia be setup for an image captioning / image retrieval task? What would be the steps required to train it on this custom dataset?
Thanks!

**Comment by aoxolotl** [comment]
A small update.
I also tried out captioning on the coco dataset with the command:
```
python tools/run.py --tasks captioning --datasets coco --model butd --config configs/captioning/coco/butd.yml
```
but ended up encountering this error:
```
ERROR: invalid argument 0: Tensors must have same number of dimensions: got 2 and 3 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:74
```

**Comment by apsdehal** [comment]
This should be fixed now. Closing.
