### ISSUE TITLE
Is there a way to speed up classifications on GPU?

### ISSUE THREAD

**Issue by inafi** [facebookresearch/mmf#212]
## ❓ Questions and Help
I have 3 RTX 2080s on my ubuntu 18.04.3 machine and I'm running the pythia vqa demo on images. Right now it takes around 11-12 seconds for it to process 1 image (it's running on 1 gpu). Is there a way to accelerate the running time or even run it on multiple gpus simultaneously?

Edit: Here is the nvidia-smi output when running pythia
|   0  GeForce RTX 2080    Off  | 00000000:09:00.0 Off |                  N/A |
|  0%   38C    P2    61W / 215W |   2160MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2080    Off  | 00000000:0A:00.0 Off |                  N/A |
|  0%   48C    P0    52W / 215W |     11MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 2080    Off  | 00000000:41:00.0 Off |                  N/A |
|  5%   49C    P0    44W / 215W |     11MiB /  7974MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by apsdehal** [comment]
For demo it will require multiple steps:
- Wrap you model in nn.DataParallel. It should use multiple GPUs. Replace: `model = Pythia(model_config)` with `model = torch.nn.DataParallel(Pythia(model_config))`.
- Load multiple images first to create a batch first
- Also, wrap Detectron Model code with DataParallel so it can use multiple GPUs.
- This may require more changes than what I mentioned.

**Comment by apsdehal** [comment]
I would suggest you to pre-extract the features of your images and then use pythia `run.py` to do inference instead of using the demo code to do the same.

**Comment by inafi** [comment]
When I tried wrapping with torch.nn.DataParallel, it threw an error:

```
Traceback (most recent call last):
  File "run.py", line 253, in <module>
    demo = PythiaDemo()
  File "run.py", line 41, in __init__
    self.pythia_model = self._build_pythia_model()
  File "run.py", line 78, in _build_pythia_model
    model.build()
  File "/home/2022inafi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'build'

```
Here's the method I'm using:

```
def _build_pythia_model(self):
        state_dict = torch.load('content/model_data/pythia.pth')
        model_config = self.config.model_attributes.pythia
        model_config.model_data_dir = "content/"
        #model = Pythia(model_config)
        model = torch.nn.DataParallel(Pythia(model_config))
        model.build()
        model.init_losses_and_metrics()
        if list(state_dict.keys())[0].startswith('module') and \
           not hasattr(model, 'module'):
            state_dict = self._multi_gpu_state_to_single(state_dict)

        model.load_state_dict(state_dict)
        model.to("cuda")
        model.eval()
        return model

```

**Comment by michaelroyzen** [comment]
Try adding`data_parallel: True` to pythia.yaml. That worked for me during training, and I assume it will work for inference.
