### ISSUE TITLE
LoRRA inference in Colab

### ISSUE THREAD

**Issue by michaelroyzen** [facebookresearch/mmf#219]
## ❓ Questions and Help
I am trying to adapt the Pythia VQA demo notebook (https://colab.research.google.com/drive/1Z9fsh10rFtgWe4uy8nvU4mQmqdokdIRR) to support LoRRA trained on TextVQA. When I run the adapted demo, I get the following error:

`RuntimeError: Error(s) in loading state_dict for LoRRA:
	size mismatch for classifier.module.linear_text.weight: copying a param with shape torch.Size([4047, 300]) from checkpoint, the shape in current model is torch.Size([3997, 300]).
	size mismatch for classifier.module.linear_text.bias: copying a param with shape torch.Size([4047]) from checkpoint, the shape in current model is torch.Size([3997]).
	size mismatch for classifier.module.linear_image.weight: copying a param with shape torch.Size([4047, 5000]) from checkpoint, the shape in current model is torch.Size([3997, 5000]).
	size mismatch for classifier.module.linear_image.bias: copying a param with shape torch.Size([4047]) from checkpoint, the shape in current model is torch.Size([3997]).`

I would like to adapt the notebook code as opposed to using the recommended tools/run.py command as I would like to build this into a project that supports rapid multi-batch inference without having to reload the model weights into memory. 

It seems to me this issue is caused by the model expecting 4047 entries in the answers file instead of 3997 (as found in answers_textvqa_more_than_1.txt), but I do not know why this is the case. Advice would be appreciated. Thanks!

I am using .pth from https://dl.fbaipublicfiles.com/pythia/pretrained_models/textvqa/lorra_best.pth and .yml from https://dl.fbaipublicfiles.com/pythia/pretrained_models/textvqa/lorra.yml.

**Comment by michaelroyzen** [comment]
Update: I've added lines to the txt file so that part now runs (I don't know about correctness). Now, when I actually try to perform inference on an image, I get: 

`/home/pythia_notebooks/pythia/pythia/models/lorra.py in forward(self, sample_list)
     47 
     48         context_embedding_total, _ = self.process_feature_embedding(
---> 49             "context", sample_list, text_embedding_total, ["order_vectors"]
     50         )
     51 `

`AttributeError: order_vectors not present in SampleList. Valid choices are ['text', 'text_len', 'image_feature_0', 'image_info_0', 'image_feature_1']`

**Comment by michaelroyzen** [comment]
Please refer to my Colab: https://colab.research.google.com/drive/1qWyAEmmGW3K3ueY7wOdTc3gm5fS6BkI5.

**Comment by michaelroyzen** [comment]
@apsdehal

**Comment by apsdehal** [comment]
Please use https://colab.research.google.com/drive/120xCDefxsqAmm7l6uf5nFDx5zr7msA0R

**Comment by apsdehal** [comment]
Closing as answered.

**Comment by akira-l** [comment]
meet the same problem for M4C in textvqa. 
missing image_feature_1 in code now
