### ISSUE TITLE
released COCO Karpathy train imdb has only 82783 images (should be 113287 images)

### ISSUE THREAD

**Issue by ronghanghu** [facebookresearch/mmf#220]
## 🐛 Bug

In the released imdb for the COCO Captioning dataset, the Karpathy train imdb (`coco_captions/imdb_karpathy_train.npy`) has only 82783 images. However, there should actually be 113287 images in this set.

The Karpathy split for the COCO Captioning dataset was first described [here](https://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Karpathy_Deep_Visual-Semantic_Alignments_2015_CVPR_paper.pdf) and was also used in the [BUTD paper](http://openaccess.thecvf.com/content_cvpr_2018/papers/Anderson_Bottom-Up_and_Top-Down_CVPR_2018_paper.pdf). As described in the BUTD paper, **it contains 113287 images for training, 5000 images for validation, and 5000 images for testing.** However, in Pythia repo, the released [COCO imdbs](https://dl.fbaipublicfiles.com/pythia/data/imdb/coco_captions.tar.gz) from the [docs](https://learnpythia.readthedocs.io/en/latest/tutorials/quickstart.html) only contains **82783 training images**, 5000 validation images, and 5000 test images.

It seems that the released training imdb was actually the COCO's train2014 split, instead of the Karpathy train split.

Could you take a look at it? Thanks a lot!

## To Reproduce

```
# download the released COCO imdbs
wget https://dl.fbaipublicfiles.com/pythia/data/imdb/coco_captions.tar.gz
tar xf coco_captions.tar.gz

python -c "import numpy as np; imdb = np.load('coco_captions/imdb_karpathy_train.npy', allow_pickle=True); images = {d['image_id'] for d in imdb[1:]}; print('there are {} images in train imdb'.format(len(images)))"
# prints "there are 82783 images in train imdb"
```

## Expected behavior

There should be 113287 training images in `coco_captions/imdb_karpathy_train.npy`, not 82783.

**Comment by vedanuj** [comment]
Thanks for finding this issue. We will update the imdb files and release the pretrained BUTD model soon.

**Comment by vedanuj** [comment]
The imdb for `coco_captions` has been updated at https://dl.fbaipublicfiles.com/pythia/data/imdb/coco_captions.tar.gz. The new file added is `imdb_karpathy_restval.npy` which can be used along with `imdb_karpathy_train.npy` for full 113287 images training.
