### ISSUE TITLE
Save scores from evaluation

### ISSUE THREAD

**Issue by Karol-G** [facebookresearch/mmf#222]
## ❓ Questions and Help
Hi,

I want to evaluate pythia on the train-, val-, and testset and save the best score from every prediction.
My problem is that I am quite confused about which modules to modify.
Could you give me a hint to which module I should look into?

**Comment by vedanuj** [comment]
The scores are calculated in batches. If you want to save for every prediction then you will need to set the batch size to 1 and log in this method : https://github.com/facebookresearch/pythia/blob/2ad4c4cfe121e951db12efa3fe5b6f1cc0188da7/pythia/trainers/base_trainer.py#L380
