### ISSUE TITLE
Pythia training on other languages

### ISSUE THREAD

**Issue by YoussefSaadYoussef** [facebookresearch/mmf#223]
## ❓ Questions and Help
could I train Pythia for image captioning and VQA on another language not only English? 
if yes what files should I change?

**Comment by vedanuj** [comment]
Currently `pythia` uses `fasttext` glove model for english language embeddings. We do not have any immediate plans to support other languages. One possible thing that you can do is translate the other lanaguage to English and try image captioning and VQA with `pythia`.
