### ISSUE TITLE
Version dependency conflict of tqdm

### ISSUE THREAD

**Issue by canhongpoxiao** [facebookresearch/mmf#229]
## 🐛 Bug

When I run `python setup.py develop`
I get error 
error: tqdm 4.19.9 is installed but tqdm>=4.27 is required by {'transformers'}
then I change the tqdm version and rerun I get error
error: tqdm 4.43.0 is installed but tqdm==4.19.9 is required by {'torchvision'}

**Comment by apsdehal** [comment]
torchvision version also requires an update to the latest.
