### ISSUE TITLE
Question about fastText when start training

### ISSUE THREAD

**Issue by SuNicole** [facebookresearch/mmf#231]
## ❓ Questions and Help
I got error  
**ModuleNotFoundError: No module named 'fastText'** 
when I run   _python tools/run.py --tasks vqa --datasets textvqa --model lorra --config \configs/vqa/textvqa/lorra.yml_ in quickStart .
 I tried to use _pip install fastText_  but it didn't change the result. 
 When I try to use '_git clone https://github.com/facebookresearch/fastText.git_ ' , it reported error '**cannot import name 'load_model'**'. 
Is this error relate to the version of fastText or python? How to solve this problem?

**Comment by apsdehal** [comment]
Duplicate of #234
