### ISSUE TITLE
OCR words from images

### ISSUE THREAD

**Issue by gokulanv** [facebookresearch/mmf#237]
## ❓ Questions and Help
I would like to output/get the detected OCR tokens from the input images while inferring on the M4C model. Any suggestion on how this can be done? @ronghanghu @apsdehal

**Comment by ronghanghu** [comment]
Hi, if you want to access the per-image OCR results in the TextVQA images, they are stored in `ocr_tokens` key in the imdbs.

If you want to see whether a predicted answer word in the M4C model's prediction come from OCR or fixed vocabulary, one can check the `'pred_source'` in field in the dumped json EvalAI prediction file. This field is a list containing either `'VOCAB'` or `'OCR'` indicating which source each answer word is predicted from.

**Comment by gokulanv** [comment]
Thank you. One more question!
The Textcaps Lorra model has a demo notebook that contains the predict function which takes in an image and gives out a caption just for that image. Is there a similar functionality in M4C ? If not, can you direct me where I can make changes to get this implemented? @ronghanghu

**Comment by apsdehal** [comment]
Not yet but you can have a look at LoRRA demo. https://colab.research.google.com/drive/120xCDefxsqAmm7l6uf5nFDx5zr7msA0R?usp=sharing Closing as resolved.
