### ISSUE TITLE
Bounding boxes for visualizing attention maps

### ISSUE THREAD

**Issue by mchandak29** [facebookresearch/mmf#255]
## ❓ Questions and Help

As stated in #145: To visualize attention maps on vqav2 we would need bounding boxes. Can you provide some support for that?

**Comment by apsdehal** [comment]
the features file should have bounding box information. Is there something else you were looking for specifically?

**Comment by mchandak29** [comment]
Ive downloaded the detectron_fix_100 provided in the quick start, it doesn't have the required bbox information. Is there something I am missing ?

**Comment by Ra0k** [comment]
> the features file should have bounding box information. Is there something else you were looking for specifically?

Hi, how could I get these bounding boxes exactly? Which part of the code? Are these coordinates extracted in real-time directly from ResNet-152 or they are provided in the dataset as ground truth?
