### ISSUE TITLE
error happened during training !!

### ISSUE THREAD

**Issue by stnlrgrs** [facebookresearch/mmf#256]
## ❓ Questions and Help
Hi, I met an error when I used this command line:

python3 tools/run.py --datasets textvqa --model lorra --config configs/vqa/textvqa/lorra.yaml

usage: run.py [-h] [-co CONFIG_OVERRIDE] [--local_rank LOCAL_RANK] ...
run.py: error: unrecognized arguments: --datasets

Can you tell me what's wrong and how to solve it?   Thanks!

**Comment by apsdehal** [comment]
The configuration system has changed in the latest version of MMF (Pythia). You may want to have a look at [configuration docs](https://mmf.readthedocs.io/en/latest/notes/configuration.html). For your command I would run this after installing the project:
```
mmf_run dataset=textvqa model=lorra config=projects/lorra/configs/textvqa/defaults.yaml
```
Caution: This would reinstall features, annotations and other things required for TextVQA automatically. Make sure you have enough space.

If you want to use original commit where you command would work see [README](../tree/master/README.md)

**Comment by apsdehal** [comment]
Closing as already responded. If you face any other issues, please open a new one.
