### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.scripts'

### ISSUE THREAD

**Issue by tonytang731** [facebookresearch/mmf#260]
## ❓ Questions and Help

Hi,

We just installed MMF and tried unzipping data using the command "mmf_convert_hm --zip_file=x --password=y" where x and y are replaced with correct values. However, we get the following error. Have you encountered a similar error? Thank you very much for your help!

![image](https://user-images.githubusercontent.com/50162066/82374427-ab138d80-99e4-11ea-80f3-cc509d621a19.png)

**Comment by tonytang731** [comment]
Solved

**Comment by apsdehal** [comment]
@tonytang731 Can you provide information on how you solved this for bookkeeping purposes on our side?

**Comment by tonytang731** [comment]
Sure. Instead of using pip install method, we tried the "install from source" method and it works. 👍 

![image](https://user-images.githubusercontent.com/50162066/82382342-60e4d900-99f1-11ea-9ed2-a8e9a26672ad.png)
