### ISSUE TITLE
Colab notebook is not working

### ISSUE THREAD

**Issue by Ra0k** [facebookresearch/mmf#264]
## 🐛 Bug

The Google Colab Notebook linked in the [Quickstart](https://mmf.readthedocs.io/en/latest/notes/quickstart.html) is not working. 

## To Reproduce

1. open [notebook](https://colab.research.google.com/drive/1Z9fsh10rFtgWe4uy8nvU4mQmqdokdIRR)
2. click to "Open in playground"
3. run all

<img width="841" alt="Screenshot 2020-05-20 at 11 43 37" src="https://user-images.githubusercontent.com/19765153/82431620-2762ab00-9a8f-11ea-991d-0c4d55cbef21.png">

**Comment by vedanuj** [comment]
This is due to the fact that the notebook is still using old pythia and has to be migrated to new mmf namespace. We are in the process of updating the colab notebooks. Please stay tuned.

**Comment by MarijnQ** [comment]
Mate, life saver! Just started playing around with it but I came across this issue too.
Ill stay updated! Thanks!

**Comment by MarijnQ** [comment]
It's still giving me an error.... Has there been a fix yet?

**Comment by IsraelAbebe** [comment]
@MarijnQ  did you solve your issue?

**Comment by MarijnQ** [comment]
Kast time I checked it still wasn't fixed...

**Comment by mubtaseemz** [comment]
Replacing Pythia with MMF works for me:

`from mmf.utils.configuration import ConfigNode`
`from mmf.datasets.processors import VocabProcessor, CaptionProcessor`
`from mmf.models.butd import BUTD`
`from mmf.common.registry import registry`
`from mmf.common.sample import Sample, SampleList`

However, I get the following attribute error
![image](https://user-images.githubusercontent.com/32416908/89189134-60f08000-d5c1-11ea-8584-1d7a1f771280.png)

Any pointers for this @vedanuj ? Thanks!

**Comment by apsdehal** [comment]
MMF Pythia Demo should be working now at https://colab.research.google.com/drive/1Z9fsh10rFtgWe4uy8nvU4mQmqdokdIRR?usp=sharing. Closing this as fixed. We will later move this notebook to its proper place under MMF notebooks.

**Comment by ajandrey** [comment]
> MMF Pythia Demo should be working now at https://colab.research.google.com/drive/1Z9fsh10rFtgWe4uy8nvU4mQmqdokdIRR?usp=sharing. Closing this as fixed. We will later move this notebook to its proper place under MMF notebooks.

But this is VQA. 
This issue is about the Captioning Demo, that is still with error.
