### ISSUE TITLE
Data Loading

### ISSUE THREAD

**Issue by tonytang731** [facebookresearch/mmf#266]
## ❓ Questions and Help
Hi,

After we load the data on Google Colab, we have this

![image](https://user-images.githubusercontent.com/50162066/82509525-be4e5800-9acd-11ea-873d-4ee1f27f6503.png)

and it seems to me that the data is moved to the "/root/.cache/torch/mmf/data" folder. However, I cannot locate this corresponding folder in my drive, and we are not able to reproduce the baseline models since the data is not found. 

![image](https://user-images.githubusercontent.com/50162066/82509715-50eef700-9ace-11ea-8bf1-cead4268ddfb.png)

Thank you for any insights or suggestions!

**Comment by apsdehal** [comment]
Hidden folders (the ones with "." in the start) are not shown by default in colab's grid view. I would suggest you to do
```
!ls /root/.cache/torch/mmf/data
```
to see if folder is actually present.

**Comment by tonytang731** [comment]
Thanks! It's weird that the data disappeared.  I will try to figure it out.

**Comment by apsdehal** [comment]
Data will disappear with command. MMF moves it to its cache directory. The ls command that I gave you points to cache directory.

**Comment by tonytang731** [comment]
Thank you very much for your time! Now I have this.

![image](https://user-images.githubusercontent.com/50162066/82517006-cadcab80-9ae1-11ea-93c5-7eaa5c315eae.png)
