### ISSUE TITLE
Training the Image-Region Model

### ISSUE THREAD

**Issue by tonytang731** [facebookresearch/mmf#268]
## ❓ Questions and Help
Hi,

I am currently trying to train a model with 

"mmf_run config=<REPLACE_WITH_BASELINE_CONFIG> model=<REPLACE_WITH_MODEL_KEY> dataset=hateful_memes"

and my code for Image-Region Model is 

![image](https://user-images.githubusercontent.com/50162066/82518382-e5fcea80-9ae4-11ea-83e5-4cc82fdce140.png)

And it seems that we need to specify extra stuff

![image](https://user-images.githubusercontent.com/50162066/82518319-bcdc5a00-9ae4-11ea-9875-1a1e78f7be26.png)

Sorry if I missed anything, and thank you very much for your help!

**Comment by vedanuj** [comment]
Can you run a clean `pip install --upgrade --pre mmf` and try it? In my environment this is working. 

Also please list the steps you did before you hit this error.

**Comment by tonytang731** [comment]
Thanks for your answer! I am using the second installation method "install from source". I will try the first method and see if it solves my problem.

**Comment by tonytang731** [comment]
One more question:

If I am using Google Colab and the first "pip install method". Do we need to reload data every time we restart the script? Thank you!

**Comment by apsdehal** [comment]
If you are disconnected from the runtime for long time, it will reset and you will have to restart again.

**Comment by tonytang731** [comment]
Thanks! Now I used the pip install method and loaded the data.

This time I got another error like this (sort_keys)

![image](https://user-images.githubusercontent.com/50162066/82598385-353c2d00-9b70-11ea-904b-5878154b73b7.png)
 
In addition, it seems that the free version of Google Colab doesn't have enough Disk Memory. Do you have any tools recommended for this competition? Thank you very much! We are currently thinking about upgrading to Google Colab Pro or AWS EC2.

![image](https://user-images.githubusercontent.com/50162066/82598541-6f0d3380-9b70-11ea-80eb-b545f4966496.png)

**Comment by apsdehal** [comment]
YAML one is a known issue. In next release, multiple issues relating to colab will be fixed including prediction issue. For now, update version of PyYAML by running `!pip install --upgrade PyYAML` which will fix your this issue.

For disk, we are thinking to add a command line utility to clean up stuff that MMF caches for saving the space. For now, you can delete the features tar file that was download by `rm /root/.cache/torch/mmf/data/dataset/hateful_memes/defaults/features/features.tar.gz`. That should save a lot of space for you. 

Once you start training, models will be checkpoint which can again take space, you can increase checkpoint interval by adding `training.checkpoint_interval=5000` or any number at the end of your command.

**Comment by tonytang731** [comment]
Thank you! It's very helpful.
