### ISSUE TITLE
Working with models and data

### ISSUE THREAD

**Issue by dni138** [facebookresearch/mmf#276]
## ❓ Questions and Help
My team and I tried to get some benchmark scores using LoRRA, Pythia, and other pretrained models, but could get them up and running. Below is a picture of the error.

![Screen Shot 2020-05-24 at 3 53 10 PM](https://user-images.githubusercontent.com/28276541/82833310-a7bc4e00-9e8b-11ea-8bd7-fac4cb15655c.png)

Should we be downloading more files and data than what is given in the challenge? I downloaded the data from the challenge site, and then followed these install instructions after forking the repo:

https://mmf.readthedocs.io/en/latest/notes/installation.html

Thanks!

**Comment by vedanuj** [comment]
Hi , we are working on updating the documentation. It is outdated as we are in beta release of a new version. Meanwhile if you want to run training for `lorra` model, try this command : 

```
mmf_run config=projects/lorra/configs/textvqa/defaults.yaml datasets=textvqa model=lorra run_type=train_val
```

**Comment by wind91725** [comment]
Ok,looking forward to your updating documentation.
