### ISSUE TITLE
Help with Imdbs for M4C

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/mmf#279]
## ❓ Questions and Help
@ronghanghu I have a few questions on the imdbs created for datasets for M4C model

1. For each image there is a field called "ocr_toens" and "ocr_normalized_boxes". How are these normalized boxes created from bounding boxes in "ocr_tokens" ? Is the  ordering of tokens in "ocr_toens" and "ocr_norrmalized_boxes" important ?
2. How is "valid_answers" and "answers"  in the imdb different?
3. In cases of datasets like ST-VQA where there are only 2  ground truth answers per question, are 10  answers in  "answers" , actual answers replicated 10 times ?
4. It will be really helpful if you have a script/sample-script which you have used to create imdbs for a dataset like ST-VQA
----
Thanks in advance

**Comment by ronghanghu** [comment]
Hi,
> For each image there is a field called "ocr_toens" and "ocr_normalized_boxes". How are these normalized boxes created from bounding boxes in "ocr_tokens"? 

The `ocr_normalized_boxes` key contains bounding boxes normalized to the range between 0 and 1. It is obtained as `[x_min / W, y_min / H, x_max / W, y_max / H]`, where (x_min, y_min) is the upper left corner of the bounding box in pixels, (x_max, y_max) is the lower right corner of the bounding box in pixels, and H and W are image height and width (in pixels) respectively.

> Is the ordering of tokens in "ocr_toens" and "ocr_norrmalized_boxes" important ?

The order of the OCR tokens in the imdbs is the same as their order returned by the OCR system (Rosetta in our case). In practice this usually means that they are ordered from left to right and from upper to lower in the image. Our M4C model is invariant to the order of the OCR tokens in the imdbs.

> How is "valid_answers" and "answers" in the imdb different?

On the TextVQA, ST-VQA, and OCR-VQA datasets, `valid_answers` and `answers` are exactly the same. (But `valid_answers` and `answers` might be different on the VQAv2 dataset imdbs.)

> In cases of datasets like ST-VQA where there are only 2 ground truth answers per question, are 10 answers in "answers" , actual answers replicated 10 times ?

In the case where there are 2 ground-truth answers, each answer is duplicated 5 times to make 10 total answers. In the case where there 1 ground-truth answer, each answer is duplicated 10 times.

> It will be really helpful if you have a script/sample-script which you have used to create imdbs for a dataset like ST-VQA

Attached 
[stvqa_build_imdb.py.zip](https://github.com/facebookresearch/mmf/files/4699404/stvqa_build_imdb.py.zip) is part of the codebase we used to build the ST-VQA imdb. Hope that it can be helpful to you!

**Comment by mineshmathew** [comment]
thanks a lot for a quick and detailed reply :)
