### ISSUE TITLE
Object features and features of OCR tokens' boxes

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/mmf#280]
## ❓ Questions and Help
This question is specific to M4C model for VQA. I hope @ronghanghu  will be able to help me

**which mask-rcnn-benchmark to use**
I see that features of objects are extracted using [this script](https://github.com/facebookresearch/mmf/blob/project/m4c/pythia/scripts/features/extract_features_vmb.py) and features of ocr boxes using[ this one](https://github.com/facebookresearch/mmf/blob/project/m4c/pythia/scripts/features/extract_features_vmb.py)

And in the second script for OCR boxes it is mentioned that mask rcnn benchmark need to be installed from https://github.com/ronghanghu/vqa-maskrcnn-benchmark-m4c

Can I use the above  mask-rcnn-benhmark repo  with _extract_features_vmb.py_ for getting object features? Or should I use the previous repo here - https://gitlab.com/meetshah1995/vqa-maskrcnn-benchmark ( If I remember correctly for LoRRA this gitlab repo is used)

**On Resnet features**
LoRRA uses resnet features too along with object features. Does M4C uses resnet512 features as well. In any case which is the right script to get resnet512 features for my own set of images

Thanks in advance

**Comment by mineshmathew** [comment]
hi @ronghanghu 
I have been trying to install the maskrcnn benchmark  as given in https://github.com/ronghanghu/vqa-maskrcnn-benchmark-m4c/blob/bbox_feat_extract/INSTALL.md

The instructions seems  to be the same one as given for the original repo here - https://github.com/facebookresearch/maskrcnn-benchmark

I have been facing lot of issues with pytorch versions and gcc versions. Do you suggest to follow the same instructions as in the INSTALL.md? Since you have recently used it for M4C project do you think pytorch 1.4 or recent versions are compatible with this mask-rcnn benchmark code


I have a few questions in this regard:

1. The instructions says `cd github` ; where/when  is this folder created?
2. Finall it says to `git clone https://github.com/facebookresearch/maskrcnn-benchmark.git`. Is it the right repo ? Should not I clone https://github.com/ronghanghu/vqa-maskrcnn-benchmark-m4c.git ?

**Comment by ronghanghu** [comment]
Hi @mineshmathew,

I used PyTorch 1.3 in my experiments for feature extraction, but PyTorch 1.4 or higher version should work as well. To install, one can simply do the following:
```
git clone https://github.com/ronghanghu/vqa-maskrcnn-benchmark-m4c.git
cd vqa-maskrcnn-benchmark-m4c
python setup.py build develop
```
