### ISSUE TITLE
Vocabulary used for answer processor for TextVQA

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/mmf#283]
## ❓ Questions and Help
Hi this is regarding pythia v0.4. For the [config file for Text VQA](https://github.com/facebookresearch/mmf/blob/v0.4/pythia/common/defaults/configs/datasets/vqa/textvqa.yml) I see that a vocabulary file - vocabs/answers_textvqa_8k.txt is mentioned under answer processor.

Can you please help me understand why this vocab file is required. The vocab corresponding to output classes is another vocabulary with nearly 4000 classes. What is this bigger vocab used for?

**Comment by apsdehal** [comment]
Bigger vocab is used for `LoRRA + LA` model reported in the [TextVQA](https://arxiv.org/abs/1904.08920) paper. Shorter vocabulary is for  `LoRRA + SA` model.
