### ISSUE TITLE
Fail to run pytest after installation

### ISSUE THREAD

**Issue by ZhangYuef** [facebookresearch/mmf#293]
### Environment
- python: 3.7
- pytorch 1.5 + CUDA10.1

### Problem
I successfully installed the `mmf`  from source with `pip install --editable .`.
After that, I run `pytest ./tests/` which is suggested in the documents to check the library. Then I got the error as following:

>  tests/modules/test_metrics.py::TestModuleMetrics::test_caption_bleu4
>   /home/jupyter/.local/lib/python3.7/site-packages/nltk/lm/vocabulary.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
>     from collections import Counter, Iterable
> 
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_finalize_and_restore_from_it
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_finalize_and_resume_file
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_pretrained_load
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_resets
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_save_and_load_state_dict
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_zoo_load
>   /home/jupyter/tutorials/test/mmf/mmf/models/base_model.py:162: UserWarning: 'losses' already present in model output. No calculation will be done in base model.
>     "'losses' already present in model output. "
> 
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_finalize_and_resume_file
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_zoo_load
>   /home/jupyter/tutorials/test/mmf/mmf/utils/checkpoint.py:224: UserWarning: 'optimizer' key is not present in the checkpoint asked to be loaded. Skipping.
>     "'optimizer' key is not present in the "
> 
> -- Docs: https://docs.pytest.org/en/latest/warnings.html
> ================================================= short test summary info =================================================
> FAILED tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_save_and_load_state_dict - RuntimeError: Expected objec...
> ================================== 1 failed, 66 passed, 17 warnings in 72.52s (0:01:12) ===================================

I have no idea now why this error happens. So if anyone else who has faced this problem or know how to solve it, please help me to debug it.

Thanks for any comment or suggestion.

**Comment by apsdehal** [comment]
Can you post the full error, is it related to cuda?

**Comment by ZhangYuef** [comment]
> Can you post the full error, is it related to cuda?

Thanks for this quick response!
This is the whole error log I got after running `CUDA_VISIBLE_DEVICES=0 pytest -v ./tests/utils/test_checkpoint.py'.
> plugins: arraydiff-0.3, openfiles-0.4.0, astropy-header-0.1.2, hypothesis-5.10.4, remotedata-0.3.1, doctestplus-0.4.0
> collected 7 items                                                                                                         
> 
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_finalize_and_restore_from_it PASSED                       [ 14%]
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_finalize_and_resume_file PASSED                           [ 28%]
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_pretrained_load PASSED                                    [ 42%]
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_resets PASSED                                             [ 57%]
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_save_and_load_state_dict FAILED                           [ 71%]
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_save_config PASSED                                        [ 85%]
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_zoo_load PASSED                                           [100%]
> 
> ======================================================== FAILURES =========================================================
> ____________________________________ TestUtilsCheckpoint.test_save_and_load_state_dict ____________________________________
> 
> self = <tests.utils.test_checkpoint.TestUtilsCheckpoint testMethod=test_save_and_load_state_dict>
> 
>     def test_save_and_load_state_dict(self):
>         with mock_env_with_temp() as d:
>             checkpoint = Checkpoint(self.trainer)
>             self._init_early_stopping(checkpoint)
>             self._do_a_pass()
>             # Test normal case
>             checkpoint.save(1500)
>     
>             self.assertTrue(
>                 PathManager.exists(os.path.join(d, "models", "model_1500.ckpt"))
>             )
>             self.assertTrue(PathManager.exists(os.path.join(d, "current.ckpt")))
>             self.assertFalse(PathManager.exists(os.path.join(d, "best.ckpt")))
>             os.remove(os.path.join(d, "models", "model_1500.ckpt"))
>             os.remove(os.path.join(d, "current.ckpt"))
>     
>             best_model = deepcopy(self.trainer.model)
>             best_optimizer = deepcopy(self.trainer.optimizer)
>             # Test with update_best
>             checkpoint.save(2000, update_best=True)
>     
>             self.assertTrue(
>                 PathManager.exists(os.path.join(d, "models", "model_2000.ckpt"))
>             )
>             self.assertTrue(PathManager.exists(os.path.join(d, "best.ckpt")))
>             self.assertTrue(PathManager.exists(os.path.join(d, "current.ckpt")))
>     
>             self._do_a_pass()
>             checkpoint.save(2500)
>     
>             # Test resume
>             self.trainer.config.checkpoint.resume = True
>     
>             current_model = deepcopy(self.trainer.model)
>             current_optimizer = deepcopy(self.trainer.optimizer)
>             checkpoint.load_state_dict()
>     
>             self.assertFalse(
>                 compare_state_dicts(
>                     self.trainer.model.state_dict(), best_model.state_dict()
>                 )
>             )
>             self.assertTrue(
>                 compare_state_dicts(
>                     self.trainer.model.state_dict(), current_model.state_dict()
>                 )
>             )
>             self.assertFalse(
>                 self._compare_optimizers(self.trainer.optimizer, best_optimizer)
>             )
>             self.assertFalse(
>                 self._compare_optimizers(
>                     self.trainer.optimizer, best_optimizer, skip_keys=True
>                 )
>             )
>             self.assertFalse(
>                 self._compare_optimizers(self.trainer.optimizer, current_optimizer)
>             )
>             self.assertTrue(
>                 self._compare_optimizers(
>                     self.trainer.optimizer, current_optimizer, skip_keys=True
>                 )
>             )
>     
>             base_0_weight_current = self.trainer.model.base[0].weight.data.clone()
>     
>             # Test resume_best
>             self.trainer.config.checkpoint.resume = True
>             self.trainer.config.checkpoint.resume_best = True
>     
>             checkpoint.load_state_dict()
>     
>             self.assertTrue(
>                 compare_state_dicts(
>                     self.trainer.model.state_dict(), best_model.state_dict()
>                 )
>             )
>             self.assertFalse(
>                 self._compare_optimizers(self.trainer.optimizer, best_optimizer)
>             )
>             self.assertTrue(
>                 self._compare_optimizers(
>                     self.trainer.optimizer, best_optimizer, skip_keys=True
>                 )
>             )
>             self.assertFalse(
>                 self._compare_optimizers(self.trainer.optimizer, current_optimizer)
>             )
>             self.assertFalse(
>                 self._compare_optimizers(
>                     self.trainer.optimizer, current_optimizer, skip_keys=True
>                 )
>             )
>             base_0_weight_best = self.trainer.model.base[0].weight.data.clone()
>     
>             self.trainer.config.checkpoint.resume_best = False
>             # Test distributed settings
>             self.trainer.model = torch.nn.DataParallel(self.trainer.model)
>             checkpoint.load_state_dict()
>     
>             self.assertTrue(
>                 torch.equal(
> >                   self.trainer.model.module.base[0].weight, base_0_weight_current
>                 )
>             )
> E           RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'other' in call to _th_equal
> 
> tests/utils/test_checkpoint.py:201: RuntimeError
> ==================================================== warnings summary =====================================================
> /opt/conda/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15
>   /opt/conda/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>     import imp
> 
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_finalize_and_restore_from_it
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_finalize_and_resume_file
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_pretrained_load
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_resets
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_save_and_load_state_dict
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_zoo_load
>   /home/jupyter/tutorials/test/mmf/mmf/models/base_model.py:162: UserWarning: 'losses' already present in model output. No calculation will be done in base model.
>     "'losses' already present in model output. "
> 
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_finalize_and_resume_file
> tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_zoo_load
>   /home/jupyter/tutorials/test/mmf/mmf/utils/checkpoint.py:224: UserWarning: 'optimizer' key is not present in the checkpoint asked to be loaded. Skipping.
>     "'optimizer' key is not present in the "
> 
> -- Docs: https://docs.pytest.org/en/latest/warnings.html
> ================================================= short test summary info =================================================
> FAILED tests/utils/test_checkpoint.py::TestUtilsCheckpoint::test_save_and_load_state_dict - RuntimeError: Expected objec...
> ========================================= 1 failed, 6 passed, 9 warnings in 9.18s =========================================

I think you are right. It seems the program doesn't use GPU/cuda in a proper way. But how could I solve it?

**Comment by apsdehal** [comment]
This error is fine and shouldn't affect your normal workflow. You can skip this test for now and move ahead with your programming. I will fix it properly in a PR. Thanks for reporting this. #257 is related to this but needs to fixed properly.

**Comment by ZhangYuef** [comment]
Thanks @apsdehal 's help! I got it. 

For the others who will see this issue in the future: this _error_ is related with the parameters' initialization in test file `tests/utils/test_checkpoint.py `. ([link](https://github.com/facebookresearch/mmf/pull/257#issuecomment-630675387)) 
It's the error in test file so it will not hurt models' usage. Other people have already raised a PR (#257) for this but it has not been merged yet. 

I will close this issue here.
