### ISSUE TITLE
mmf installation error

### ISSUE THREAD

**Issue by AbSaifi** [facebookresearch/mmf#299]
pip install --upgrade --pre mmf
Collecting mmf
  Using cached mmf-1.0.0rc8.tar.gz (159 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Abdurrabb\AppData\Local\Continuum\anaconda3\envs\DD_HM\python.exe' 'C:\Users\Abdurrabb\AppData\Local\Continuum\anaconda3\envs\DD_HM\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\ABDURR~1\AppData\Local\Temp\tmp2g_a_4ol'
       cwd: C:\Users\Abdurrabb\AppData\Local\Temp\pip-install-mi9790dx\mmf
  Complete output (20 lines):
  Traceback (most recent call last):
    File "C:\Users\Abdurrabb\AppData\Local\Continuum\anaconda3\envs\DD_HM\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
      main()
    File "C:\Users\Abdurrabb\AppData\Local\Continuum\anaconda3\envs\DD_HM\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\Abdurrabb\AppData\Local\Continuum\anaconda3\envs\DD_HM\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Abdurrabb\AppData\Local\Temp\pip-build-env-073dip2a\overlay\Lib\site-packages\setuptools\build_meta.py", line 147, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\Abdurrabb\AppData\Local\Temp\pip-build-env-073dip2a\overlay\Lib\site-packages\setuptools\build_meta.py", line 128, in _get_build_requires
      self.run_setup()
    File "C:\Users\Abdurrabb\AppData\Local\Temp\pip-build-env-073dip2a\overlay\Lib\site-packages\setuptools\build_meta.py", line 249, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\Abdurrabb\AppData\Local\Temp\pip-build-env-073dip2a\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 107, in <module>
      REQUIREMENTS = (fetch_requirements(),)
    File "setup.py", line 52, in fetch_requirements
      with open(requirements_file) as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Abdurrabb\AppData\Local\Continuum\anaconda3\envs\DD_HM\python.exe' 'C:\Users\Abdurrabb\AppData\Local\Continuum\anaconda3\envs\DD_HM\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\ABDURR~1\AppData\Local\Temp\tmp2g_a_4ol' Check the logs for full command output.

**Comment by apsdehal** [comment]
Can you try installing from source for now and see if that works? We don't have full fledged support for Windows at the moment but this error probably won't come when you install from source. See https://mmf.readthedocs.io/en/latest/notes/installation.html#install-from-source

Can you provide me output of `python -m torch.utils.collect_env` for my debugging purposes?

**Comment by AbSaifi** [comment]
Hi, I tried installing from the source and installation was successful. I had to separately install visual c++ builder tools though for successful installation of fasttext, which is present in requirement of mmf.

thanks for help.
Is the o/p of collect_env still needed or shall I mark this thread closed.

**Comment by apsdehal** [comment]
If you can provide me for my debugging purposes for the pip package, that would be great. After that feel free to close the issue. Thanks.

**Comment by AbSaifi** [comment]
python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Microsoft Windows 10 Home Single Language
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.6
[pip] numpydoc==0.9.1
[pip] torch==1.5.0
[pip] torchtext==0.5.0
[pip] torchvision==0.6.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      245
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.0.14           py37h14836fe_0
[conda] mkl_random                1.1.0            py37h675688f_0
[conda] pytorch                   1.5.0           py3.7_cuda102_cudnn7_0    pytorch
[conda] torchtext                 0.5.0                    pypi_0    pypi
[conda] torchvision               0.6.0                py37_cu102    pytorch

**Comment by aka4rKO** [comment]
I was getting the same issue but when I tried installing from source I still get an error which doesn't allow me to download `torchtext==0.5.0`. However this error goes off when I change the `torchtext` version to `0.6.0`

Is this version ok?

ERROR: HTTP error 403 while getting https://download.pytorch.org/whl/torchtext-0.5.0-py3-none-any.whl (from https://download.pytorch.org/whl/torch_stable.html)
ERROR: Could not install requirement torchtext==0.5.0 from https://download.pytorch.org/whl/torchtext-0.5.0-py3-none-any.whl because of HTTP error 403 Client Error: Forbidden for url: https://download.pytorch.org/whl/torchtext-0.5.0-py3-none-any.whl for URL https://download.pytorch.org/whl/torchtext-0.5.0-py3-none-any.whl (from https://download.pytorch.org/whl/torch_stable.html)
