### ISSUE TITLE
Using only dynamic vocabulary ( no fixed vocab) for LoRRA or M4C models

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/mmf#302]
## ❓ Questions and Help
Hi
If I  dont want to use a fixed vocabulary for output classes but only an output space defined by ocr tokens in the image,  what changes i need to make for the lorra and m4c models.

For example, I see that in case of m4c model vocabulary is specified [here](https://github.com/facebookresearch/mmf/blob/project/m4c/configs/vqa/m4c_textvqa/m4c.yml) . Will removing this vocab flle or replacing with an empty vocab file with only the special tokens work?

Would excluding the fixed vocabulary have any other effect on the model?
@ronghanghu 

thank you

**Comment by ronghanghu** [comment]
Yes, replacing `m4c_vocabs/textvqa/fixed_answer_vocab_textvqa_5k.txt` in https://github.com/facebookresearch/mmf/blob/project/m4c/configs/vqa/m4c_textvqa/m4c.yml#L28 with an empty vocabulary file (that only contains the following 4 lines) will make M4C only use the OCR output space.

To create an empty vocabulary file for M4C, put the following 4 lines into a plain text file:
```
<pad>
<s>
</s>
<unk>
```

**Comment by mineshmathew** [comment]
thank you
