### ISSUE TITLE
On config file for m4c

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/mmf#312]
## ❓ Questions and Help
@ronghanghu 
In the [config file for m4c ](https://github.com/facebookresearch/mmf/blob/project/m4c/configs/vqa/m4c_textvqa/m4c.yml) what  does the `dataset_attributes.processors.copy_processor.params.max_length `parameter represent?

Its value is 100. From the paper I understand that max number of decoding steps is 12 , which is specified in the config file as `max_copy_steps`. In that case what is this value of 100?

**Comment by ronghanghu** [comment]
The configuration for maximum decoding step is `max_copy_steps ` (https://github.com/facebookresearch/mmf/blob/project/m4c/configs/vqa/m4c_textvqa/m4c.yml#L36).

`dataset_attributes.processors.copy_processor.params.max_length` is used to decide the maximum length of object bounding box tensors copied from the imdbs. It should be set to the same value (100) as `features_max_len` here (https://github.com/facebookresearch/mmf/blob/project/m4c/pythia/common/defaults/configs/datasets/vqa/m4c_textvqa.yml).

**Comment by mineshmathew** [comment]
Hi,

I have been trying to change the config options for m4c . In my case I want to use upto 150 ocr tokens. I have extracted features for objects as well as frnc features of ocr bounding boxes. 
I keep getting dimension issues although I change original value of 50 to 150 in the config file

**Comment by mineshmathew** [comment]
Hi,
I was trying not change the number of objects considered  (currently 100) to say 10. For this
I changed `features_max_len` [here](https://github.com/facebookresearch/mmf/blob/project/m4c/pythia/common/defaults/configs/datasets/vqa/m4c_stvqa.yml) to 10 and `dataset_attributes.processors.copy_processor.params.max_length` [here](https://github.com/facebookresearch/mmf/blob/project/m4c/configs/vqa/m4c_textvqa/m4c.yml) to 10 as well. But I get an error when trying to train with this modification. The error says:

`  File "/pythia_m4c/lib/python3.5/site-packages/torch-1.5.0-py3.5-linux-x86_64.egg/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/pythia_m4c/mmf/pythia/models/m4c.py", line 176, in forward
    self._forward_ocr_encoding(sample_list, fwd_results)
  File "pythia_m4c/mmf/pythia/models/m4c.py", line 241, in _forward_ocr_encoding
    dim=-1
RuntimeError: Sizes of tensors must match except in dimension 1. Got 50 and  10
`

@ronghanghu  Can you please tell me if I need to do something more to train the m4c model with features of just 10 objects instead of 100

**Comment by mineshmathew** [comment]
@ronghanghu 
I was trying to change the number of objects whose features are considered for the m4c model for textvqa dataset. In the original model it is 100. If I want to change it to say 10, what all parameters I need to change.

I changed the `dataset_attributes.processors.copy_processor.params.max_length` in[ m4c.yml](https://github.com/facebookresearch/mmf/blob/project/m4c/configs/vqa/m4c_textvqa/m4c.yml ) and `features_max_len` in [m4c_textvqa]( https://github.com/facebookresearch/mmf/blob/project/m4c/pythia/common/defaults/configs/datasets/vqa/m4c_textvqa.yml)  to 10.

But I get the following error while training after making the above two changes.

`Traceback (most recent call last):
  File "tools/run.py", line 88, in <module>
    run()
  File "tools/run.py", line 75, in run
    trainer.train()
  File "pythia_m4c/mmf/pythia/trainers/base_trainer.py", line 236, in train
    report = self._forward_pass(batch)
  File "pythia_m4c/mmf/pythia/trainers/base_trainer.py", line 258, in _forward_pass
    model_output = self.model(prepared_batch)
  File "pythia_m4c/mmf/pythia/models/base_model.py", line 120, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "pythia_m4c/lib/python3.5/site-packages/torch-1.5.0-py3.5-linux-x86_64.egg/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "pythia_m4c/mmf/pythia/models/m4c.py", line 176, in forward
    self._forward_ocr_encoding(sample_list, fwd_results)
  File "pythia_m4c/mmf/pythia/models/m4c.py", line 241, in _forward_ocr_encoding
    dim=-1
RuntimeError: Sizes of tensors must match except in dimension 1. Got 50 and 10
`
