### ISSUE TITLE
Get bounding box information within Lorra model

### ISSUE THREAD

**Issue by Ra0k** [facebookresearch/mmf#328]
## ❓ Questions and Help

I am wondering if it is possible to get the bounding box information within the Lorra model (mmf/models/lorra.py) for both the image regions and the words. I would like to use the positions to develop a new model. If it is not possible, how should I proceed? Should I override the _process_feature_embedding_ method? Sorry, it is not crystal clear for me, how could I get the bounding box information exactly. 

Best regards,
David

**Comment by apsdehal** [comment]
You can enable `return_features_info: true` to get bounding box features. Similarly check other options here: https://github.com/facebookresearch/mmf/blob/master/projects/m4c/configs/textvqa/defaults.yaml#L60

You can check which keys you have in the sample list using `sample_list.keys()` method.

**Comment by Ra0k** [comment]
So far so good. I got access to "ocr_bbox_coordinates" once I got the dataloader fixed. I will make a pull request for that. On the other hand, the bounding box information for the image feats are still missing.

**Comment by apsdehal** [comment]
Did you enable `return_features_info` to True, if you did and you should get it in the key "image_info_0".

**Comment by Ra0k** [comment]
I used `sample_list.image_info_0.keys()` to print the keys and it gave me only the max features:
odict_keys(['max_features']). 

This is my config I added to the default one:
```
dataset_config:
  textvqa:
    use_ocr: true
    use_order_vectors: true
    return_features_info: true
    use_ocr_info: true
```

**Comment by Ra0k** [comment]
@apsdehal, is it possible that the _use_order_vectors_ is overwritten somewhere on my end?

**Comment by apsdehal** [comment]
Apologies for late reply @Ra0k. Let me have a look at my end and see what is the issue.

**Comment by apsdehal** [comment]
I tested this and it seems like the lmdb doesn't have the information you need. I probably need to update the lmdb, looking into that now.

**Comment by Ra0k** [comment]
@apsdehal thank you very much!

**Comment by apsdehal** [comment]
@Ra0k Apologies for a late resolution on this one as it required extensive testing on our end as well as retraining of M4C model's best version. The PR #375 is now up and should be ready for your use.

**Comment by Ra0k** [comment]
@apsdehal thank you very much for your help! 
However, in my end, I still can't access anything else but "max_features" within "image_info_0".
(I deleted the cache)

**Comment by apsdehal** [comment]
Reinvestigating. I will reach back soon.

**Comment by ronghanghu** [comment]
Hi, @Ra0k  it's because these keys (bounding boxes) were currently removed from the TextVQA dataset loader in https://github.com/facebookresearch/mmf/blob/master/mmf/datasets/builders/textvqa/dataset.py#L107-L116 to save GPU memory and speed up batch loading.

You can remove these lines (https://github.com/facebookresearch/mmf/blob/master/mmf/datasets/builders/textvqa/dataset.py#L109-L112) so that the boxes will be kept.

**Comment by apsdehal** [comment]
@ronghanghu  Thanks. Based on the passed config, we should probably keep them. I will open up a PR for that.

**Comment by Ra0k** [comment]
@apsdehal thank you, it really helped a lot! Now, I have the bounding boxes for both the OCR tags and the image regions. :)
Just one more extra question: is it normal that the coordinates of some bboxes are larger than the actual picture?

**Comment by ronghanghu** [comment]
@Ra0k Yes, sometimes the boxes can be larger than the image, as they are predicted by the bounding box regression step in the Faster R-CNN detector.

**Comment by Ra0k** [comment]
@apsdehal and @ronghanghu Thank you very much for your help! You are the best! It seems I will be able to finish my project in time! :)
