### ISSUE TITLE
Writer not registered when calling build_dataset

### ISSUE THREAD

**Issue by mckinziebrandon** [facebookresearch/mmf#338]
## 🐛 Bug

I was following the tutorial for the hateful memes challenge ([link](https://medium.com/pytorch/bootstrapping-a-multimodal-project-using-mmf-a-pytorch-powered-multimodal-framework-464f75164af7)). I made a slight modification so I could try downloading TextVQA. I ran the following:

```python
from mmf.utils.build import build_dataset
dataset = build_dataset("textvqa")
```

This eventually tries calling `self.writer.write` inside processors.py (line 401). The issue is that `registry.get('writer')` returned `None` when instantiating `self.writer`. This can be fixed by ensuring `register.register('writer', ...)` gets set before instantiation of the processor, of course. Should be a simple fix.

**Comment by vedanuj** [comment]
Thanks for reporting this bug. We are looking into it.
