### ISSUE TITLE
Running Inference without EvalAIAnswerProcessor

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/mmf#347]
## ❓ Questions and Help
Hi 

I am doing inference on the M4C model as given below 
`python tools/run.py --tasks vqa --datasets m4c_textvqa --model m4c \
--config configs/vqa/m4c_textvqa/m4c.yml \
--save_dir save/m4c \
--run_type inference --evalai_inference 1 \
--resume_file data/models/m4c_textvqa_m4c.ckpt`
I assume this will also post process answers to suit eval ai submission as given in the [EvalAIAnswerProcessor](https://github.com/facebookresearch/mmf/blob/c67c759a88fb9634132cc508922377e971e78de0/mmf/datasets/processors/processors.py#L895)

Is there any way i can get question wise predictions without doing any such post processing. 
Or  can I just comment out a few lines code somwhere to just use this existing inference script but without getting the answers post-processed using the EvalAIAnswerProcessor class

@ronghanghu

**Comment by ronghanghu** [comment]
Hi, actually the answers written to the prediction file does not go through this EvalAIAnswerProcessor (but the EvalAI server will post-process the answers in the prediction file on the server end before computing accuracy). This processor is only used when locally evaluating the TextVQA accuracy on the validation set.

If you would like to disable it, you can comment out these lines: https://github.com/facebookresearch/mmf/blob/c67c759a88fb9634132cc508922377e971e78de0/mmf/utils/m4c_evaluators.py#L212-L215
