### ISSUE TITLE
A question about log path on Windows

### ISSUE THREAD

**Issue by JayZhu0104** [facebookresearch/mmf#348]
## ❓ Questions and Help
When I use the command "mmf_run config=projects/m4c/configs/textvqa/defaults.yaml datasets=textvqa model=m4c run_type=train_val", the log file reported an error.

The details of error as follow:
`(pythia) F:\Projects\mmf>mmf_run config=projects/m4c/configs/textvqa/defaults.yaml datasets=textvqa model=m4c run_type=train_val
Namespace(config_override=None, local_rank=None, opts=['config=projects/m4c/configs/textvqa/defaults.yaml', 'datasets=textvqa', 'model=m4c', 'run_type=tra
in_val'])
Overriding option config to projects/m4c/configs/textvqa/defaults.yaml
Overriding option datasets to textvqa
Overriding option model to m4c
Overriding option run_type to train_val
Using seed 14855581
Logging to: ./save\logs\train_2020-06-21T20:30:14.log
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pythia\Scripts\mmf_run-script.py", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "f:\projects\mmf\mmf_cli\run.py", line 111, in run
    main(configuration, predict=predict)
  File "f:\projects\mmf\mmf_cli\run.py", line 38, in main
    registry.register("writer", Logger(config, name="mmf.train"))
  File "f:\projects\mmf\mmf\utils\logger.py", line 73, in __init__
    channel = logging.FileHandler(filename=self.log_filename, mode="a")
  File "c:\programdata\anaconda3\envs\pythia\lib\logging\__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "c:\programdata\anaconda3\envs\pythia\lib\logging\__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 22] Invalid argument: 'F:\\Projects\\mmf\\save\\logs\\train_2020-06-21T20:30:14.log'ows:`

The path of log is any wrong? But my other code did not report an error, and it works:
`f = open(r'F:\Projects\pythia\save\m4c\text.txt', 'a')`
Thanks~

**Comment by vedanuj** [comment]
@JayZhu0104 Thanks for the issue. We will look into this. We do not have extensive support for windows. So please expect a delay in resolution of this issue.

**Comment by JayZhu0104** [comment]
> @JayZhu0104 Thanks for the issue. We will look into this. We do not have extensive support for windows. So please expect a delay in resolution of this issue.

Thank you for your reply! 
I have solved this problem, and just `train_2020-06-21T20:30:14.log` changed to `train_2020_06_21T20:30:14.log`. It works!
