### ISSUE TITLE
[Hateful_Memes]Unexpected Results while training Visualbert

### ISSUE THREAD

**Issue by jishnuvk** [facebookresearch/mmf#350]
## ❓ Questions and Help
We tried to train visual_bert on the hateful memes dataset using the cli command:

> mmf_run config=projects/hateful_memes/configs/visual_bert/from_coco.yaml model=visual_bert dataset=hateful_memes

The only change made was in the config file to reduce batch size due to GPU limitations.

We ran the predict command:

> mmf_predict config=projects/hateful_memes/configs/visual_bert/defaults.yaml model=visual_bert dataset=hateful_memes run_type=test checkpoint.resume_file=./mmf/save/current.ckpt

The result was that every sample was labeled 0

first few lines of the prediction output: 

> id,proba,label
> 16395,0.3520083725452423,0
> 37405,0.35202673077583313,0
> 94180,0.35202813148498535,0
> 54321,0.35201042890548706,0
> 97015,0.35202696919441223,0
> 73506,0.3520272970199585,0
> 5429,0.35202693939208984,0
> 70691,0.35199105739593506,0

All entries were like this.

While looking through the training log files, I found that the evaluation after 1000/22000 iterations had an accuracy above 50%

> 2020-06-20T16:36:49 | INFO | mmf.train : progress: 1000/22000, val/total_loss: 0.6817, val/hateful_memes/cross_entropy: 0.6817, **val/hateful_memes/accuracy: 0.5720**, val/hateful_memes/binary_f1: 0.4191, val/hateful_memes/roc_auc: 0.6220, num_updates: 1000, epoch: 1, iterations: 1000, max_updates: 22000, val_time: 13s 294ms, best_update: 1000, best_iteration: 1000, best_val/hateful_memes/roc_auc: 0.622043

But all subsequent evaluations had an accuracy of exactly 50%(I assume because it is predicting all entries as 0)

> mmf.train : progress: 2000/22000, val/total_loss: 0.9269, val/hateful_memes/cross_entropy: 0.9269, **val/hateful_memes/accuracy: 0.5000,** val/hateful_memes/binary_f1: 0.0000, val/hateful_memes/roc_auc: 0.5190, num_updates: 2000, epoch: 1, iterations: 2000, max_updates: 22000, val_time: 13s 201ms, best_update: 1000, best_iteration: 1000, best_val/hateful_memes/roc_auc: 0.622043

Another piece of information(possibly unrelated):
After the training process was complete, we also got the following exception

> -- Process 1 terminated with the following error:
> Traceback (most recent call last):
>   File "/home/hdd1/fhmc/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", mon/report.py", line 83, in accumulate_tensor_fields
>     raise AttributeError(key)
> AttributeError: targets

The corresponding log file entry was:

> UserWarning: Sample list has not field 'targets', are you sure that your ImDB has labels? you may have wanted to run with evaluation.predict=true

Is there anything we overlooked while training that caused this problem?
Thanks in advanced.

**Comment by vedanuj** [comment]
After your training is over you should use either the `best.ckpt` or `visual_bert_final.pth` files for validation or prediction. Can you test with those and let us know how much you are getting?

**Comment by jishnuvk** [comment]
@vedanuj Thanks for the response.

Here is the validation on best.ckpt

> progress: 1000/22000, val/total_loss: 0.6817, val/hateful_memes/cross_entropy: 0.6817, val/hateful_memes/accuracy: 0.5720, val/hateful_memes/binary_f1: 0.4191, val/hateful_memes/roc_auc: 0.6220

Another thing I tried was load the best.ckpt and train for 100 iterations. The result :

> mmf.train : progress: 101/100, val/total_loss: 0.7840, val/hateful_memes/cross_entropy: 0.7840, val/hateful_memes/accuracy: 0.5000, val/hateful_memes/binary_f1: 0.0000, val/hateful_memes/roc_auc: 0.6064, num_updates: 101, epoch: 2, iterations: 101, max_updates: 100, val_time: 29s 577ms, best_update: 101, best_iteration: 101, best_val/hateful_memes/roc_auc: 0.606423

**Comment by ambuje** [comment]
Hi ,
I am trying to implement this and I am not able to change the batch size. Once I open the from_coco.yaml it has just a path written over there. Can you tell me how did you change the batch size?

**Comment by vedanuj** [comment]
What is the batch size you are using? If you are changing the batch size it might also require lowering the learning rate and increasing the number of iterations.

**Comment by jishnuvk** [comment]
Reducing the learning rate worked. Thanks and sorry for the stupid question.
