### ISSUE TITLE
UnboundLocalError: local variable 'should_log' referenced before assignment

### ISSUE THREAD

**Issue by webYFDT** [facebookresearch/mmf#378]
command: mmf_run config=projects/hateful_memes/configs/mmbt/defaults.yaml     model=mmbt     dataset=hateful_memes     run_type=train_val
When I run the above command, there is a bug
<img width="1255" alt="截屏2020-07-01 下午7 00 34" src="https://user-images.githubusercontent.com/17585343/86236743-27e17c00-bbcd-11ea-85da-d5184b39a6f4.png">

**Comment by apsdehal** [comment]
It seems like training is still crashing due tb_writer in training_loop. It should be accessed via logistics callback.
