### ISSUE TITLE
[feature] Add DocVQA to MMF

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/mmf#392]
## 🚀 Feature

A new dataset related to TextVQA and STVQA has been released by STVQA team: DocVQA. https://arxiv.org/abs/2007.00398. Since, MMF is a central hub for these kind of datasets and the related models, we should DocVQA as well.

## Pitch
Follow the implementation of TextVQA, STVQA and OCRVQA to create DocVQA interface.

**Comment by apsdehal** [comment]
@mineshmathew would you like to work on this?

**Comment by mineshmathew** [comment]
@apsdehal  yes.  give me a weeks time.  I have imdb files and the features extracted with me .
With data in the same format as the one for STVQA i could use m4c branch  of pythia with minimal changes.

If mmf is not quite different from pythias notion of tasks and datasets  it must be easy
I shall check the changes in mmf and let you know

**Comment by apsdehal** [comment]
@mineshmathew Thanks a lot. You can check the TextVQA dataset and corresponding STVQA inheritance in the master branch to see how it all fits.

**Comment by shikharmn** [comment]
@apsdehal I would like to work on this. Is there anything apart from this thread that I should know?

**Comment by apsdehal** [comment]
@shikharmn Thanks for your interest. Not specifically, let me know when you have a PR open and I can review it.

**Comment by Priyanshiguptaaa** [comment]
Hi @apsdehal, I would also like to work on this if the whole feature is not made yet. I would be open to collaborating on this if that's okay?
