### ISSUE TITLE
about textVQA visualization

### ISSUE THREAD

**Issue by shine-lcy** [facebookresearch/mmf#395]
## ❓ Questions and Help
The latest version of textVQA dataset does not appear to provide the original image. I want to analyze the performance of the algorithm by observing the pair of original image and the predicted answer. How can I get the original image? Maybe download the old version textVQA dataset? Thanks.

**Comment by apsdehal** [comment]
@shine-lcy The images for textvqa are available at https://textvqa.org/download. And you can map to images using image_id field in annotations. Let me know if this was not what you were looking for.

**Comment by shine-lcy** [comment]
I confirmed that maping to images using image_id is correct. Thanks a lot.

**Comment by apsdehal** [comment]
Np. Closing as resolved.

**Comment by HenryJunW** [comment]
Hello, I would like to visualize the input image and the prediction answer as well on the textvqa dataset. I am wondering whether there is any existing jupyter notebook similar with that of hm dataset https://colab.research.google.com/github/facebookresearch/mmf/blob/notebooks/notebooks/mmf_hm_example.ipynb or code snippet. Thanks in advance.
