### ISSUE TITLE
What does the input shape of  Movie+MCAN look like?

### ISSUE THREAD

**Issue by luogen1996** [facebookresearch/mmf#399]
## ❓ Questions and Help
Hi, that's a great work! I want to know is the grid feature padding to 32x32 in the Movie+MCAN? As described in《In Defense of Grid Features for Visual Question Answering》, i guess the grid feature is flattened and padded to a length of 608 in MCAN.  So, when both Movie and MCAN are built, what does the input shape look like? And I have not found any operations like 2d padding in the vqa2 datasets, which puzzled me so much. I'm appreciative if you could give some details for it. @vedanuj

**Comment by kienduynguyen** [comment]
Hi @luogen1996 ,

In the VQA challenge, we use 2D tensor as input (so the shape is 32x32). The 2D tensor will be fed into the MoVie part and the flatten 1D tensor with length of 1024 will be fed into the MCAN part.

**Comment by luogen1996** [comment]
> Hi @luogen1996 ,
> 
> In the VQA challenge, we use 2D tensor as input (so the shape is 32x32). The 2D tensor will be fed into the MoVie part and the flatten 1D tensor with length of 1024 will be fed into the MCAN part.

Thank you much !
