### ISSUE TITLE
Pytorch XLA/TPU Support

### ISSUE THREAD

**Issue by Namoush** [facebookresearch/mmf#402]
## ❓ Questions and Help
I would like to ask if you have planned to add support for this accelerated training scheme.
I have been poking around with it in a Colab but, after changing quite a lot in several functions (mainly on run.py and base_trainer.py) I am not able to surpass an apparently .backward hang and I think I am going to default to GPUs for now.
Cheers and thanks for the great framework!

**Comment by apsdehal** [comment]
Hi @Namoush,
Thanks for your interest in MMF.
TPU/XLA support is not yet on our roadmap, but if you would like to work on it, we can help you. Looking forward to your contributions.
