### ISSUE TITLE
How to use Visual Bert for Multi Label Classification

### ISSUE THREAD

**Issue by ravising-h** [facebookresearch/mmf#404]
## ❓ Questions and Help
I want to classify memes( I have Images of memes and through Google OCR I have extracted what is written in them) into multiple classes like offensive, mean, abusive .. they can have more than one label at a time. Can some one guide me  through mmf configs and repo, how to run this dataset and will this repo be helpful?

**Comment by apsdehal** [comment]
Hi @ravising-h,

Please have a look at how we run VisualBERT on MMIMDb using logit_bce as a loss: https://github.com/facebookresearch/mmf/blob/master/projects/visual_bert/configs/mmimdb/defaults.yaml. MMIMDb also have multiple labels and we multilabel metrics to measure performance. 

To run your custom dataset, just convert it to MMF format of MMIMDb and it should work.

**Comment by ravising-h** [comment]
Thank You for your Help. I will close the issue once the training starts.

**Comment by vedanuj** [comment]
@ravising-h Can we close this issue?

**Comment by ravising-h** [comment]
I am really sorry, I forgot to reply. Thank you for your Help.

**Comment by mohamadhabash** [comment]
Hi @ravising-h,
I have a similar multi-label task of yours and I'm trying to use VisualBERT, can you tell me how you used it?
Thanks.

**Comment by sdevatha96** [comment]
Hi, Can someone redirect me to a link where visualBERT is explained?
