### ISSUE TITLE
Running mmf source code instead of installing it got 2 point lower performance on textvqa with m4c. Why?

### ISSUE THREAD

**Issue by QingqingWang-1** [facebookresearch/mmf#414]
## ❓ Questions and Help
I have run mmf/mmf_cli/run.py directly with the setting run(opts=["config=projects/m4c/configs/textvqa/defaults.yaml", "datasets=textvqa", "model=m4c", "run_type=train_val"]). The only change is the paths in mmf/mmf/configs/defaults, which are changed to:
 cache_dir: ${env:MMF_CACHE_DIR, ./cache}
 data_dir: ${env:MMF_DATA_DIR, ../../data}

With installation, the performance is about 39.25, but without installation, it is only 37.4. 
Struggling to figure it out. Any one any suggestion?

**Comment by apsdehal** [comment]
Hi,
Thanks for using MMF. I think you figured it out but for future reference to achieve best score you need with use `joint_with_stqva.yaml` file which will train on both STVQA and TextVQA to achieve best score.

**Comment by QingqingWang-1** [comment]
Hi apsdehal,
Many thanks. I have figured it out. It is cased by the downloaded wiki.en.bin file, which is incomplete because I interupted the program when the downloading of the bin file was ongoing. Then, the program and myself do not download the bin file again since it's already there, though its size is much  smaller than the correct one.
