### ISSUE TITLE
TypeError: NoneType' object is not callable when running Movie+MCAN

### ISSUE THREAD

**Issue by CCYChongyanChen** [facebookresearch/mmf#425]
## ❓ Questions and Help
Hi, I got an error when I run `mmf_run config=projects/movie_mcan/configs/vizwiz/defaults.yaml \
    model=movie_mcan \
    dataset=vizwiz \
    run_type=train`

Traceback (most recent call last):
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/torch/multiprocessing/spawn.py"                                 , line 20, in _wrap
    fn(i, *args)
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/mmf_cli/run.py", line 54, in di                                 stributed_main
    main(configuration, init_distributed=Tr                                 ue, predict=predict)
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/mmf_cli/run.py", line 40, in ma                                 in
    trainer.load()
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/mmf/trainers/base_trainer.py",                                  line 60, in load
    self.load_model_and_optimizer()
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/mmf/trainers/base_trainer.py",                                  line 112, in load_model_and_optimizer
    self.model = build_model(attributes)
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/mmf/utils/build.py", line 62, i                                 n build_model
    model = model_class(config)
TypeError: 'NoneType' object is not callabl                                 e

I am at the "master" branch, should I check out to other branches? like this issue: https://github.com/facebookresearch/mmf/issues/236, Thank you.

**Comment by apsdehal** [comment]
@CCYChongyanChen  What was the exact command you ran, so we can replicate?

**Comment by apsdehal** [comment]
@CCYChongyanChen  How did you install the package? pip version is outdated. Can you install from source?

**Comment by CCYChongyanChen** [comment]
@apsdehal  Thank you for replying. I installed it from the source. To make sure I have the latest version, I just git pull it this morning but I still have this error.

**Comment by apsdehal** [comment]
Let us have a look. We will get back to you.

**Comment by CCYChongyanChen** [comment]
Sounds good. Thank you!

**Comment by vedanuj** [comment]
HI @CCYChongyanChen Can you paste your `projects/movie_mcan/configs/vizwiz/defaults.yaml` here ?

**Comment by CCYChongyanChen** [comment]
@vedanuj Sure.
model_config:
  movie_mcan:
    losses:
    - type: triple_logit_bce

dataset_config:
  vizwiz:
    depth_first: true
    use_features: true
    zoo_requirements:
      - vizwiz.defaults
      - vizwiz.grid_features
    features:
      train:
      - /data/vqa/feats/VizWiz/grid_feat/features/VizWiz_train
      val:
      - /data/vqa/feats/VizWiz/grid_feat/features/VizWiz_val
      test:
      - /data/vqa/feats/VizWiz/grid_feat/features/VizWiz_test
    annotations:
      train:
      - vizwiz/v2019/annotations/imdb_vizwiz_train.npy
      val:
      - vizwiz/v2019/annotations/imdb_vizwiz_val.npy
      test:
      - vizwiz/v2019/annotations/imdb_vizwiz_test.npy

optimizer:
  type: adam_w
  params:
    lr: 5e-05
    weight_decay: 0
    eps: 1e-09
    betas:
    - 0.9
    - 0.98

scheduler:
  type: multi_step
  params:
    use_warmup: true
    lr_steps:
    - 180000
    - 216000
    lr_ratio: 0.2
    warmup_iterations: 54000
    warmup_factor: 0.25

evaluation:
  metrics:
  - vqa_accuracy

training:
  lr_scheduler: true
  clip_norm_mode: all
  clip_gradients: false
  max_grad_l2_norm: 5
  max_updates: 236000
  batch_size: 64
  task_size_proportional_sampling: true
  encoder_lr_multiply: 1
  early_stop:
    criteria: vqa2/vqa_accuracy
    minimize: false
  find_unused_parameters: true

**Comment by vedanuj** [comment]
Hi @CCYChongyanChen .. for grid feature annotations you can use the script detailed here https://github.com/facebookresearch/grid-feats-vqa#feature-extraction and use one of the pretrained models. For vizwiz dataset you might need to hack the script to loop over the images or you can also dump the image info into COCO json format and run using the script.

**Comment by CCYChongyanChen** [comment]
> Hi @CCYChongyanChen .. for grid feature annotations you can use the script detailed here https://github.com/facebookresearch/grid-feats-vqa#feature-extraction and use one of the pretrained models. For vizwiz dataset you might need to hack the script to loop over the images or you can also dump the image info into COCO json format and run using the script.
> 
> Grid features are required because we do not have an end to end pipeline to use the VG attribute pretrained Detectron2 models in MMF just yet. But we will be adding that feature sometime soon.

Hi @vedanuj , Thank you for your reply. I have extracted grid features. But it is still not clear to me what is grid feature's **"annotations**".

**Comment by CCYChongyanChen** [comment]
Could anyone give me some hints? This issue is still not solved yet.

**Comment by vedanuj** [comment]
The annotations are the files where questions, answers, image_id etc are stored. You can check the annotations files for vqa2, which will be downloaded in your `~/.cache/torch/mmf/data/datasets/vqa2/grid_features/annotations` directory. 

Can you try this and see if removing the `\`s  have any affect : 

```
mmf_run config=projects/movie_mcan/configs/vizwiz/defaults.yaml  model=movie_mcan  dataset=vizwiz  run_type=train
```

**Comment by CCYChongyanChen** [comment]
That doesn't have an affect. I tried the default region features `
      - vizwiz/v2019/features/detectron.lmdb`, it gives me the same error.

**Comment by vedanuj** [comment]
I ran the exact same command and it works for me : 

```
mmf_run config=projects/movie_mcan/configs/vizwiz/defaults.yaml model=movie_mcan dataset=vizwiz run_type=train
```

Does it run for you with vqa2 config? Or do you see the same error?

**Comment by vedanuj** [comment]
@CCYChongyanChen Were you able to fix the issue?

**Comment by CCYChongyanChen** [comment]
> @CCYChongyanChen Were you able to fix the issue?

Thank you for following up! Not yet...
Could you please offer the direct download link for vqav2 & VG annotations (imdb_train2014)? It is not downloaded automatically. I have got the grid feature annotations for vqav2. Thank you！

**Comment by CCYChongyanChen** [comment]
In the log it says:

2020-08-02T14:28:48 | INFO | mmf.train : Loading datasets
2020-08-02T14:28:59 | INFO | mmf.train : No model registered for name: movie_mcan

**Comment by CCYChongyanChen** [comment]
I checked the "models" folder and found the movie_mcan.py was missed (other models were there). Re clone the repo and get this error fixed.
Btw, the latest version will download the Vqa2 features automatically even though in the config I indicate to use "vizwiz" dataset...and the VizWiz features/annotations are not downloaded automatically...
