### ISSUE TITLE
Cannot load the latest checkpoint_VisualBERT

### ISSUE THREAD

**Issue by CCYChongyanChen** [facebookresearch/mmf#429]
## ❓ Questions and Help
Hi, I trained VisualBERT for 6 h, stopped it, and would like to resume the model. I found the checkpoint is saved in the mmf/save/models and the latest model is "model_21000.ckpt". However, when I try running the following command, it still be trained from the very beginning, i.e., producing model_1000.ckpt. Could you help me with that? Thank you a lot!
`mmf_run config=projects/visual_bert/configs/vizwiz/defaults.yaml     model=visual_bert     dataset=vizwiz     run_type=train    checkpoint.resume=Ture checkpoint.resume_best=True`

**Comment by apsdehal** [comment]
You have typo in `checkpoint.resume=Ture`, it needs to be `checkpoint.resume=True`.

**Comment by CCYChongyanChen** [comment]
Thank you for replying so quickly! @apsdehal, Do I still need `checkpoint.resutme=True`?

**Comment by CCYChongyanChen** [comment]
Seems both `checkpoint.resume=True` and `checkpoint.resume_best=True' are not needed if `checkpoint.resume_file=<file_path>` is used. I can now load the latest checkpoint. Thank you a lot!

**Comment by runzeer** [comment]
@CCYChongyanChen Have you experimented the VisualBert on the VizWiz datasets? How about the results? Better than pythia?
