### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by caprone** [facebookresearch/mmf#430]
HI
trying to install from pip or source:

ERROR: Could not find a version that satisfies the requirement torchvision==0.6.0 (from mmf) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.3.0, 0.4.1, 0.5.0)
ERROR: No matching distribution found for torchvision==0.6.0 (from mmf)

on pytorch 1.5.1

thanks

**Comment by apsdehal** [comment]
Can you provide output of `python -m torch.utils.collect_env`?

**Comment by caprone** [comment]
of course:

PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce RTX 2070 SUPER
Nvidia driver version: 445.87
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1
[pip3] torchvision==0.6.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      216
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.1.0            py37h45dec08_0
[conda] mkl_random                1.1.1            py37h47e9c7a_0
[conda] pytorch                   1.5.1           py3.7_cuda102_cudnn7_0    pytorch
[conda] torchvision               0.6.1                py37_cu102    pytorch

**Comment by apsdehal** [comment]
For now please run:

`pip install torchvision===0.6.0 -f https://download.pytorch.org/whl/torch_stable.html` before pip installing mmf.

I would also recommending building from source in case you want latest features.

FYI, in case you want to know what happened: Pytorch doesn't upload latest binaries for pypi directly for windows anymore so you have to provide dependency link using `-f` to direct pytorch pip cloud.

**Comment by caprone** [comment]
HI and thanks
but unfortunately the same issue occurs....:((

**Comment by apsdehal** [comment]
As in, when installing torchvision or when installing mmf?

**Comment by caprone** [comment]
when installing mmf from pip and source

**Comment by apsdehal** [comment]
Was torchvision install actually successful? Can you post `python -m torch.utils.collect_env` again?

**Comment by caprone** [comment]
yes torchvision install successful;

PyTorch version: 1.5.1+cu92
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce RTX 2070 SUPER
Nvidia driver version: 445.87
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.5.1+cu92
[pip3] torchvision==0.6.0
[conda] torch                     1.5.1+cu92               pypi_0    pypi
[conda] torchvision               0.6.0                    pypi_0    pypi

**Comment by apsdehal** [comment]
Last question: can you print the error of final `pip install mmf`?

**Comment by caprone** [comment]
ERROR: Could not find a version that satisfies the requirement torch==1.5.0 (from mmf) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.5.0 (from mmf)

thanks

**Comment by apsdehal** [comment]
Yeah, so do this `pip install torch==1.5.0 -f https://download.pytorch.org/whl/torch_stable.html` and install mmf again.

**Comment by caprone** [comment]
HI and thanks..
we made progress, but anothers errors occurs;
from the first one:

ERROR: Failed building wheel for mmf
  Building wheel for fasttext (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\softwareRaza\Anaconda\envs\multi_mod_mmf\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\TEMP\\pip-install-tyblcqdc\\fasttext\\setup.py'"'"'; __file__='"'"'D:\\TEMP\\pip-install-tyblcqdc\\fasttext\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'D:\TEMP\pip-wheel-3tre7f0v'
       cwd: D:\TEMP\pip-install-tyblcqdc\fasttext\
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\fasttext
  copying python\fasttext_module\fasttext\FastText.py -> build\lib.win-amd64-3.7\fasttext
  copying python\fasttext_module\fasttext\__init__.py -> build\lib.win-amd64-3.7\fasttext
  creating build\lib.win-amd64-3.7\fasttext\util
  copying python\fasttext_module\fasttext\util\util.py -> build\lib.win-amd64-3.7\fasttext\util
  copying python\fasttext_module\fasttext\util\__init__.py -> build\lib.win-amd64-3.7\fasttext\util
  creating build\lib.win-amd64-3.7\fasttext\tests
  copying python\fasttext_module\fasttext\tests\test_configurations.py -> build\lib.win-amd64-3.7\fasttext\tests
  copying python\fasttext_module\fasttext\tests\test_script.py -> build\lib.win-amd64-3.7\fasttext\tests
  copying python\fasttext_module\fasttext\tests\__init__.py -> build\lib.win-amd64-3.7\fasttext\tests
  running build_ext
  building 'fasttext_pybind' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for fasttext
  Running setup.py clean for fasttext
  Building wheel for demjson (setup.py) ... done
  Created wheel for demjson: filename=demjson-2.2.4-py3-none-any.whl size=73548 sha256=11a2064b8c71882a429fdf853dba489833718708654d01a5976ba944d2af3361
  Stored in directory: c:\users\raza\appdata\local\pip\cache\wheels\41\94\3d\466801f4a8db8e6fce765d7a0115dfebcc55ddf6b00cd98f59
  Building wheel for sklearn (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1320 sha256=dd981d84c74d6a93cb1afe3ce4554e472a7b2c7db603aa588a46f9b25a23a6a2
  Stored in directory: c:\users\raza\appdata\local\pip\cache\wheels\46\ef\c3\157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built demjson sklearn
Failed to build mmf fasttext
ERROR: Could not build wheels for mmf which use PEP 517 and cannot be installed directly


#but I  have already installed  --  visual C++  2015-2019   ...???

**Comment by apsdehal** [comment]
Hi,
Please see these references to properly install vs c++:

- https://github.com/benfred/implicit/issues/76
- https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required

**Comment by caprone** [comment]
HI
I have installed properly Visual C++ (works correctly for others frameworks..), however I upgraded to last version available
but problem remains the same...; 
probably Mmf has some problems with some Win configurations...

however thanks for your Help! very appreciated ;)

**Comment by apsdehal** [comment]
I don't think MMF has issues with Windows, because we do have windows build test setup on MMF and they do build successfully.

Maybe you can try installing fasttext from scratch? And what command are you running for installing MMF.

**Comment by caprone** [comment]
"Maybe you can try installing fasttext from scratch?"
yes, I'm trying to do that...but having serious problems...grr

**Comment by apsdehal** [comment]
Sorry about this experience. Let me look up if there is some guidance in fasttext repo on this.

**Comment by caprone** [comment]
but do not worry! THANKS FOR YOUR GREAT SUPPORT!! ;))
yes I'll do!
thanks again

**Comment by caprone** [comment]
HI
ok, fasttext successfully installed from scratch, but the last error left is:


"""
Building wheel for mmf (PEP 517) ... error
.........
ERROR: Could not build wheels for mmf which use PEP 517 and cannot be installed directly...
"""

**Comment by apsdehal** [comment]
This is a known issue with pip's new versions for which indented solution for now is to downgrade pip:
```
python -m pip install --force-reinstall pip==18.1
```

Let me know if this works.

**Comment by caprone** [comment]
Hi and thanks for your help;
but there is always a problem with Win;

vs C++ issue continues to happen despite vs c++ is perfectly installated and works for all frameworks...
(probably issue with virtualenv??)...mah...

error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
  Can't roll back mmf; was not uninstalled
Command "D:\softwareRaza\Anaconda\envs\mmf\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Raza\\mmf\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in C:\Users\Raza\mmf\
You are using pip version 18.1, however version 20.2b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

however no problem, I give up installing it, but I'll use some of your great code for some of my tasks;
thanks anyway!

**Comment by apsdehal** [comment]
Yes, why not use docker or ubuntu in windows 10 to install this?

**Comment by caprone** [comment]
I will consider your suggestions, ;) thanks again

**Comment by amaterasu59** [comment]
same issue with the installation: 
**ERROR: Could not find a version that satisfies the requirement torch==1.5.0 (from mmf) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.5.0 (from mmf)**

upon running the `python -m torch.utils.collect_env` command on command prompt:

C:\Users\user>python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Microsoft Windows 10 Home Single Language
GCC version: (MinGW.org GCC-8.2.0-3) 8.2.0
CMake version: Could not collect

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce 940MX
Nvidia driver version: 442.23
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] Could not collect

Same result when I install mmf from source.
What to do?

**Comment by apsdehal** [comment]
For windows, you will need to separately install these two version by specifying dependency links:
```
pip install torch===1.5.0 torchvision===0.6.0 -f https://download.pytorch.org/whl/torch_stable.html
```
