### ISSUE TITLE
Overriding annotations

### ISSUE THREAD

**Issue by gantoniou92** [facebookresearch/mmf#431]
Hi MMF team,

I have a question regarding overriding annotations using dot list. It is suggested (https://mmf.sh/docs/notes/configuration#command-line-dot-list-override) that one can override annotations e.g. 

`dataset_config.hateful_memes.annotations.train[0]=x`. 

Doing something similar 

`dataset_config.hateful_memes.annotations.train[0]=hateful_memes/defaults/annotations/new_train.jsonl`, 

it doesn't seem that any overriding is happening, rather the original annotation file train.jsonl is loading. However, if I use 

`dataset_config.hateful_memes.annotations.train=hateful_memes/defaults/annotations/new_train.jsonl`

I get the message:

> Overriding option dataset_config.hateful_memes.annotations.train to hateful_memes/defaults/annotations/new_train.jsonl

thus probably loading the new annotation file. In addition, in this case the produced config file the corresponding part looks:

annotations:
      train: hateful_memes/defaults/annotations/new_train.jsonl
      val:
      - hateful_memes/defaults/annotations/dev.jsonl
      test:
      - hateful_memes/defaults/annotations/test.jsonl

Q: Is this expected behaviour or am I missing something in my understanding of this functionality in mmf?

Thanks in advance for your help.

**Comment by apsdehal** [comment]
Fixed by #438 in master. Closing.
