### ISSUE TITLE
Can not match VISUAL BERT baseline for hateful memes

### ISSUE THREAD

**Issue by crazysal** [facebookresearch/mmf#435]
## ❓ Questions and Help

Ran the checkpoint for inference using the command : 

`CUDA_VISIBLE_DEVICES=0 mmf_predict config=./mmf/projects/hateful_memes/configs/visual_bert/from_coco.yaml dataset=hateful_memes run_type=test checkpoint.resume_zoo=visual_bert.finetuned.hateful_memes.from_coco model=visual_bert`

Attached train log. and output csv 

The submission AUC on he challenge site gives this an score(AU ROC) of 0.3482 
which is not even near to the unimodal 50% mark, any idea where I am going wrong ? 
 
[train.log](https://github.com/facebookresearch/mmf/files/4988763/train.log)
[hateful_memes_run_test_2020-07-27T18:24:15.csv](https://docs.google.com/spreadsheets/d/1G-bBOIDW0y8b7Vc8Bl5OWM-vjNMqodvMEz71QWOskJg/edit?usp=sharing)

**Comment by AkaneNyan** [comment]
you loaded the coco checkpoint by using from_coco.yaml (resume_zoo)
try using the default config file

**Comment by vedanuj** [comment]
Try this : 

```
CUDA_VISIBLE_DEVICES=0 mmf_predict config=./mmf/projects/hateful_memes/configs/visual_bert/defaults.yaml dataset=hateful_memes run_type=test checkpoint.resume_zoo=visual_bert.finetuned.hateful_memes.from_coco model=visual_bert
```

**Comment by crazysal** [comment]
why not the one pretrained on coco ?

**Comment by vedanuj** [comment]
The configs we provide are for training. You can use the config `from_coco.yaml` when you run evaluation/test but you will need to add `checkpoint.resume_pretrained=False` to your ccommand. This is because when `checkpoint.resume_pretrained=True` is set, only the base of the model is loaded from the pretrained weights and not the classification head weights.

**Comment by apsdehal** [comment]
Closing this for now as it has been documented at multiple places. We probably will open up a master task later to clear up this confusion properly or fix the way this works. Please open up a new issue if you face any more problems.

**Comment by Abhiruchi** [comment]
Running this command now generates 2000 rows. Is this expected? I hit the below error when I try to submit the baseline results. 

<img width="746" alt="Screenshot 2020-11-28 at 11 51 37" src="https://user-images.githubusercontent.com/7767267/100495299-329a4000-3170-11eb-971a-48352ea6f76c.png">

**Comment by Abhiruchi** [comment]
Opened a new issue here - https://github.com/facebookresearch/mmf/issues/702 for this concern.
