### ISSUE TITLE
Support epoch based training

### ISSUE THREAD

**Issue by vedanuj** [facebookresearch/mmf#440]
## 🚀 Feature
Add ability to run epoch based training to MMF

## Motivation

Currently MMF supports iteration(updates) based training and all related intervals(like checkpoints, logging etc) are based on iterations. It will be useful to add epoch(one complete set of iteration over the dataset) based training support to MMF. 

## Pitch

Should be able to specify `training.max_epochs` in config for epoch based training. Simple way to implement this will be convert epochs to iterations/updates. MMF already has parameters `training.max_epochs` and `training.max_updates`. Currently in the training loop, `max_epochs` is not used. For more details how the flow works please check https://github.com/facebookresearch/mmf/blob/cb2adc68acf155be2d8e14e5c447aa6f4e954917/mmf/trainers/core/training_loop.py#L26

Checkpoints and logging intervals can still follow iterations. So the change required will be converting epochs to iterations. 

Note: If you are a bootcamper and looking to work on this, please assign this to yourself on tasks app: T70933226

**Comment by ytsheng** [comment]
`iterations` and `updates` are the same thing. In my PR, I will keep the naming "updates", since it is used in more places. But please let me know if you all prefer iterations. :)

**Comment by ytsheng** [comment]
Issue implemented in PR attached. Please make sure you specify at least one of the values: max_updates or max_epochs.
