### ISSUE TITLE
Pretrained model for VisualBERT?

### ISSUE THREAD

**Issue by CCYChongyanChen** [facebookresearch/mmf#443]
## ❓ Questions and Help
Hi, could you share the pre-trained model for VisualBERT? (either pretrained on coco or pretrained on vqav2 is fine)
Thank you a lot!

**Comment by apsdehal** [comment]
Hi @CCYChongyanChen ,
If you set `checkpoint.resume_zoo=visual_bert.pretrained.coco` in your command, it should automatically download it for you.

**Comment by CCYChongyanChen** [comment]
@apsdehal Cool! Thanks a lot!
