### ISSUE TITLE
How to generate the annotation file for customized dataset (ocr_tokens & question_tokens)   Movie_MCAN

### ISSUE THREAD

**Issue by CCYChongyanChen** [facebookresearch/mmf#444]
## ❓ Questions and Help
Hi,
The vizwiz annotation file you provide is 2018 version, and I would like to generate annotation for 2020 VizWiz dataset. How could I generate the ocr_tokens and the question_tokens? Could you share the code about generating the annotation file? Thank you!

**Comment by apsdehal** [comment]
`question_tokens` are generated by using tokenize function `mmf.utils.text.tokenize` on the question. You don't need ocr tokens for MoVie-MCAN model.

**Comment by CCYChongyanChen** [comment]
Thanks! Is the ocr_token used for textVQA task? I may run that later so I still would like to know how can I generate ocr_token via MMF.
Thank you in advance!

**Comment by apsdehal** [comment]
Yes, that's right. We use internal model Rosetta for generating those OCR tokens which is not available publicly. We recommend using Google Cloud Vision OCR service to extract OCR tokens for your own use case.

**Comment by CCYChongyanChen** [comment]
Cool, thank you.
