### ISSUE TITLE
[feature] Install glove only when the processor is actually used

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/mmf#446]
## 🚀 Feature
Install Glove embedding only when the processor is actually called with some input.

## Motivation

Currently, most of the dataset default on GloVe embeddings as the text processor. Most of our current models override GloVe embedding processor with BERT text encoders. But, the GloVe embeddings are still initialized in case when build_dataset is called. Thus, instead of initializing them in the init function of GloVe processor

## Pitch

- Move the glove initialization to inside the `__call__`
- Only initialize in the master node, and wait until it downloads
- Keep track of whether downloaded or not in a variable.
- See implementation of how fasttext embedding bin is download at runtime.
- Make sure vocab size and other variables are still set.

Note: if you are a bootcamper working on this task, please assign the internal task to yourself: T71089006

**Comment by vedanuj** [comment]
#469 fixes this.
