### ISSUE TITLE
Multimodal Alignment loss for Vilbert/VisualBERT

### ISSUE THREAD

**Issue by vedanuj** [facebookresearch/mmf#466]
## 🚀 Feature
Multimodal Alignment or Sentence Image Prediction loss for ViLBERT/VisualBERT

## Motivation

[VilBERT](https://arxiv.org/abs/1908.02265) model uses two pretraining losses. Current MMF implementation uses `masked multimodal modeling` loss but not the `multimodal alignment` loss. Similarly [VisualBERT](https://arxiv.org/abs/1908.03557) model also uses a similar loss which they call  `sentence-image prediction` loss. Task is to add this multimodal alignment loss to Vilbert and VisualBERT models.

## Pitch

To be able to reproduce Vilbert/VisualBERT model results `multimodal alignment` loss should be added. Also in order to extend to retrieval downstream tasks, this `multimodal alignment` loss will be important.

## Additional context

The task will involve adding this loss to the models, modify any dataset side changes and test the implementation is working as expected.

**Comment by Priyanshiguptaaa** [comment]
Hi @ytsheng, I would like to give this a try. Is there any other information or resources about this feature apart from this thread that I should know about?

**Comment by Priyanshiguptaaa** [comment]
Hi @vedanuj @ytsheng, I would like to give this a try if the feature is still required to be worked on. If yes, is there any other information or resources apart from this thread that I need to know about? 

Thanks!

**Comment by pragyasrivastava0805** [comment]
Hi @apsdehal I think I can do this. I will have to contribute this as a part of an initial screening for a research intern position. Hope you understand

**Comment by Farhan-jafri** [comment]
Hi, I want to work on this issue, this is my first contribution, could you please guide me
