### ISSUE TITLE
Temperature scaled sampling for multi dataset

### ISSUE THREAD

**Issue by vedanuj** [facebookresearch/mmf#467]
## 🚀 Feature
Temperature scaled sampling for multi dataset

## Motivation

In multitask training involving multiple datasets, it is often desirable to be able to control the sampling ratios for different datasets. Currently mmf provides either `equal` or size `proportional` sampling. In order to have more control over the sampling we should add temperature scaled sampling.

## Pitch

Currently [multi_dataset_loader.py](https://github.com/facebookresearch/mmf/blob/080a3308e669f4153ac346c513feb51b86228396/mmf/datasets/multi_dataset_loader.py#L159) implements two sampling strategies for multiple dataset trianing. One is `equal` and the other is `proportional`. In order to have more control over the sampling ratios for multiple datasets, we can add a temperature(`T`) scaling capability when deciding the proportions of different datasets to be used. On one extreme, when `T=1` it will be same as the current 'proportion' sampling. As `T` increases the sampling tends to become more and more `equal`. Reference: [Google T5](https://arxiv.org/abs/1910.10683)

## Additional context

Temperature scaled sampling is often required during multi task training. For reference Google's T5 [paper](https://arxiv.org/abs/1910.10683). The task will involve adding a temperature parameter that can be configured for sampling datasets during multi dataset training.

**Comment by Suhruth9** [comment]
@vedanuj any updates on this? I'd like to implement this if no one is already on it.

**Comment by Suhruth9** [comment]
@vedanuj any update on this? I'd like to work on this if no one is already on it

**Comment by parthduggal** [comment]
Hi, @vedanuj @apsdehal  any update on this? I'd like to work on this and this could be my first issue

**Comment by apsdehal** [comment]
@parthduggal Thanks for your interest. This can be added as a form of iteration strategy. Take a look at https://github.com/facebookresearch/mmf/blob/master/mmf/datasets/iteration_strategies.py

**Comment by parthduggal** [comment]
@apsdehal , if I'm not wrong, I have to add temperature scaled sampling to the current iteration strategies in the format of the other iteration strategies that you showed in the link?

**Comment by joshibhaumik** [comment]
Can I work on this issue?

**Comment by shinobi-AI** [comment]
May i work on this..

**Comment by vedanuj** [comment]
@shinobi-AI  Since, @parthduggal is already working on this can you check any other issue?

**Comment by vaish-muk** [comment]
take
