### ISSUE TITLE
Not enough documentation

### ISSUE THREAD

**Issue by aryamansriram** [facebookresearch/mmf#476]
## ❓ Questions and Help
The documentation does not include a tutorial on how to implement a model from the model zoo for our tasks. Please include one so that it becomes a little easier to use mmf

**Comment by vedanuj** [comment]
We will update the documentation. For now here is a colab notebook that adds a new dataset and uses a model with it : 

https://colab.research.google.com/github/facebookresearch/mmf/blob/notebooks/notebooks/kdd_tutorial.ipynb

Let us know if that works for your use case.

**Comment by aryamansriram** [comment]
Thanks, works for me
