### ISSUE TITLE
AssertionError: Checksum of downloaded file does not match the expected checksum. Please try again.

### ISSUE THREAD

**Issue by aryamansriram** [facebookresearch/mmf#478]
## 🐛 Bug

Getting checksum error while trying to run baseline for hateful memes dataset

## Command
!mmf_convert_hm --zip_file=gdrive/My\ Drive/Lnmwdnq3YcF7F3YsJncp.zip --password=KexZs4tn8hujn1nK

## To Reproduce
Refer to the steps <a href="https://github.com/facebookresearch/mmf/tree/master/projects/hateful_memes#prerequisites">here</a>

P.S Encountered the error while running on colab, is the error because of that?

**Comment by vedanuj** [comment]
Can you try adding `--bypass_checksum` and rerun?

**Comment by aryamansriram** [comment]
Yep, this solved it
