### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by bl1211** [facebookresearch/mmf#480]
## ❓ Questions and Help
Hi
I have a problem in running mmf_convert and mmf_run
When I unzip dataset by mmf_convert_hm, output is saved to home/ directory
and then when i run training, its output such as checkpoints are saved to home/cache/ directory.
this cause memory problem.
is there any way to change the output directory ?

thanks

**Comment by vedanuj** [comment]
During training, you can save output to a different directory by specifying `env.save_dir=<path_to_your_new_directory>`. SImilarly if your data directory you want is different from the default directory then you can override it by specifying `env.data_dir=<path_to_your_new_directory>`
