### ISSUE TITLE
Whats the difference between coco.defaults and coco.resnet152?

### ISSUE THREAD

**Issue by daniel3303** [facebookresearch/mmf#481]
## ❓ Questions and Help

Hello,

I was wondering, what is the difference between coco.defaults and coco.resnet152?
I initially assumed that coco.defaults included the top 100 features per image extracted by Faster RCNN making them a tensor of (N, 100, 2048). I also assumed that coco.resnet152 represented the features extracted from the images using resnet152 making them a tensor of (N, 4096). After some debugging I found out that both coco.defaults and coco.resnet152 are represented by (N, 100, 2048) tensors. So how are really the coco.resnet152 features extracted?

Thanks.

**Comment by vedanuj** [comment]
Yes they are resnet152 features.

**Comment by daniel3303** [comment]
Well my question was not very explicit. What I don't understand is how resnet152 extracts (100, 2048) features per image. I expected to get 4096 features from resnet.

**Comment by apsdehal** [comment]
ResNet feature extraction code is available in this script: https://github.com/facebookresearch/mmf/blob/master/tools/scripts/features/extract_resnet152_feat.py

**Comment by MonsKim999** [comment]
@apsdehal 

  with open("./list") as f:
        lines = f.readlines()
        for line in lines:
            exclude[line.strip("\n").split(os.path.sep)[-1].split(".")[0]] = 1

this is a part of extract_resnet152_feat.py.
what is the ./list?
I can't find this file

**Comment by apsdehal** [comment]
Hi,
You can `touch list` in the folder where you are running this command to create an empty file. List is used to exclude some files from feature extraction if needed. This probably needs to be handled more gracefully. We will open up a task for this. For now, you can use what I suggested i.e. an empty file.

**Comment by MonsKim999** [comment]
@apsdehal

Thank you for your help.
Can this file run in alone? 

In fact, I want to reimplement the textvqa paper.
so I'd like to study the code in detail. but I can't find some parts of the project as like dataloader, preprocessing, dataset, extract feature.

Can you help me more? Thank you!

**Comment by apsdehal** [comment]
Please open up a new issue.

**Comment by MonsKim999** [comment]
@apsdehal

Yes !
