### ISSUE TITLE
build dataset for each worker for multi-machine distributed job

### ISSUE THREAD

**Issue by ariwaranosai** [facebookresearch/mmf#493]
add config to allow build dataset for each worker for multi-machine distributed job.

https://github.com/facebookresearch/mmf/blob/6b94a8be4c270ffa1edb4b1263787f38b370b74d/mmf/datasets/base_dataset_builder.py#L76-L78

now, build function only be invoked in master. This may cause issue when training job is running in multi machine.

Can we add a dataset config to allow replica build dataset themselves?

**Comment by vedanuj** [comment]
Hi .. we use distributed data parallel to do multi machine training and the data sampler takes care of distributing the batch over multiple machines. Is there a use case that you are trying to solve that requires dataset to be built separately for each worker in DDP?

**Comment by ariwaranosai** [comment]
In my case, I write my dataset and each worker needs cache data separately in their own disk in DDP model.

**Comment by vedanuj** [comment]
Ok got it. Our setup work with shared memory use cases. We can look into this. Feel free to take a stab at it and PRs are welcome.
