### ISSUE TITLE
Where is implementation code for models?

### ISSUE THREAD

**Issue by bl1211** [facebookresearch/mmf#494]
## ❓ Questions and Help
Hello
I have a question about code.
there is a funtion as build_model(config) in mmf.utils.build.
this function get config and return model. I want to know what type is model? and where is its code?

then in mmf.trainers.core.training_loop there is a function as training_loop
in this function there is this statement: self.model.train()
Where is the code of the train method?

**mmf.utils.build:**
```
def build_model(config):
    model_name = config.model

    model_class = registry.get_model_class(model_name)

    if model_class is None:
        raise RuntimeError(f"No model registered for name: {model_name}")
    model = model_class(config)

    if hasattr(model, "build"):
        model.load_requirements()
        model.build()
        model.init_losses()

    return model
```
--------------------------------------------------------------------
**mmf.trainers.core.training_loop:**
```
def training_loop(self) -> None:
        self.max_updates = self._calculate_max_updates()
        torch.autograd.set_detect_anomaly(self.training_config.detect_anomaly)

        logger.info("Starting training...")
        self.model.train()
        self.run_training_epoch()
        self.after_training_loop()

```

**Comment by vedanuj** [comment]
Hi .. `model_name = config.model` will get the model name that you define in your config. All models are registered in the `registry` and depending on what you have specified a particular model will be loaded. Each model has a `build` method which gets called in the `build_model` method. The models are available under `mmf/models/` directory. You can follow  `mmf/models/base_model.py` and any model extending from it to understand the flow.

**Comment by bl1211** [comment]
> Hi .. `model_name = config.model` will get the model name that you define in your config. All models are registered in the `registry` and depending on what you have specified a particular model will be loaded. Each model has a `build` method which gets called in the `build_model` method. The models are available under `mmf/models/` directory. You can follow `mmf/models/base_model.py` and any model extending from it to understand the flow.

thanks a lot.
Then It means each model has been implemented in `mmf/models/ directory`. right?
I found `build` method but i cant find `train` method in models implementation. Can you guide me for found its code? where is `train` method?

**Comment by bl1211** [comment]
> `model.train()` is something PyTorch provides and is in every Pytorch `nn.Module`. Are you looking for code for training? That is in `mmf/trainers/core/training_loop.py`.
> 
> See the following reference: https://stackoverflow.com/questions/51433378/what-does-model-train-do-in-pytorch

thanks a lot
