### ISSUE TITLE
can't find any .pt or .pth file to convert into tensorflow

### ISSUE THREAD

**Issue by amaterasu59** [facebookresearch/mmf#496]
## ❓ Questions and Help
you said that your model is powered by pytorch but I could not find any pytorch file. I wished to convert this model into tensorflow using ONNX. Any idea as to how I can do that?
P.S.: I am still a beginner in deep learning so please pardon me if this query is too beginner level. Thank you!

**Comment by vedanuj** [comment]
Hi @amaterasu59 .. which model and trained on which dataset specifically you want to convert to tf?

**Comment by amaterasu59** [comment]
the deep learning model behind this website: https://vqa.cloudcv.org/. I guess this is their github repository: https://github.com/Cloud-CV/VQA. They have utilized the MMF framework. I wished to deploy the similar model but for an android app. Any guidelines as to how to do that? Thank you!
