### ISSUE TITLE
MMF training not saving model

### ISSUE THREAD

**Issue by gireek** [facebookresearch/mmf#501]
Problem edited below

**Comment by vedanuj** [comment]
Hi .. this model is not trained using mmf. So we won't be able to help with this. You can train or use models trained with MMF by following the [tutorial](https://mmf.sh/docs/challenges/hateful_memes_challenge) or [readme](https://github.com/facebookresearch/mmf/tree/master/projects/hateful_memes).

**Comment by gireek** [comment]
@vedanuj  What should I do if I have to load a dataset exactly like hateful memes and run training on it on MMF?

**Comment by vedanuj** [comment]
Follow the prerequisites here : https://github.com/facebookresearch/mmf/tree/master/projects/hateful_memes#prerequisites

**Comment by gireek** [comment]
Do I have to zip it in the format of MMF and run mmf_convert_hm ? and then run the following command with dataset as hateful_memes to train?

`mmf_run config=<REPLACE_WITH_BASELINE_CONFIG> model=<REPLACE_WITH_MODEL_KEY> dataset=hateful_memes
`

**Comment by gireek** [comment]
I tried the following from https://github.com/apsdehal/hm_example_mmf:
`MMF_USER_DIR="." mmf_run config="configs/experiments/defaults.yaml"  model=concat_vl dataset=hateful_memes training.num_workers=0 
`

also:
`mmf_run config="configs/experiments/defaults.yaml"  model=concat_vl dataset=hateful_memes training.num_workers=0  run_type=train_val`
because your docs here: https://mmf.sh/docs/challenges/hateful_memes_challenge
listed run_type=train_val option for training but **training does Not happen**.
The logs in the save folder end up like this : 

`2020-08-20T17:24:02 | INFO | mmf.train : Total Parameters: 59437822. Trained Parameters: 59437822
2020-08-20T17:24:02 | INFO | mmf.train : Starting training...
2020-08-20T17:24:02 | INFO | mmf.train : Loading fasttext model now from /root/.cache/torch/mmf/wiki.en.bin
2020-08-20T17:28:04 | INFO | mmf.train : Finished loading fasttext model
`
and the models folder in the save folder is always empty.

**Comment by gireek** [comment]
@vedanuj 
The kind of rows in train.jsonl in hateful memes dataset are like :
`{"id":13894,"img":"img\/13894.png","label":0,"text":"putting bows on your pet"}
`

but in my data they are like:
`{"id": 724, "img": "./img/724.jpg", "label": 2, "text": "KALE GREEN TEA "}
`

the difference being in the key "img" in the 2 rows. Can that be a problem because of paths?


Even the folder structure i have is same as the hateful memes dataset being:
./data
       |------- img
       |------- train.jsonl
       |------- test.jsonl
       |------- dev.jsonl

Then, I zipped the data folder with a password becuase it seems MMF commands need a password secured zip file dataset by:

`!zip -r --password pass123 ./training.zip ./data/`

and then opened it as an MMF dataset:

`!mmf_convert_hm --zip_file=./training.zip --password=pass123 --bypass_checksum=1`

**Comment by vedanuj** [comment]
Can you show the `configs/experiments/defaults.yaml` that you are using?

**Comment by gireek** [comment]
IT is this one:
https://github.com/apsdehal/hm_example_mmf/blob/master/configs/experiments/defaults.yaml

**Comment by gireek** [comment]
This is what comes on the terminal:
```
2020-08-20 19:18:34.411776: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Namespace(config_override=None, local_rank=None, opts=['config=configs/experiments/defaults.yaml', 'model=concat_vl', 'dataset=hateful_memes', 'training.num_workers=0', 'run_type=train_val'])
/usr/local/lib/python3.6/dist-packages/mmf/utils/configuration.py:528: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.
  + "Switching to CPU version."
Importing user_dir from /content/hm_example_mmf
Overriding option config to configs/experiments/defaults.yaml
Overriding option model to concat_vl
Overriding option datasets to hateful_memes
Overriding option training.num_workers to 0
Overriding option run_type to train_val
Using seed 36408782
Logging to: ./save/logs/train_2020-08-20T19:18:36.log
Downloading extras.tar.gz: 100% 211k/211k [00:00<00:00, 279kB/s]  
169876453it [05:55, 478358.09it/s]
Downloading: "https://download.pytorch.org/models/resnet152-b121ed2d.pth" to /root/.cache/torch/checkpoints/resnet152-b121ed2d.pth
100% 230M/230M [00:03<00:00, 60.8MB/s]

tcmalloc: large alloc 5423251456 bytes == 0x47eb8000 @  0x7f587bdd2887 0x7f57db499593 0x7f57db490897 0x7f57db4913b1 0x7f57db44e883 0x7f57db471b00 0x566ddc 0x50a783 0x50c1f4 0x507f24 0x509202 0x594b01 0x54a17f 0x5517c1 0x5a9eec 0x50a783 0x50cfd6 0x509918 0x50a64d 0x50c1f4 0x509918 0x50a64d 0x50c1f4 0x509015 0x594b01 0x54ac61 0x59fe1e 0x50d596 0x507f24 0x509202 0x594b01
tcmalloc: large alloc 3023249408 bytes == 0x18babc000 @  0x7f587bdd2887 0x7f57db499593 0x7f57db4908db 0x7f57db4913b1 0x7f57db44e883 0x7f57db471b00 0x566ddc 0x50a783 0x50c1f4 0x507f24 0x509202 0x594b01 0x54a17f 0x5517c1 0x5a9eec 0x50a783 0x50cfd6 0x509918 0x50a64d 0x50c1f4 0x509918 0x50a64d 0x50c1f4 0x509015 0x594b01 0x54ac61 0x59fe1e 0x50d596 0x507f24 0x509202 0x594b01
^C
```

Suprisingly the '^C' comes automatically in the last line. I amdoing this on Colab using GPU. The other issue is even on using GPU it gives this:

`/usr/local/lib/python3.6/dist-packages/mmf/utils/configuration.py:528: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.
`
