### ISSUE TITLE
Train captioning model using Grid features

### ISSUE THREAD

**Issue by mokadyr** [facebookresearch/mmf#503]
## ❓ Questions and Help

Hi,
I wish to train captioning model using grid features
(similar to [In Defense of Grid Features for Visual Question Answering](https://arxiv.org/abs/2001.03615) )
Is it possible changing only configuration file?( I didn't a relevant configuration file)

**Comment by vedanuj** [comment]
The grid features for COCO are available. You don't need to create them. Those will be same as used by the [movie+mcan](https://mmf.sh/docs/projects/movie_mcan) model.
