### ISSUE TITLE
VilBERT output_attentions

### ISSUE THREAD

**Issue by lilyli2004** [facebookresearch/mmf#507]
## ❓ Questions and Help

I'm trying to visualize attention over an image as described in #145, but to do that I need the attention weights. I see that in the VilBERT model_config there's a key for output_attentions, but setting it to true doesn't change anything so it seems that it's not actually being used.

**Comment by vedanuj** [comment]
Can you set this to true and try ? https://github.com/facebookresearch/mmf/blob/ab8d3f5ea2e88e8f4c22c8f3ec1e0b5798c99995/mmf/models/vilbert.py#L849

We should add this to config later

**Comment by lilyli2004** [comment]
Thanks for responding. I tried setting it to true, it still doesn't return attention weights. 

If I change every line in that file with output_all_attention_masks=False to True it returnes an array of Nones:

`{'attention_weights': ([None, None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None], [None, None, None, None, None, None]), 'scores': tensor([[-4.6950,  5.2790],
        [-2.7249,  3.4144],
        [ 4.2371, -5.3074],
        [-5.0205,  5.3667],
        [-4.0550,  4.2542],
        [-1.2446,  3.0586],
        [ 4.8686, -5.1795],
        [-4.2003,  4.5071],
        [ 5.0359, -5.0130],
        [-4.3184,  4.4732],
        [-3.8754,  4.2878],
        [-4.9110,  4.8071],
        [-4.4969,  5.0775],
        [ 4.4756, -4.9688],
        [-3.8757,  5.4387],
        [-4.4190,  4.1395],
        [ 4.6009, -5.7298],
        [ 4.9328, -5.2371],
        [-4.3172,  4.5485],
        [ 4.3968, -4.1901],
        [ 5.0198, -5.4975],
        [ 5.1284, -5.0690],
        [ 4.6897, -5.2649],
        [-1.5844,  2.2520],
        [-3.3575,  3.0376],
        [-3.6803,  3.9656],
        [ 4.4489, -4.4763],
        [ 3.9956, -4.9506],
        [-3.3798,  4.0102],
        [ 2.5870, -3.2591],
        [ 4.5612, -6.0324],
        [ 4.4529, -4.2601]], device='cuda:0', grad_fn=<ViewBackward>)}`

**Comment by CCYChongyanChen** [comment]
I got 3 empty lists of attention weights for vilbert by change every line in that file with output_all_attention_masks=False to True. Not sure what went wrong. @vedanuj

**Comment by CCYChongyanChen** [comment]
> Thanks for responding. I tried setting it to true, it still doesn't return attention weights.
> 
> If I change every line in that file with output_all_attention_masks=False to True it returnes an array of Nones:
> 
> `{'attention_weights': ([None, None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None], [None, None, None, None, None, None]), 'scores': tensor([[-4.6950, 5.2790], [-2.7249, 3.4144], [ 4.2371, -5.3074], [-5.0205, 5.3667], [-4.0550, 4.2542], [-1.2446, 3.0586], [ 4.8686, -5.1795], [-4.2003, 4.5071], [ 5.0359, -5.0130], [-4.3184, 4.4732], [-3.8754, 4.2878], [-4.9110, 4.8071], [-4.4969, 5.0775], [ 4.4756, -4.9688], [-3.8757, 5.4387], [-4.4190, 4.1395], [ 4.6009, -5.7298], [ 4.9328, -5.2371], [-4.3172, 4.5485], [ 4.3968, -4.1901], [ 5.0198, -5.4975], [ 5.1284, -5.0690], [ 4.6897, -5.2649], [-1.5844, 2.2520], [-3.3575, 3.0376], [-3.6803, 3.9656], [ 4.4489, -4.4763], [ 3.9956, -4.9506], [-3.3798, 4.0102], [ 2.5870, -3.2591], [ 4.5612, -6.0324], [ 4.4529, -4.2601]], device='cuda:0', grad_fn=<ViewBackward>)}`

Did you address it? Thanks!
