### ISSUE TITLE
Issue in training a model using Hateful Memes Data set 

### ISSUE THREAD

**Issue by AjinkyaP1998** [facebookresearch/mmf#509]
## ❓ Questions and Help
For the Hateful Memes challenge, after downloading the data and converting it to the MMF format. I executed the following code for training a model:

`!mmf_run config=projects/hateful_memes/configs/mmbt/defaults.yaml \ model=mmbt \ dataset=hateful_memes \ training.log_interval=50 \ training.max_updates=3000 \ training.batch_size=16 \ training.evaluation_interval=500`

And in between the execution of the code, some space opened up for the user's input. What is this input for? What am I suppose to put in it to train the model?

**Comment by gireek** [comment]
I am not really sure but my issue got solved when I reduced training batch size. Do try that.

**Comment by vedanuj** [comment]
Can you provide a more detailed stack trace? Also please attach environment details for bug reports.

**Comment by apsdehal** [comment]
Closing this as there hasn't been a response and I believe recommendation to decrease batch size solves this. If the issue persists, please open up a new one with details.
