### ISSUE TITLE
problem in lxmert get_image_and_text_features fn

### ISSUE THREAD

**Issue by ariwaranosai** [facebookresearch/mmf#520]
in get_image_and_text_features, position of box will be norm by following code 

https://github.com/facebookresearch/mmf/blob/3f313b6878d3d0cb55882415445ba31ef8bfa291/mmf/models/lxmert.py#L677-L687

in line 680, if image_h and image_w is provided, image_location will be init with zero? is there should be copy of bbox?

**Comment by vedanuj** [comment]
Yes it seems like a bug. We will fix it. Thanks for reporting.
