### ISSUE TITLE
Example notebook for running pretrained libraries from the mmf package

### ISSUE THREAD

**Issue by aryamansriram** [facebookresearch/mmf#525]
## ❓ Questions and Help
Hi,
I checked out the tutorial which mentioned running model baselines from the command line. Is there an example notebook which mentions how to use them in code in case you wanted to improve the model?

**Comment by apsdehal** [comment]
We don't have something specific as you asked for the tutorial. Do you have a model or a dataset in mind? Some context would help us to understand your use case better.
