### ISSUE TITLE
Modify `mmf_convert_hm` to copy dir rather than move it

### ISSUE THREAD

**Issue by steph-en-m** [facebookresearch/mmf#528]
Currently running `mmf_convert_hm` moves the entire zipfile to a new location of the mmf dataset.
This isn't an ideal behavior for google-colab users where session storage doesn't persist.

Modifying the `mmf_convert_hm` method to instead create a copy of the dir to the new dir of the mmf converted dataset would be more ideal and allow for quick experimentation with mmf.

**Comment by apsdehal** [comment]
Hi, that sounds good. Can you open up a PR to implement this?

**Comment by steph-en-m** [comment]
Sure I'll implement and open a PR.
