### ISSUE TITLE
Pretraining Visual Bert on masked VQAv2

### ISSUE THREAD

**Issue by violetteshev** [facebookresearch/mmf#533]
## ❓ Questions and Help
Hi, I'm trying to pretrain Visual Bert on masked VQAv2:
`mmf_run config=projects/pretrain_vl_right/configs/visual_bert/masked_vqa2/full.yaml run_type=train_val dataset=masked_vqa2 model=visual_bert`

And I get this error:
`AttributeError: 'MaskedVQA2Dataset' object has no attribute 'answer_processor'`

It happens because in MaskedVQADataset `self._add_answer` attribute is True by default:

https://github.com/facebookresearch/mmf/blob/24dedb1908333782de3a0ee54253b229c9a7218d/mmf/datasets/builders/vqa2/masked_dataset.py#L7-L17

Shouldn't it be False if answers are not used during pretraining?

**Comment by apsdehal** [comment]
Hi!

Yes, you are right. There is a PR open to fix this #529. You can patch it or wait until it lands.

Thanks for reporting the issue.

**Comment by violetteshev** [comment]
Thank you!
