### ISSUE TITLE
Pretraining VisualBERT on Hateful memes dataset

### ISSUE THREAD

**Issue by arjondas** [facebookresearch/mmf#543]
## ❓ Questions and Help
Is there any way/config I can use to task-specific pretrain the "VisualBERT pretrained on COCO" model on Hateful memes dataset? I'm assuming that MMF's model zoo does not provide the task specific pretrained model.

Pretraining to be similar to masked language modeling with the image objectives. Looking for an MMF way of doing this.

**Comment by vedanuj** [comment]
Are you trying to pretrain on the the Hateful Memes Dataset? We usually don't pretrain on such a small dataset. In case you want to, you will have to create a Masked version of the Hateful Memes Dataset. Similar to masked_coco etc. Let us know if that answers your question.
