### ISSUE TITLE
Missing data in stvqa for M4C re-implememt 

### ISSUE THREAD

**Issue by akira-l** [facebookresearch/mmf#547]
## ❓ Questions and Help
I download the file in [https://dl.fbaipublicfiles.com/pythia/m4c/data/m4c_stvqa_obj_frcn_features.tar.gz](url) . But I get an error when running m4c with configure join_with_stvqa.yaml : 
`TypeError: cannot unpack non-iterable NoneType object`  in features_database.py in line 68. 

It seems the file I downloaded missing train/aa2e11c2f95b2dec.npy 

How can I get the complete files and where is the missing file? I got  folders like coco-text, icdar, VisualGenome etc in train folder from m4c_stvqa_obj_frcn_features, but there is no *.npy files.

**Comment by apsdehal** [comment]
Hi there, 
This is one of the files required for running joint_with_stvqa.yaml. The config should automatically download all of the requirements for you including the missing ones: https://github.com/facebookresearch/mmf/blob/master/projects/m4c/configs/textvqa/joint_with_stvqa.yaml#L8. Any particular reason, you are manually downloading these?

**Comment by akira-l** [comment]
I have to download this feature manually for some reason. I download the features via the link provided by the author of this repo, but still meet this problem.
