### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/private/home/vedanuj/projects/pythia-internal/data/nlvr2/detectron_fix_100/fc6/train-9316-3-img0.npy'

### ISSUE THREAD

**Issue by Rishika-Rathore** [facebookresearch/mmf#556]
## ❓ Questions and Help
Can you please help with this error @vedanuj .....

![image](https://user-images.githubusercontent.com/34299068/92908034-7b7d0b00-f443-11ea-8c47-c1b3777ad95d.png)

**Comment by vedanuj** [comment]
We will have to upload the features and other annotation files to our servers. Expect by end of this week.

**Comment by rishika-99** [comment]
Thanks ✌🏻✌🏻

**Comment by Rishika-Rathore** [comment]
Thanks✌🏻
