### ISSUE TITLE
Pretraining LXMERT

### ISSUE THREAD

**Issue by gantoniou92** [facebookresearch/mmf#566]
Hi,

It seems the following reported issue (KeyError: 'question_tokens') on pre-training LXMERT on Visual Genome persists.

https://github.com/facebookresearch/mmf/pull/339#issuecomment-672293055

I would be grateful for your help.

George

**Comment by vedanuj** [comment]
Will look into this issue.

**Comment by gantoniou92** [comment]
Also, is there a way to import pre-trained weights from original LXMERT paper into MMF instead? Thanks
