### ISSUE TITLE
[enhancment] SampleList should check device of tensor being added

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/mmf#567]
## 🚀 Feature

SampleList in all cases, (update, setattr) should check that the tensor or object being added has same device as sample list itself.

## Motivation

This minor oversight can cause issues later down the lane as .to may not move everything to device to keep checks shallow.
The validation check should happen at the add level itself.

## Pitch

Check device of tensor field if present and ensure newly added tensor has same device.

**Comment by prachigarg23** [comment]
Hi, I would like to work on this. This will be my first attempt at contributing. This feature is still required, right? Just to clarify, this feature will have to be incorporated at all instances of sample_list across the repository right?

**Comment by apsdehal** [comment]
Hi,
Thanks for your interest. This would happen inside the samplelist class itself, in the setter functions. Let me know if you don't understand anything.

**Comment by saif-sk** [comment]
Hi, I would like to work on this. This will be my first attempt at open source contributing.

**Comment by pragyasrivastava0805** [comment]
@apsdehal can I generate a PR for this?

**Comment by pragyasrivastava0805** [comment]
@apsdehal @vedanuj could you please guide me and tell what exactly needs to be done?
