### ISSUE TITLE
CPU memory leakage

### ISSUE THREAD

**Issue by violetteshev** [facebookresearch/mmf#574]
Hi, I'm trying to pretrain Visual Bert on a cluster:
```
CUDA_VISIBLE_DEVICES=0,1,2,3 mmf_run config=projects/pretrain_vl_right/configs/visual_bert/masked_vqa2/full.yaml run_type=train_val dataset=masked_vqa2 model=visual_bert
```

But after few iterations the job is killed due to exceeded memory:
```
slurmstepd: error: Job 34477 exceeded memory limit (169384386560 > 161061273600), being killed
slurmstepd: error: Exceeded job memory limit
```

I tried to increase allocated memory (up to 250 GB), but it's exceeded anyway after more iterations. So the memory keeps growing during training. Could you give me some guidance why it might happen?

**Comment by vedanuj** [comment]
Hi .. Can you provide more details like a full stack trace?

**Comment by violetteshev** [comment]
The code is running ok, there is no errors. But the job is canceled by slurm when it exceeds memory. I set up num_workers to 0 and now RAM memory is almost constant. I guess it somewhat relevant to this [issue](https://github.com/pytorch/pytorch/issues/13246#issue-375013234) so that maybe pytorch problem, not mmf.

**Comment by yangapku** [comment]
Hi, I met the same problem. The strange thing is that the problem does not happen on a local GPU server but occurs on the cluster.

**Comment by violetteshev** [comment]
I confirm, it only happens on the cluster. So that's what I noticed. When running on 4 x Tesla V100-SXM2-32GB (cuda 9.2.148, nvidia driver 410.48) total memory consumption is about 250 GB and it keeps growing during training. When training on 4 x Tesla M40-24GB (cuda 9.2.148, nvidia driver 396.44) the total memory is just 20-30 GB, and with num_workers=0 it fluctuates but doesn't exceed 30GB.
