### ISSUE TITLE
mmf documentation 

### ISSUE THREAD

**Issue by webYFDT** [facebookresearch/mmf#577]
## ❓ Questions and Help
when I read mmf documentation  about "registry",the page can't found.

https://mmf.sh/docs/lib/common/registry
![截屏2020-09-22 下午8 41 31](https://user-images.githubusercontent.com/17585343/93883353-08617780-fd14-11ea-878a-c692ea061eb7.png)

**Comment by vedanuj** [comment]
The link should be https://mmf.sh/api/lib/common/registry.html
