### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by CCYChongyanChen** [facebookresearch/mmf#578]
## ❓ Questions and Help
When running MCAN, I run into the CUDA out of memory issue.
My server has 4 GPU with 11178MB per GPU. 
The code could run with Batchsize=16 but I think that batch size is not optimal...
Any trick for this? I think mmf have set inplace=True for all 'ReLu' also I see the use of torch.no_grad.
I don't know other simple ways to reduce memory use.

Also it says 10.21 GB already allocated. 10.27G reserved in total by PyTorch. on the server, no program is running except MCAN.

RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 2; 10.92 GiB total capacity; 10.21 GiB already allocated; 51.25 MiB free; 10.27 GiB reserved in total by PyTorch) (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:289)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7f78d8047536 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1cf1e (0x7f78d8290f1e in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x1df9e (0x7f78d8291f9e in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: THCStorage_resize + 0x96 (0x7f78d9518186 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #4: at::native::(anonymous namespace)::resize_cuda_(at::Tensor&, c10::ArrayRef<long>, c10::optional<c10::MemoryFormat>) + 0x9aa (0x7f78dad2ebfa in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x288cb93 (0x7f78dad2fb93 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0xf21d92 (0x7f78d93c4d92 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x1053996 (0x7f78d94f6996 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0xf76dc8 (0x7f78d9419dc8 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #9: <unknown function> + 0x10c3ec0 (0x7f79159f0ec0 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x2c9b6fe (0x7f79175c86fe in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x10c3ec0 (0x7f79159f0ec0 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #12: at::Tensor::mm(at::Tensor const&) const + 0xf0 (0x7f79155b4b70 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x28e6b6c (0x7f7917213b6c in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #14: torch::autograd::generated::AddmmBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x1b0 (0x7f7917214080 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x2d89c05 (0x7f79176b6c05 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7f79176b3f03 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #17: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7f79176b4ce2 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #18: torch::autograd::Engine::thread_init(int) + 0x39 (0x7f79176ad359 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #19: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7f7923dec998 in /home/cc67459/MMF2/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #20: <unknown function> + 0xbd6df (0x7f7924ebe6df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #21: <unknown function> + 0x76db (0x7f79275986db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #22: clone + 0x3f (0x7f79272c1a3f in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by apsdehal** [comment]
Hi, MoVie+MCAN model was trained on 8 GPUs IIRC, if the default batch size doesn't work for you please use gradient accumulation to fit bigger batch sizes, by setting `training.update_frequency` parrameter accordingly.
