### ISSUE TITLE
Questions about ".lmdb" features

### ISSUE THREAD

**Issue by ChenyuGAO-CS** [facebookresearch/mmf#583]
## ❓ Questions and Help
Hi, 
I want to use a new dataset to train VisualBERT. The scrept ["extract_features_vmb.py"](https://github.com/facebookresearch/mmf/blob/master/tools/scripts/features/extract_features_vmb.py) only can save features as ".npy" files, while the mmf needs ".lmdb" formate. How can I covert the ".npy" files to ".lmdb" files?

**Comment by apsdehal** [comment]
Hi,

Technically, MMF should work with .npy files as well. Let us know if you have any issue in that regard.

For the answer to your question, have a look at the script: https://github.com/facebookresearch/mmf/blob/master/tools/scripts/features/lmdb_conversion.py
