### ISSUE TITLE
VisualBERT Finetuning Error

### ISSUE THREAD

**Issue by mmiakashs** [facebookresearch/mmf#587]
## ❓ Questions and Help
In mmf I was trying to extract the VisualBERT pretrained features. I used the VisualBERT model similar to [this one](https://github.com/facebookresearch/mmf/issues/465#issuecomment-675876026). First time I train and validate that model without any error. However, the next time when I try to re-train the VisualBert model I got the following error:

> RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

**Comment by apsdehal** [comment]
Hi,
Please add `training.find_unused_parameters=True` at the end of your command. We will fix this in the config itself as this has now been reported multiple times.

**Comment by mmiakashs** [comment]
@apsdehal Thanks, it is working now :)
