### ISSUE TITLE
Adding Custom Losses

### ISSUE THREAD

**Issue by mmiakashs** [facebookresearch/mmf#589]
## ❓ Questions and Help

I added a custom loss in the losses.py of mmf and also register that loss using @registry.register_loss("custom_loss"). However, the problem is I couldn't able to use that loss without reinstalling the whole mmf library. After reinstalling the mmf from the modified repo with custom_loss in the losses.py, I can use that loss. Otherwise, it gave not found a registered loss error. Is the appropriate way to add loss in mmf or am I missing any step? Thanks.

**Comment by apsdehal** [comment]
hi, if you want to use MMF as a library then it is recommended to install from source but create your own project as user directory. See the option: https://github.com/facebookresearch/mmf/blob/master/mmf/configs/defaults.yaml#L210. An example of MMF based project which uses MMF as dependency is available at https://github.com/apsdehal/hm_example_mmf

**Comment by g-luo** [comment]
How did you resolve the registered loss error? I'm getting the same issue with an unregistered builder object. 

What command do we run to make sure that the registry is up to date, even though we have already run register_x() when creating a class?

**Comment by apsdehal** [comment]
Hi,
(i) Are you registering the new builder under same name as one of the original ones that MMF provides? 
(ii) Are you up mmf_cli.run programmatic API to run the job in colab?

**Comment by g-luo** [comment]
(i) No, I'm using a unique name
(ii) I am using mmf_cli.run in colab
![Screen Shot 2020-09-30 at 4 37 49 PM](https://user-images.githubusercontent.com/36020488/94750632-5b05e980-033b-11eb-80a7-dfe085e16100.png)
![Screen Shot 2020-09-30 at 4 38 17 PM](https://user-images.githubusercontent.com/36020488/94750635-5ccfad00-033b-11eb-8eb8-8e9fd8efa998.png)

It seems to me that the registry is up to date and has the builder in Jupyter notebook, but in the processing of running the python scripts it is no longer up to date

**Comment by apsdehal** [comment]
What error do you see btw?

**Comment by g-luo** [comment]
![Screen Shot 2020-09-30 at 4 41 38 PM](https://user-images.githubusercontent.com/36020488/94750813-d36caa80-033b-11eb-879e-c09df7e83e62.png)

**Comment by apsdehal** [comment]
Interesting, did you try the kdd tutorial colab notebook? Did it work?

**Comment by g-luo** [comment]
I did not; I have no idea if it works.

**Comment by apsdehal** [comment]
Jupyter notebook is a runtime environment, so you need to do everything programmatically to make sure registry is updated. if you run without programmatic api, it will launch using the binary execution file which would have no idea about your runtime. Let us have a look at why isn't it working for you.

**Comment by apsdehal** [comment]
Alternative way which I suggested to @mmiakashs is to create your own user_dir as in the example repo I shared above and use `MMF_USER_DIR` environment variable to specify where it is.

**Comment by g-luo** [comment]
Would another valid workaround be defining my classes (and registering) in a python file?

**Comment by apsdehal** [comment]
I ran the kdd_tutorial colab, it seems to work fine, did you run the cells in a sequence? (The cells that define the builder should be run before the mmf_cli.run cell)

**Comment by apsdehal** [comment]
> Would another valid workaround be defining my classes (and registering) in a python file?

Yes. That would work. Let us know if it doesn't. But we should try to debug why colab isn't working.

**Comment by g-luo** [comment]
Yes, I ran it sequentially; I can share the notebook I'm working on https://github.com/g-luo/foil_mmf

**Comment by apsdehal** [comment]
Can you update the notebook with your latest code? I don't see the block for running the mmf_cli.run.

**Comment by g-luo** [comment]
> Can you update the notebook with your latest code? I don't see the block for running the mmf_cli.run.

It's updated.

**Comment by apsdehal** [comment]
Cool, thanks. Give us some time to have a look at this.

**Comment by apsdehal** [comment]
Hi again,
I had a look at your jupyter notebook. I replaced your dataset in-place with a numbers dataset and it seems to be working for me. Can you make replace back your content in place into this colab notebook and try again: https://colab.research.google.com/drive/1bFO9FwrwA_5gVQZsrMhKL1CG9ute3BBw?usp=sharing

Also to download from dropbox you need to add `?dl=1` at the end of the url from dropbox.

**Comment by g-luo** [comment]
Yes, the Colab works. I think this is a multithreading issue in mmf_cli > run.py since the colab only uses one cpu, and if I comment out all multithreading in run() (while running on cluster with multiple gpus) the error no longer appears.

**Comment by apsdehal** [comment]
Yeah, if you are using it in multithreading scenario, colab is not the way to go. Since multithreading will spawn a new process, it will lose all of the variables or changes from the parent. For multithreading scenario and if you are planning to add your code to a script and run using `MMF_USER_DIR` instead. Easier way to run only on 1 GPU is to set `CUDA_VISIBLE_DEVICES=0`.

I don't recommend commenting out all of the multiprocessing code as it is what will allow you to actually use > 1 GPUs. Instead follow my recommendation of using scripts.

**Comment by g-luo** [comment]
Gotcha; thanks for all the help!

**Comment by apsdehal** [comment]
Closing this as resolved for now! If new issue happens, please feel free to open up a new issue.
