### ISSUE TITLE
Downloading MMF Dataset - Checksum doesn't match & Cuda is not present

### ISSUE THREAD

**Issue by mmervecerit** [facebookresearch/mmf#593]
## ❓ Questions and Help

Hi, I am trying to download HM dataset from drivendata, mmf_convert_hm gives 

`AssertionError: Checksum of downloaded file does not match the expected checksum. Please try again.`

It also gives a user warning:

```
 UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.
  "Device specified is 'cuda' but cuda is not present. "
```

I tested twice in different machines, 1 Tesla T4 Colab Machine, the other is a VM with CPU(Using Conda, installed MMF from the source, Python 3.7 + Pytorch 1.6)

What could the be reason for the issues above?

Thank you
M

**Comment by apsdehal** [comment]
Hi,
MMF hasn't been updated according to new files. We will update it soon.

**Comment by mmervecerit** [comment]
Thanks @apsdehal!
