### ISSUE TITLE
The movie_mcan.grid.vqa2_vg checkpoint in the model zoo cannot reproduce the reported score on VQA

### ISSUE THREAD

**Issue by yangapku** [facebookresearch/mmf#594]
## ❓ Questions and Help
Hi, I tried to use the provided movie_mcan.grid.vqa2_vg checkpoint to reproduce the reported test-dev result (73.92) following this guide [link](https://mmf.sh/docs/projects/movie_mcan/). However, when I submitted the predicted result, I got a much lower evaluation test-dev score (overall 72.58, yesno 88.73, number 54.83, other 62.8). The score on number questions are especially lower than reported. Could you help me to figure out why this happened? Is the checkpoint provided for download wrong? Thank you very much!

**Comment by yangapku** [comment]
Hi, may I ask whether there is any progress on this issue? Thank you! Besides, I notice that the config yaml for the downloaded checkpoint has some different options with the config trained by myself using the default config files (batchsize=512 max_features=100 compared with mine batchsize=64 max_features=1024). Is this model zoo checkpoint trained with different options and will that cause this issue?

**Comment by apsdehal** [comment]
@yangapku We are looking into it. Expect a reply soon by our collaborator responsible for movie+mcan soon.

**Comment by vedanuj** [comment]
@yangapku Can you try with this PR #604 and check if you can get test-dev score of 73.92 ?

**Comment by yangapku** [comment]
Ok, I will have a try. Meanwhile, may I ask whether I need to apply this PR if I want to do training as well?

**Comment by vedanuj** [comment]
Yes, apply this to training as well.

**Comment by yangapku** [comment]
Thank you the PR works! Now I get the test-dev score of 73.92. May I ask another question? If I want to train another movie+mcan model to reproduce the around 73.92 test-dev score (for model ensemble), do I need to change any default yaml configs of this project? I notice that the config yaml for the downloaded checkpoint has some different options with the default config files (batchsize=512 max_features=100 in the checkpoint compared with batchsize=64 max_features=1024 in the default configs). Will that matters?

**Comment by vedanuj** [comment]
You should use the batch size=64 and max_features=1024 as provided in the defaults.yaml config. The batch size in the checkpoint config was used for inference. max_features=100 won't work sue to some later changes.

**Comment by yangapku** [comment]
Thank you very much! May I ask how long are the training process expected to take? I just began training and found it will take around 8 days in total to train 13 epochs on my server (8GPUs with 16GB memory each, use batch-size=32 and update_frequency=2).
