### ISSUE TITLE
Warning in Loading VisualBERT pretrained weights in MMF

### ISSUE THREAD

**Issue by mmiakashs** [facebookresearch/mmf#598]
## ❓ Questions and Help

I was trying to load VisualBERT weights from the pretrained model, key: _"visual_bert.pretrained.coco"_. I am confused about whether MMF could load the weights, as I got the following warning when it tries to load the weights. Is it an expected warning message for loading VisualBERT weights using MMF?

> transformers.modeling_utils: Weights of VisualBERTBase not initialized from pretrained model: ['bert.embeddings.token_type_embeddings_visual.weight', 'bert.embeddings.position_embeddings_visual.weight', 'bert.embeddings.projection.weight', 'bert.embeddings.projection.bias']

**Comment by vedanuj** [comment]
Yeah that is an expected warning. This is the stage where during model init it tries to load the BERT model weights from transformers. You can ignore this. The checkpoint loading starts when you see this in your logs : 

`mmf.utils.checkpoint: Loading checkpoint`

**Comment by mmiakashs** [comment]
@vedanuj Thanks. I didn't see that message in the log. I was trying to load VisualBERT pretrained model weight in the following way. Is it the right way to load the VisualBERT pretrained model weights?

```
self.visual_bert = registry.get_model_class(
            "visual_bert"
        ).from_pretrained(
            "visual_bert.pretrained.coco"
        )
self.visual_bert.model.output_hidden_states = True
self.visual_bert.training_head_type = "finetuning"
```

**Comment by apsdehal** [comment]
Yeah. This should load. Log that Vedanuj is talking about appears if you load using mmf_run and checkpoint utils.

**Comment by apsdehal** [comment]
I am closing this issue as resolved. Feel free to open up a new one if our response didn't resolve your question.
