### ISSUE TITLE
Issue Fine-tuning / Training on multiple GPUs

### ISSUE THREAD

**Issue by g-luo** [facebookresearch/mmf#600]
## ❓ Questions and Help

Hello, I'm getting an issue when I'm trying to fine-tune on a system with multiple GPUs. It seems to load the custom dataset (foil) and pertained model (visual_bert.pretrained.coco) correctly, but when it starts running training I get this error:

![Screen Shot 2020-10-03 at 3 02 34 PM](https://user-images.githubusercontent.com/36020488/95002492-87af4080-0589-11eb-8783-d9f4c1046154.png)

My full code is at https://github.com/g-luo/foil_mmf, and this issue occurs when I run 
`MMF_USER_DIR="." mmf_run "config=./configs/experiment_config.yaml" 
        model=visual_bert 
        dataset=foil
        run_type=train_val`

It seems like this issue is occurring because the child processes cannot find my user_dir module (foil_mmf).

**Comment by g-luo** [comment]
Also random followup, but instead of this issue I get a "CUDA out of memory error" when training on one GPU. I tried decreasing the batch size, but for some reason the available memory would shrink as I adjusted that. Is there something else I should do to resolve this?

**Comment by g-luo** [comment]
Here's my train.log as well:
[train.log](https://github.com/facebookresearch/mmf/files/5322359/train.log)

**Comment by apsdehal** [comment]
For now, can you train with `training.num_workers=0`? We got aware of this bug recently and are looking into it. Thanks for your patience.

**Comment by g-luo** [comment]
Thanks! That resolved the issue.

**Comment by apsdehal** [comment]
I am reopening this issue until we fully fix it.
