### ISSUE TITLE
BUTD Captioning DEMO is not working

### ISSUE THREAD

**Issue by ajandrey** [facebookresearch/mmf#601]
I saw a similar question in https://github.com/facebookresearch/mmf/issues/264 and it is improperly closed.

The error reported by others remains unresolved. The request was closed stating that the mmf demo was working (https://colab.research.google.com/drive/1Z9fsh10rFtgWe4uy8nvU4mQmqdokdIRR?usp=sharing.)

However, the MMF Pythia Demo does not do image captioning. Do you have a preview of the demo that generates image captioning to work?

![Screenshot from 2020-10-03 19-46-17](https://user-images.githubusercontent.com/54222787/95003026-2602cc80-05b1-11eb-83f0-881384837ac2.png)

**Comment by apsdehal** [comment]
Hi,

We haven't fixed the captioning demo yet and this may take some time. In theory, you can take the changes applied on original Pythia demo to migrate it to MMF demo to captioning demo as well to get it working. Please expect a delay on resolution of this from our side. If you plan to fix it, feel free to open up a PR on the `notebooks` branch of MMF which hosts all example notebook code under `notebooks` folder.

**Comment by ajandrey** [comment]
> Hi,
> 
> We haven't fixed the captioning demo yet and this may take some time. In theory, you can take the changes applied on original Pythia demo to migrate it to MMF demo to captioning demo as well to get it working. Please expect a delay on resolution of this from our side. If you plan to fix it, feel free to open up a PR on the `notebooks` branch of MMF which hosts all example notebook code under `notebooks` folder.

Thanks for the feedback, it was very useful for me. I have a question: does the image captioning task return a captioning assertiveness rate? I really need to see it. I'm trying for version 0.1 (Pythia) and also for the MMF version, but still without success. For example, when using the MMF VQA demo, it reports an accurate % for each object identified.
Is there an option for image captioning? That is, can I see how accurate the description (captiooning) is? I would like to know if this is already implemented and available in the latest version. You don't have to give me details, I just want to know if I keep trying to show this result or if it doesn't actually exist.

Thank you!

**Comment by apsdehal** [comment]
Hi,
There is no concept of accuracy of description or confidence in captioning. You can take out probability of each word generated, all of which you will need to multiply to generate total probability. But this will decrease with longer sequences and doesn't make sense to calculate because the model is trained with teacher forcing and technically only cares about Markov Chain of 2nd order. So, overall it wouldn't make sense to report probability of whole sentence because of how the generation works and how it only cares about immediate next word predicted in loss optimization. Also, longer sentences will always have lower probability in this case.

**Comment by apsdehal** [comment]
Another point to be noted is that when there is a ground truth available for the caption, you can use generation metrics such as BLUE, METEOR and others to estimate how good of that generated description, but without ground truth at inference time this is not possible.

**Comment by ajandrey** [comment]
Yes, I thought that would be the answer, but I wanted confirmation from you.
Thank you very much. It helped me a lot, thanks!

Should I close this issue or leave it open because of the demo captioning?

**Comment by apsdehal** [comment]
No problem. Let's keep it open so that it is tracked.
