### ISSUE TITLE
Add yaml configuration support for collection type parameters

### ISSUE THREAD

**Issue by vvmar** [facebookresearch/mmf#610]
## 🚀 Feature

Add yaml configuration support for collection type parameters.
## Motivation

Adam optimizer's 'betas' parameter is an example of a collection type parameter that is not support in the current version of the library via yaml config.
## Pitch
Introduce an extension to the syntax that allows specifying a collection type parameter with values supporting type conversion from strings. 
Example of yaml config.
...
betas: '[0.9,0.999]'
...
**Notes.**
A presence of the dot should force auto conversion to float.

## Alternatives

Introduce additional config parameters and create additional code wrappers that will use Pytorch api to set collection type parameters.

**Comment by apsdehal** [comment]
Hi,
Did you try passing:

```
betas:
- 0.9
- 0.999
```
?
