### ISSUE TITLE
AssertionError: Checksum of downloaded file does not match the expected checksum.

### ISSUE THREAD

**Issue by jiany-ctrl** [facebookresearch/mmf#611]
## ❓ Questions and Help

When I run command : mmf_convert_hm --zip_file /content/hm.zip --password ******* 

Getting checksum error while trying to run baseline for hateful memes dataset: AssertionError: Checksum of downloaded file does not match the expected checksum. Please try again.

Similar issue with closed #478 . In #478 , one comment said add --bypass_checksum and rerun, but after I run the command line like this:  mmf_convert_hm --zip_file /content/hm.zip --password ******* --bypass_checksum

There is another error like this: mmf_convert_hm: error: argument --bypass_checksum: expected one argument.

I am new student  to the CS area and please let me know how to solve this problem.

**Comment by apsdehal** [comment]
Hi, Please use `--bypass_checksum=1`

**Comment by jiany-ctrl** [comment]
> Hi, Please use `--bypass_checksum=1`

Thanks for your quick response. I have another question here:

I just follow this mmf_hm_example.ipynb from Google Colab and there is an error indicating the dataset I builded was not a registered dataset builder. Can you please help me solve this problem? Thanks
![Screenshot from 2020-10-06 15-23-32](https://user-images.githubusercontent.com/72469440/95256061-ea9e1300-07e7-11eb-82a1-ce254934edc9.png)

**Comment by apsdehal** [comment]
Please try to reload your runtime and try again. There are notes in the colab to troubleshoot the issues.

**Comment by CCYChongyanChen** [comment]
Hi, is there a way to disable checksum for regular download (not for HM) like passing --bypass_checksum=1? It takes too long to checksum every time I run the model. Thanks!

**Comment by CCYChongyanChen** [comment]
> Hi, is there a way to disable checksum for regular download (not for HM) like passing --bypass_checksum=1? It takes too long to checksum every time I run the model. Thanks!

For now I just commented the checksum function in download.py entirely...

**Comment by apsdehal** [comment]
Hi @CCYChongyanChen,
This feature is not yet available in MMF, can you open up a new issue for the feature request and we will work on that.
