### ISSUE TITLE
Not able to build dataset for hateful memes

### ISSUE THREAD

**Issue by SwatiTiwarii** [facebookresearch/mmf#612]
## ❓ Questions and Help
Hi I am following steps present here : 
https://medium.com/pytorch/bootstrapping-a-multimodal-project-using-mmf-a-pytorch-powered-multimodal-framework-464f75164af7

I have setup a Linux subsystem inside windows . 
And I am able to download and convert dataset 
![tempsnip](https://user-images.githubusercontent.com/46405184/95336846-c2d5aa80-08ce-11eb-8beb-6a2cd2e5cbd6.png)

After that I am able to see datasets folder in following location
**/home/tswati/.cache/torch/mmf/data/datasets/hateful_memes/**

But when I am trying to build dataset as suggested in tutorial , 
![image](https://user-images.githubusercontent.com/46405184/95337137-2d86e600-08cf-11eb-97a9-bf6dfb3a86a8.png)
I am facing above issue. is there some config change that needs to be done apart from steps mentioned in medium tutorial. 
Thanks in advance.

**Comment by apsdehal** [comment]
Hi,
To run MMF in interactive mode you need to also run `setup_imports`
Call this before running anything else:
```
from mmf.utils.env import setup_imports
setup_imports()
```

**Comment by SwatiTiwarii** [comment]
thanks it worked.
