### ISSUE TITLE
Running out of memory when training Lorra on VQA 

### ISSUE THREAD

**Issue by gaotongxiao** [facebookresearch/mmf#627]
## ❓ Questions and Help
Hi, 

I tried to retrain LORRA on VQA v2.0 with the provided configuration:

```
mmf_run config=projects/lorra/configs/vqa2/train_val.yaml model=lorra dataset=vqa2 run_type=train
```

However, just after 1000 training steps and as the evaluation begins, the program gets killed since it allocates more than 230GB of memory, which is not affordable on my server. I turned off the evaluation but the program still explodes at some time between the first 1k~2k steps. I wondered if it is due to memory leak, or it's just my server simply doesn't meet the minimum requirement for training on VQA?

**Comment by apsdehal** [comment]
Hi,
I would suggest running with `training.num_workers=0` if you are facing problems with memory. This would be slow but it should still work.

**Comment by gaotongxiao** [comment]
> Hi,
> I would suggest running with `training.num_workers=0` if you are facing problems with memory. This would be slow but it should still work.

Sorry but I forgot to mention that `training.num_workers` has been set to 0. That's why I felt surprised by the memory requirement.

**Comment by apsdehal** [comment]
We will have to check this. We will get back to you.

**Comment by apsdehal** [comment]
@gaotongxiao I tried replicating this, but couldn't. Can you provide me your server's specs?

**Comment by gaotongxiao** [comment]
I use slurm to submit the job to server, which runs ubuntu 18.04 with E5-2630, 8 x titan-v GPUs and 260GB RAM. Here is part of the slurm script:
```
### Node info
#SBATCH --nodes=1                                                           
#SBATCH --ntasks-per-node=1                                        # Number of tasks per node
#SBATCH --time 1000:00:00                                                     # Run time (hh:mm:ss)

#SBATCH --gres=gpu:1                                                       # Number of gpus needed
#SBATCH --mem=200G
#SBATCH --cpus-per-task=2                                             # Number of cpus needed per task

mmf_run config=projects/lorra/configs/vqa2/defaults.yaml model=lorra dataset=vqa2 run_type=train 
```

**Comment by gaotongxiao** [comment]
I found that when loading the model, the virtual memory usage suddenly increases from ~4000MB to 350GB. I guess slurm has counted virtual memory into memory usage as well. What can be the cause of overwhelming virtual memory usage, and is there any way to fix it?
