### ISSUE TITLE
BUTD: How to NOT use bottom-up attention?

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookresearch/mmf#640]
Hello,

In the BUTD paper, the authors proposed a strong baseline without the "bottom-up" part. Could you please tell me if it's possible to activate this mode in MMF?

Thank you very much in advance for your help!

**Comment by vedanuj** [comment]
Current implementation of BUTD isn't configurable to use without "bottom up" part. If you have cycles feel free to open a PR.
