### ISSUE TITLE
Option for using existing dataset files that are already locally available

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookresearch/mmf#643]
## 🚀 Feature

An option to take into account existing local copies of datasets (and to download only what's missing).

## Motivation

People working on other vision problems such as object detection or image segmentation probably already have a copy of popular datasets such as COCO. Re-downloading and keeping a second extracted copy for MMF seems sub-optimal (for large datasets, that would consume a lot of bandwidth and disk space).

## Pitch

I've just got started with MMF so it's hard to propose something good, but maybe a command line argument (e.g. `--dataroot`) could do the job?

**Comment by vedanuj** [comment]
If you want to use existing datasets you can override the paths to the dataset in the configs to point to your local dataset and disable `zoo_requirements` so it doesn't download anything. This is a two step process but it is possible to do this currently in MMF. Can you try that and if you feel the process is not user-friendly we can discuss more how to make it better.

**Comment by netw0rkf10w** [comment]
@vedanuj That seems to be a straightforward solution! I'll try that and get back. Thanks a lot!

**Comment by ZJ-Zhao** [comment]
how can i disable zoo_requirements

**Comment by dmlpt** [comment]
I just started using MMF and want to run inference on the UniT model #741. I already have the COCO dataset on my disk and don't want to download it again but the command in #741 downloads the dataset. Where and how can I disable the zoo_requirements to not download the dataset and also specify the dataset path? Thanks!
Also, I have the COCO data in standard format:
coco:
       |
       ->  annotations
       |
       ->  train2017
                           |-> img1.jpg, img2.jpg  ....
       |
       ->  val2017
                           |-> img1.jpg, img2.jpg  ....
       |
       ->  test2017
                           |-> img1.jpg, img2.jpg  ....

**Comment by apsdehal** [comment]
@dmlpt Can you try setting `dataset_config.vqa2.zoo_requirements=[]` so that it doesn't load any zoo requirements. If you do this, you need to map rest of the configs to point to proper paths. Let us know if you face any issues in this.

**Comment by dmlpt** [comment]
Thank You! It works. We need to set the "env.data_dir" to the folder containing the data.
