### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookresearch/mmf#647]
Hello,

I'm reading the documentation to get started with MMF, and realized that some pages in the documentation are outdated.

I have to implement a new model for image captioning that requires not only image features but also the original images for the forward pass. Thus, I guess I'll have to create a new dataset (to include the images), and then of course a new model.

I've checked [Terminology and Concepts](https://mmf.sh/docs/notes/concepts/), which I guess is fundamental for developing with MMF, but it's outdated. I've also checked [Adding a dataset](https://mmf.sh/docs/tutorials/dataset) but it's also outdated.

I would like to know if you have an updated version (e.g. beta or nightly) of the documentation available somewhere on the web. If not then could you please give an estimate of how much the documentation is outdated? I mean, if it's not "80% of the content is not accurate" then I guess I can still read those pages and have a basis.

Thank you very much in advance!

**Comment by vedanuj** [comment]
Most of the documentation has been updated. I think a few are not but we are working on them. I think the ones that are outdated have a "[Outdated]" tag. Others are updated.

**Comment by netw0rkf10w** [comment]
@vedanuj Thanks for your reply! Yes I asked the question because I saw the [Outdated] tag. I just want to know if most of the information on those pages are still highly relevant (even though some of them are to up-to-date) so that I can read them confidently.

**Comment by vedanuj** [comment]
Yes rest of them are updated and you can read them confidently.

**Comment by netw0rkf10w** [comment]
Awesome! Thanks a lot!

**Comment by vincent1rookie** [comment]
Hi, I found https://mmf.sh/docs/tutorials/dataset and https://mmf.sh/docs/notes/pretrained_models are still tagged as "Outdated". Is this possible to update those doc soon? Thanks
