### ISSUE TITLE
Support for multi-node training on Slurm

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookresearch/mmf#648]
## ❓ Questions and Help

Hello,

First of all sorry for having asked many questions in the last few hours. I couldn't find answers to these questions in the documentation or on Google.

I would like to know if MMF supports multi-node training on Slurm out-of-the-box. 

I tried submitting a training job on 2 nodes, each has 4 GPUs, thus 8 GPUs in total. In the logs I observed the following:

```
2020-10-21T01:28:23 | mmf.utils.distributed: Distributed Init (Rank 2): tcp://localhost:18188
2020-10-21T01:28:23 | mmf.utils.distributed: Distributed Init (Rank 3): tcp://localhost:18188
2020-10-21T01:28:23 | mmf.utils.distributed: Distributed Init (Rank 1): tcp://localhost:18188
2020-10-21T01:28:23 | mmf.utils.distributed: Distributed Init (Rank 0): tcp://localhost:18188
2020-10-21T01:28:24 | mmf.utils.distributed: Initialized Host node0 as Rank 2
2020-10-21T01:28:24 | mmf.utils.distributed: Initialized Host node0 as Rank 3
2020-10-21T01:28:24 | mmf.utils.distributed: Initialized Host node0 as Rank 1
2020-10-21T01:28:24 | mmf.utils.distributed: Initialized Host node0 as Rank 0
```

There's no Rank 4-7, so I guess the second node was not taken into account?

Thank you in advance for your help!

**Comment by vedanuj** [comment]
Yes mmf does support slurm. Here is the tutorial : https://mmf.sh/docs/tutorials/slurm

**Comment by netw0rkf10w** [comment]
@vedanuj Thank you for your answer, but that tutorial is about hyperparameter tuning, I can't see clearly how to apply that to a regular multi-node training...

**Comment by vedanuj** [comment]
Please check the command to run in that tutorial. It shows how to run on multiple nodes.

**Comment by netw0rkf10w** [comment]
@vedanuj Thanks. I have checked the [parameters](https://github.com/facebookresearch/mmf/blob/master/tools/sweeps/lib/__init__.py) of `sweeps` but there doesn't seem to have a parameter for the number of GPUs (or number of nodes) **per trial**.

For example, suppose I have 512 GPUs available and I would like to perform hyper-parameter tuning with 1000 trials. In addition, I would like each trial to run on 16 GPUs. How can I do that? If it's not possible to set the number of GPUs per trial, then what is the default value? I mean, if I launch `sweeps` with 1000 trials on 512 GPUs with the current code, what will happen?

**Comment by vedanuj** [comment]
If you check the tutorial in detail we have comments saying how to set number of GPUs and nodes. You are looking for the parameters `-g` and `-n`.

```bash
# This will log into folder: /home/user/jobs/my_job.bs512.lr5e-05.ngpu16/
# for one of the sweeps among 4.
# Explanation for each of the parameters:
# --resume_finished: Don't skip finished runs, this won't run already running jobs
# --resume_failed: Resume errored out runs from before
# --checkpoints_dir /home/user/jobs: Directory where log folder will be created
# -t -1: Run all sweeps, if t=1, run first combination only
# -g 8: 8 GPUs per node
# -n 2: 2 Nodes in total
# --constraint some_constraint: Slurm constraint if any
# --comment "My run": Slurm comment
# --partition some_partition: Slurm partition
# -p my_job: Prefix for log folder
```

**Comment by netw0rkf10w** [comment]
Hi @vedanuj,

Those parameters are for setting the total number of nodes and GPUs, but not per trial, which is the most important parameter here (that's why I put **per trial** in **boldface** in the previous comment). It's not clear **how much resources are devoted to each trial**.

**Comment by apsdehal** [comment]
`-g` specifies total number of GPUs per node. `-n` specifies total number of nodes.

If you have only 512 nodes and you say 16 GPUs for each job, you will have 512/16=32 jobs running and rest will have to wait for these ones to finish.
