### ISSUE TITLE
Issues with loading weights

### ISSUE THREAD

**Issue by galsk87** [facebookresearch/mmf#650]
## ❓ Questions and Help
I'm training VisualBert with this command:
`mmf_run config=projects/visual_bert/configs/vqa2/defaults.yaml run_type=train_val dataset=vqa2 model=visual_bert training.find_unused_parameters=True
`

I'm trying to load weights this way:
`    mmf_model = VisualBERT("/home/gal/mmf/projects/visual_bert/configs/vqa2/defaults.yaml").from_pretrained('/home/gal/mmf/save/models/model_1000.ckpt')
`
And I'm getting the next error:

Any idea why?

`Traceback (most recent call last):
  File "/snap/pycharm-professional/218/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/218/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/gal/lxmert/src/tasks/mmf_vqa.py", line 223, in <module>
    vqa = VQA()
  File "/home/gal/lxmert/src/tasks/mmf_vqa.py", line 73, in __init__
    self.mmf_model = VisualBERT("/home/gal/mmf/projects/visual_bert/configs/vqa2/defaults.yaml").from_pretrained('/home/gal/mmf/save/models/model_1000.ckpt')
  File "/home/gal/mmf/mmf/models/base_model.py", line 198, in from_pretrained
    ), f"Incorrect pretrained model key {model_name} for class {cls.__name__}"
AssertionError: Incorrect pretrained model key /home/gal/mmf/save/models/model_1000.ckpt for class VisualBERT`

Any ideas why that happens?

**Comment by g-luo** [comment]
Maybe try running 

`
mmf_run config=projects/visual_bert/configs/vqa2/defaults.yaml run_type=train_val dataset=vqa2 model=visual_bert training.find_unused_parameters=True checkpoint.resume_file=/home/gal/mmf/save/models/model_1000.ckpt 
`

It looks like it might think your file is a pretrained model in the zoo (for example a valid one would be `visual_bert.pretrained.vqa2.full`)

**Comment by apsdehal** [comment]
Thanks for the reply, @g-luo.

@galsk87 There isn't a smooth way to currently do this but is in work. You can do something like if you save_dir was `x`:

```
from mmf.utils.configuration import load_yaml

config = load_yaml("x/config.yaml")
vb = VisualBERT(config)
vb.load_state_dict(torch.load("x/best.ckpt")["model")
```

**Comment by galsk87** [comment]
`
self.mmf_model = VisualBERT("/home/gal/mmf/projects/visual_bert/configs/vqa2/defaults.yaml").from_pretrained('visual_bert.pretrained.coco')
ckpt = torch.load('/home/gal/save/models/model_10000.ckpt')
self.load_my_state_dict(ckpt['model'])
`
this is my workaround function:
`
def load_my_state_dict(self, state_dict):

        own_state = self.mmf_model.state_dict()
        for name, param in state_dict.items():
            if name not in own_state:
                continue
            own_state[name].copy_(param)`

**Comment by apsdehal** [comment]
Closing as resolved! Thanks for your solution @galsk87

**Comment by HenryJunW** [comment]
Hello, i am new to pycharm, and I noticed that you run the commands 'mmf_run config=projects/visual_bert/configs/vqa2/defaults.yaml run_type=train_val dataset=vqa2 model=visual_bert training.find_unused_parameters=True' successfully using pycharm. May I ask how you edit the **Run Configuration**? Are you using Python interpretation or Shell script interpretation? From my point of view, I need to specify a script path if i use remote python, which i don't know what to put. Also, it is difficult for me to understand where to put the executable file mmf_run. Thanks in advance.

**Comment by g-luo** [comment]
You can edit the config by setting `config=<local path to your config file>`. You can find an example config file [here](https://github.com/facebookresearch/mmf/blob/notebooks/mmf/configs/datasets/vqa2/defaults.yaml).  This command should be run on the shell; I believe to run mmf in python you need to use [mmf_cli/mmf/run.py] (https://github.com/facebookresearch/mmf/blob/f6bb22d97f0a1f6abd73e8b3386a5541ac48e0d8/mmf_cli/run.py). They have a good tutorial [here](https://github.com/facebookresearch/mmf/blob/notebooks/notebooks/kdd_tutorial.ipynb), where it says the python command should look like:

```
from mmf_cli.run import run

opts = [
        "config=/content/experiment_config.yaml",
        "model=mmf_transformer",
        "dataset=okvqa_colab",
        "training.log_interval=10",
        "training.batch_size=8",
        "training.max_updates=100",
        # Head is in dangling state, ignore git details in checkpoints
        "checkpoint.save_git_details=False",
]


run(opts)
```

**Comment by HenryJunW** [comment]
Thanks for your instant reply. I will give a shot using the code snippet you gave to deploy the command in the Pycharm.
