### ISSUE TITLE
train.log should be replaced by <run_type>.log

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookresearch/mmf#653]
## 🚀 Feature

`train.log` should be replaced by `<run_type>.log`, i.e. when `train.log` when `run_type=train` and `val.log` when `run_type=val`.

## Motivation

I launched a training (on a Slurm server), which produced a log file at `save/train.log`. After the training has finished, I launched an evaluation of the trained model using (of course) the same configuration file: my training logs `save/train.log` were replaced by the evaluation logs, which is clearly not desirable.

**Comment by apsdehal** [comment]
We usually run `run_type=train_val` or `run_type=train_val_test` and in most cases, I think all those should go into single log. That allows us to process multiple training logs together via glob patterns. I will have to discuss with team but I am not sure that we will make this change to keep things consistent. You can always select a different `env.save_dir` if you don't want logs to garble up.

**Comment by netw0rkf10w** [comment]
Hi @apsdehal ! Thanks for the reply.

> We usually run `run_type=train_val` or `run_type=train_val_test` and in most cases, I think all those should go into single log. That allows us to process multiple training logs together via glob patterns. 

It seems you misunderstood my proposal. I never proposed to split the logs into `train.log` and `val.log`. 

If `run_type=train_val` then the log file should be `train_val.log`, and if `run_type=train_val_test` then the log file should be `train_val_test.log`. If `run_type=whatever_you_like` then the log file should be `whatever_you_like.log`. In general, the log file should be `<run_type>.log`, as clearly put in the title.

> I will have to discuss with team but I am not sure that we will make this change to keep things consistent. You can always select a different `env.save_dir` if you don't want logs to garble up.

Obviously one can modify the config file, but it doesn't make sense to have two separate config files, one for training and one for validation.
