### ISSUE TITLE
Spelling errors and typos in the documentation

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookresearch/mmf#657]
## 🐛 Bug

Hi,

I've spot some spelling errors and typos in the documentation. Let me create this issue to track and fix them (I will edit the post to update the list as it grows). I can submit PRs, but only in a few weeks because of some important upcoming deadlines.

1. There are a lot of "for e.g." in the documentation and in the code docstrings/comments. Searching in VS Code, there are currently 23 instances in the master branch. The abbreviation "e.g." does not mean "example", it means "for example", thus "for e.g." reads "for for example", which doesn't make sense.

**Fix:**
- All "for e.g." instances should be replaced by either "e.g." or "for example".
- All "For e.g." (i.e. start of sentence) instances should be replaced by "For example".

**Comment by vedanuj** [comment]
Feel free to open up the PR to fix these when you get cycles. Thanks!
