### ISSUE TITLE
Any support for mpi run?

### ISSUE THREAD

**Issue by naykun** [facebookresearch/mmf#660]
## ❓ Questions and Help
I'm trying to use mmf on a multi-node cluster which only supports mpi to launch jobs across nodes. It seems mmf_run doesn't work in that scenario, at least out of the box. Is there any suggestions or tutorial available for how to using mmf on a mpi cluster? 
By the way, maybe handling mpi args such as "OMPI_COMM_WORLD_RANK", "OMPI_COMM_WORLD_SIZE", "OMPI_COMM_WORLD_LOCAL_RANK", "OMPI_COMM_WORLD_LOCAL_SIZE" inside mmf will help mmf support mpi launching natively?

Thanks in advance.

**Comment by apsdehal** [comment]
Hi,

This isn't currently available in MMF and isn't on our roadmap. But feel free to open up a PR for this. This should be easy to add if you take a look `mmf/utils/distributed.py` and related config options.
