### ISSUE TITLE
An error about reading database file

### ISSUE THREAD

**Issue by JayZhu0104** [facebookresearch/mmf#662]
## ❓ Questions and Help
When I was running the following command: 
`mmf_run config=projects/m4c/configs/textvqa/defaults.yaml datasets=textvqa model=m4c env.data_dir=G:\datasets\TextVQA\data run_type=train_val`

An error has occurred:
![1603722036349](https://user-images.githubusercontent.com/40751213/97184108-87e1db00-17d9-11eb-9ca2-5af91f43d256.png)
There is no b'train\\e64a1fa5dc1353bf' key in self.image_id_indices.

Because the download data set in the program was too slow, I downloaded and unzipped it myself. Are the datasets files that I downloaded wrong?

The files are under the datasets\ TextVQA \defaults\features path:
![image](https://user-images.githubusercontent.com/40751213/97184754-3a19a280-17da-11eb-8448-2badfd2dea0a.png)
And the the files are under the datasets\textvqa\defaults\features\open_images\detectron.lmdb path:
![image](https://user-images.githubusercontent.com/40751213/97184995-806f0180-17da-11eb-8fff-2dcc24548cf8.png)

**Comment by apsdehal** [comment]
Hi,
This is happening because of the windows path that MMF isn't expecting. Fixing this will take time. Would it be possible that you can run this in Ubuntu VM available inside Windows?

NOTE: PyTorch doesn't support distributed training on Windows so that limitation would still stay.

**Comment by JayZhu0104** [comment]
> Hi,
> This is happening because of the windows path that MMF isn't expecting. Fixing this will take time. Would it be possible that you can run this in Ubuntu VM available inside Windows?
> 
> NOTE: PyTorch doesn't support distributed training on Windows so that limitation would still stay.

OK！Thank you for your reply!
