### ISSUE TITLE
Can I change the path to download the dataset file? Where to modify?

### ISSUE THREAD

**Issue by vovocol** [facebookresearch/mmf#665]
## ❓ Questions and Help
Can I change the path to download the dataset file?
Where to modify?

**Comment by apsdehal** [comment]
Please use `env.data_dir` to specify where you want to download the dataset file.

**Comment by vovocol** [comment]
> Please use `env.data_dir` to specify where you want to download the dataset file.

Can you show me a concrete example?

**Comment by apsdehal** [comment]
Try something like
`<your command> env.data_dir=/x/y/z`

**Comment by apsdehal** [comment]
Closing as resolved.
