### ISSUE TITLE
Any ideas how to perform ITM with MMF?

### ISSUE THREAD

**Issue by floschne** [facebookresearch/mmf#667]
## ❓ Questions and Help
Hi,
I want to do text-image retrieval and really would like to use your awesome framework :-)
But.. I haven't found a way to do so or at least I have no idea in my head how to do it because I can't find any Task, Project, Head, Model, or Layer that is related to ITM / IR.

Do you have any suggestions on how to do text-image retrieval within MMF? I would really appreciate your help :-)

Thanks in advance!

**Comment by floschne** [comment]
Hi @ytsheng,

Thanks for you reply, I'm gonna have a look at the PR :)

Since I'm working on my master thesis, I have a more or less right schedule.. but I'll find a way :-)
When are you planning to add the retrieval components ?

Thanks for developing this awesome framework ;)

**Comment by ytsheng** [comment]
It's definitely on our list of things to do!
But, before we get to it, if your time allows, I strongly recommend that you help contribute the functionality to mmf. We will try our best to review your code! 

Keep us posted on how we can support you better!

Thank you! 😄

**Comment by ytsheng** [comment]
Closing the issue - let us know how we can help more. :)
