### ISSUE TITLE
Train  M4C Captioner using VizWiz

### ISSUE THREAD

**Issue by nbhalla93** [facebookresearch/mmf#682]
## ❓ Questions and Help
Hello

I am trying to train the M4C Captioner using VizWiz:
On this page: https://mmf.sh/docs/notes/dataset_zoo/, it mentions that the VizWiz dataset is supported in MMF. Does this mean the dataset builder is available for Vizwiz? If Yes, what are the instructions to get this dataset? If No, what dataset builder can be used to create the dataset builder for VizWiz? 

https://mmf.sh/docs/getting_started/features: 
<img width="790" alt="Screen Shot 2020-11-16 at 8 41 24 AM" src="https://user-images.githubusercontent.com/19534655/99259140-9410f500-27e7-11eb-9a24-85e944e4ce77.png">

**Comment by parambole** [comment]
@apsdehal Can you please find some time to answer this?

**Comment by apsdehal** [comment]
Hi,
It is unclear to me what exactly you are trying to do here. M4C Captioner is a captioning model while VizWiz is QA dataset. If you are trying to run it on VizWiz captions, easiest way to go here would be convert VizWiz Captions to the same format as of TextCaps's annotation file and just replace TextCaps's annotations files with those of the VizWiz Captions.

This would work but there are other things that you will need to solve. 
- M4C Captioner requires OCR tokens and related OCR features extracted using @ronghanghu's VQA MaskRCNN benchmark repo. For OCR tokens, you can probably use Google's Cloud Vision service.  
- Once you have tokens you can use these tokens and the VQA Maskrcnn benchmark repo to extract OCR features.
- For image features, you can replace the TextVQA features with VizWiz's features. (but that I believe are old and VizWiz Captions uses a new subset maybe?, if that's the case you will have to extract out image features as well, there are multiple issues that document how to do this).

**Comment by soumyasj** [comment]
> Hi,
> It is unclear to me what exactly you are trying to do here. M4C Captioner is a captioning model while VizWiz is QA dataset. If you are trying to run it on VizWiz captions, easiest way to go here would be convert VizWiz Captions to the same format as of TextCaps's annotation file and just replace TextCaps's annotations files with those of the VizWiz Captions.
> 
> This would work but there are other things that you will need to solve.
> 
> * M4C Captioner requires OCR tokens and related OCR features extracted using @ronghanghu's VQA MaskRCNN benchmark repo. For OCR tokens, you can probably use Google's Cloud Vision service.
> * Once you have tokens you can use these tokens and the VQA Maskrcnn benchmark repo to extract OCR features.
> * For image features, you can replace the TextVQA features with VizWiz's features. (but that I believe are old and VizWiz Captions uses a new subset maybe?, if that's the case you will have to extract out image features as well, there are multiple issues that document how to do this).

How to replace TextCap's annotations file with other captions file?
