### ISSUE TITLE
pythia: Object-level features and grid level features

### ISSUE THREAD

**Issue by ckj1221** [facebookresearch/mmf#687]
## ❓ Questions and Help
In pythiav0.1 ,"Object-level features and grid level features are separately fused with features from ques tions and then are concatenated to fed to classification" .How is this problem implemented in the code?
Can the extracted features be converted into compressed packages for other training models to use?

**Comment by vedanuj** [comment]
This might be what you are looking for : https://github.com/facebookresearch/mmf/blob/2a0c567b6caadad3aface611f73849631ed2fbca/mmf/models/pythia.py#L272

> Can the extracted features be converted into compressed packages for other training models to use?

Not sure what exactly you mean here. Do you want to first combine the features and then use?

**Comment by apsdehal** [comment]
I believe that @vedanuj already answered the question satisfactorily. About the features, yes they are used in multiple places and models in MMF. They are usually dataset specific though.

**Comment by ckj1221** [comment]
sorry my English is not very good.  wonder if I can use this feature in my last project, just like bottom-up provides processed image features for us to download. Can the processed files be downloaded directly?

**Comment by ckj1221** [comment]
@vedanuj sorry my English is not very good. wonder if I can use this feature in my last project, just like bottom-up provides processed image features for us to download. Can the processed files be downloaded directly?
