### ISSUE TITLE
How can I evaluate on the dataset by batches?

### ISSUE THREAD

**Issue by Yui010206** [facebookresearch/mmf#688]
## ❓ Questions and Help
Hi, I want to know how can I evaluate on the dataset and output the evaluation by batches. I notice that the evaluation_loop()  in mmf/trainer/core/evaluation_loop.py call function accumulate_tensor_fields(). It seems to accumulate all output and target tensor and evaluation on the whole dataset which may cause out of memory when both my dataset size and output size are too large. It there any other setting that I missed?

**Comment by vedanuj** [comment]
Currently this setup ensures that metrics that require evaluation on full dataset work and hence in general we accumulate the output and do the evaluation. We are aware that this sometimes leads to OOM when the dataset size is huge. We will address this issue soon. 

Can you also let us know which metric you are using and what is the size of your evaluation set?
