### ISSUE TITLE
how to change download location in hateful memes

### ISSUE THREAD

**Issue by ChunCun** [facebookresearch/mmf#689]
## ❓ Questions and Help
Hi, when I try to download things like features or extras, I know I can specify download path by using "env.data_dir=/x/y". However, when mmf tries to automatically download things like vectors, it always downloads them automatically under /home/UserName/.cache/torch/mmf. How can I avoid this situation? (the home directory is limited space due to my working environment) Thanks!

**Comment by vedanuj** [comment]
You can change the location of cache directory as well. Use `env.cache_dir=<your_location>`.

**Comment by cyang31** [comment]
Thanks! BTW, where can I find all the changeable variables in env?

**Comment by vedanuj** [comment]
The configurable env variables are here : https://github.com/facebookresearch/mmf/blob/2a0c567b6caadad3aface611f73849631ed2fbca/mmf/configs/defaults.yaml#L182
