### ISSUE TITLE
Install error with "/tmp/pip-i0sfvtwm-build/"

### ISSUE THREAD

**Issue by tiffmkell** [facebookresearch/mmf#695]
<img width="1018" alt="Screen Shot 2020-11-22 at 8 56 25 PM" src="https://user-images.githubusercontent.com/8855593/99927103-09158a80-2d12-11eb-8338-87d355912e51.png">

**Comment by ytsheng** [comment]
Hi! Thanks for using mmf!

Please checkout our `notebook` branch to see how you can use mmf in notebooks. 👯 

for example:
https://colab.research.google.com/gist/apsdehal/062b779406208f87974b2175fc267ae7/mmf_hm_example.ipynb

**Comment by apsdehal** [comment]
@tiffmkell Are you on Windows by any chance? Can you provide output `python -m torch.utils.collect_env` for our debugging purposes?
