### ISSUE TITLE
Will the framework support rtx30xx in the future？

### ISSUE THREAD

**Issue by graydove** [facebookresearch/mmf#701]
## ❓ Questions and Help
When I use rtx3090 for training model，I meet this error:

RuntimeError: CUDA error: no kernel image is available for execution on the device

Maybe it's a compatibility problem...so I'll try using other gpus for mmf.

**Comment by vedanuj** [comment]
This is not specifically a problem with mmf, but the pytorch version you are using and compatibility with the CUDA version supported for your GPU type.

**Comment by graydove** [comment]
Thank you, maybe I should wait for a new version pytorch.

**Comment by apsdehal** [comment]
Closing as this is upstream pytorch issue. If other issues persist, please open up a new issue.
