### ISSUE TITLE
Submitted TextVQA accuracy and local val accuracy have a gap

### ISSUE THREAD

**Issue by ChenyuGAO-CS** [facebookresearch/mmf#703]
## ❓ Questions and Help
Are the submitted results of TextVQA by you have a gap? Our local TextVQA val accuracy and submitted TextVQA accuracy always have a large margin (maybe > 1%), which bothers us a lot.

**Comment by apsdehal** [comment]
Hi,
We believe this should be fixed if you use metric as `textvqa_accuracy` but we can double confirm if this is the case.
