### ISSUE TITLE
outputting bounding boxes with visual and text input

### ISSUE THREAD

**Issue by fossil-ai** [facebookresearch/mmf#704]
## ❓ Questions and Help
Is there anyway to support localization in this framework? As with any object detection framework except with textual guidance. e.g image and text input helps localize a box on the input image as seen in the referring expression task e.g MattNet.

**Comment by apsdehal** [comment]
Hi,
You can possibly implement it. Adapt for example visual bert model to instead predict num_labels=100 and then loss is accordingly calculated based on softmax on whether it got it right or not. Similar framework, https://github.com/facebookresearch/vilbert-multi-task/blob/master/vilbert/vilbert.py should have an example on how to do this. @vedanuj can help with specifics.
