### ISSUE TITLE
Where is the specific code of TextVQA

### ISSUE THREAD

**Issue by MonsKim999** [facebookresearch/mmf#706]
Hi, FAIR.

Thank you for opening the code.
I want to study and reimplement the code of TextVQA.However, I'm not familiar with this mmf system.
I can't find the specific module like data loader, preprocessing, extract_image_featue...

So, I need help where is the reference fo LoRRA.
Thank you!

**Comment by apsdehal** [comment]
Hi,

- Code for TextVQA dataset is available in https://github.com/facebookresearch/mmf/tree/master/mmf/datasets/builders/textvqa
- Model code for LoRRA is available in https://github.com/facebookresearch/mmf/blob/master/mmf/models/lorra.py
- Required configs for the TextVQA and LoRRA are in https://github.com/facebookresearch/mmf/tree/master/projects/lorra

Let us know if something is confusing or not clear.

**Comment by MonsKim999** [comment]
@apsdehal

Hi, apsdehal.
Thank you for your kind reply.

I have some questions.
I succeeded to run the extract_features_vmb.py by looking at many issues in your repository.

1. Could you provide the final extracted image features ? it is because it takes so many times since my GPU resources are not enough. 
2. Could I know the part of preprocessing the question tokens and OCR tokens?
3. Could I get the pre-trained LoRRA model?
4. Could you let me know how to run the test and evaluation? 

Sorry for the many questions ... I'm so confusing the integrated repository system.
Thank you :)

**Comment by apsdehal** [comment]
1. If you download TextVQA dataset using MMF, it will automatically download the features you are looking for.
2. For preprocessing, please check the config you want in the folder I shared above and look for the processors configuration. Map this to processors present in `mmf/datasets/processors` folder.
3. We don't have pretrained model for LoRRA directly usable with current mmf as it was superseded by better model M4C which we do have inside MMF.
4. Please check the documentation for M4C on how to run M4C. https://mmf.sh/docs/projects/m4c

**Comment by MonsKim999** [comment]
@apsdehal 

Thank you. It was very helpful. I closed this issue :+1:

**Comment by ytsheng** [comment]
closing as the author of this issue suggested.
