### ISSUE TITLE
Fine-tune M4C on TextVQA using m4c.ocrvqa.defaults (pretrained model on OCR-VQA)

### ISSUE THREAD

**Issue by sweta125** [facebookresearch/mmf#707]
## ❓ Questions and Help
Hi I am trying to run the following to fine-tune M4C on TextVQA from a pre-trained version on OCR-VQA:

! mmf_run config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=train_val \
    checkpoint.resume_pretrained=True \
    checkpoint.resume_zoo=m4c.ocrvqa.defaults \
    env.save_dir=./save/m4c_final_yay

Is there a way to change perhaps the config files to fix the shape mismatches? (I tried changing the vocab files in textvqa/defaults.yaml) but receive the same error.

Here is the full output/error:
2020-12-09T00:33:12 | mmf.utils.configuration: Overriding option config to projects/m4c/configs/textvqa/defaults.yaml
2020-12-09T00:33:12 | mmf.utils.configuration: Overriding option datasets to textvqa
2020-12-09T00:33:12 | mmf.utils.configuration: Overriding option model to m4c
2020-12-09T00:33:12 | mmf.utils.configuration: Overriding option run_type to train_val
2020-12-09T00:33:12 | mmf.utils.configuration: Overriding option checkpoint.resume_pretrained to True
2020-12-09T00:33:12 | mmf.utils.configuration: Overriding option checkpoint.resume_zoo to m4c.ocrvqa.defaults
2020-12-09T00:33:12 | mmf.utils.configuration: Overriding option env.save_dir to ./save/m4c_final_yay
2020-12-09T00:33:12 | mmf: Logging to: ./save/m4c_final_yay/train.log
2020-12-09T00:33:12 | mmf_cli.run: Namespace(config_override=None, local_rank=None, opts=['config=projects/m4c/configs/textvqa/defaults.yaml', 'datasets=textvqa', 'model=m4c', 'run_type=train_val', 'checkpoint.resume_pretrained=True', 'checkpoint.resume_zoo=m4c.ocrvqa.defaults', 'env.save_dir=./save/m4c_final_yay'])
2020-12-09T00:33:12 | mmf_cli.run: Torch version: 1.6.0
2020-12-09T00:33:12 | mmf.utils.general: CUDA Device 0 is: Tesla T4
2020-12-09T00:33:12 | mmf_cli.run: Using seed 12052891
2020-12-09T00:33:12 | mmf.trainers.mmf_trainer: Loading datasets
2020-12-09T00:33:20 | mmf.trainers.mmf_trainer: Loading model
Some weights of the model checkpoint at bert-base-uncased were not used when initializing TextBert: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'bert.encoder.layer.3.attention.self.query.weight', 'bert.encoder.layer.3.attention.self.query.bias', 'bert.encoder.layer.3.attention.self.key.weight', 'bert.encoder.layer.3.attention.self.key.bias', 'bert.encoder.layer.3.attention.self.value.weight', 'bert.encoder.layer.3.attention.self.value.bias', 'bert.encoder.layer.3.attention.output.dense.weight', 'bert.encoder.layer.3.attention.output.dense.bias', 'bert.encoder.layer.3.intermediate.dense.weight', 'bert.encoder.layer.3.intermediate.dense.bias', 'bert.encoder.layer.3.output.dense.weight', 'bert.encoder.layer.3.output.dense.bias', 'bert.encoder.layer.4.attention.self.query.weight', 'bert.encoder.layer.4.attention.self.query.bias', 'bert.encoder.layer.4.attention.self.key.weight', 'bert.encoder.layer.4.attention.self.key.bias', 'bert.encoder.layer.4.attention.self.value.weight', 'bert.encoder.layer.4.attention.self.value.bias', 'bert.encoder.layer.4.attention.output.dense.weight', 'bert.encoder.layer.4.attention.output.dense.bias', 'bert.encoder.layer.4.intermediate.dense.weight', 'bert.encoder.layer.4.intermediate.dense.bias', 'bert.encoder.layer.4.output.dense.weight', 'bert.encoder.layer.4.output.dense.bias', 'bert.encoder.layer.5.attention.self.query.weight', 'bert.encoder.layer.5.attention.self.query.bias', 'bert.encoder.layer.5.attention.self.key.weight', 'bert.encoder.layer.5.attention.self.key.bias', 'bert.encoder.layer.5.attention.self.value.weight', 'bert.encoder.layer.5.attention.self.value.bias', 'bert.encoder.layer.5.attention.output.dense.weight', 'bert.encoder.layer.5.attention.output.dense.bias', 'bert.encoder.layer.5.intermediate.dense.weight', 'bert.encoder.layer.5.intermediate.dense.bias', 'bert.encoder.layer.5.output.dense.weight', 'bert.encoder.layer.5.output.dense.bias', 'bert.encoder.layer.6.attention.self.query.weight', 'bert.encoder.layer.6.attention.self.query.bias', 'bert.encoder.layer.6.attention.self.key.weight', 'bert.encoder.layer.6.attention.self.key.bias', 'bert.encoder.layer.6.attention.self.value.weight', 'bert.encoder.layer.6.attention.self.value.bias', 'bert.encoder.layer.6.attention.output.dense.weight', 'bert.encoder.layer.6.attention.output.dense.bias', 'bert.encoder.layer.6.intermediate.dense.weight', 'bert.encoder.layer.6.intermediate.dense.bias', 'bert.encoder.layer.6.output.dense.weight', 'bert.encoder.layer.6.output.dense.bias', 'bert.encoder.layer.7.attention.self.query.weight', 'bert.encoder.layer.7.attention.self.query.bias', 'bert.encoder.layer.7.attention.self.key.weight', 'bert.encoder.layer.7.attention.self.key.bias', 'bert.encoder.layer.7.attention.self.value.weight', 'bert.encoder.layer.7.attention.self.value.bias', 'bert.encoder.layer.7.attention.output.dense.weight', 'bert.encoder.layer.7.attention.output.dense.bias', 'bert.encoder.layer.7.intermediate.dense.weight', 'bert.encoder.layer.7.intermediate.dense.bias', 'bert.encoder.layer.7.output.dense.weight', 'bert.encoder.layer.7.output.dense.bias', 'bert.encoder.layer.8.attention.self.query.weight', 'bert.encoder.layer.8.attention.self.query.bias', 'bert.encoder.layer.8.attention.self.key.weight', 'bert.encoder.layer.8.attention.self.key.bias', 'bert.encoder.layer.8.attention.self.value.weight', 'bert.encoder.layer.8.attention.self.value.bias', 'bert.encoder.layer.8.attention.output.dense.weight', 'bert.encoder.layer.8.attention.output.dense.bias', 'bert.encoder.layer.8.intermediate.dense.weight', 'bert.encoder.layer.8.intermediate.dense.bias', 'bert.encoder.layer.8.output.dense.weight', 'bert.encoder.layer.8.output.dense.bias', 'bert.encoder.layer.9.attention.self.query.weight', 'bert.encoder.layer.9.attention.self.query.bias', 'bert.encoder.layer.9.attention.self.key.weight', 'bert.encoder.layer.9.attention.self.key.bias', 'bert.encoder.layer.9.attention.self.value.weight', 'bert.encoder.layer.9.attention.self.value.bias', 'bert.encoder.layer.9.attention.output.dense.weight', 'bert.encoder.layer.9.attention.output.dense.bias', 'bert.encoder.layer.9.intermediate.dense.weight', 'bert.encoder.layer.9.intermediate.dense.bias', 'bert.encoder.layer.9.output.dense.weight', 'bert.encoder.layer.9.output.dense.bias', 'bert.encoder.layer.10.attention.self.query.weight', 'bert.encoder.layer.10.attention.self.query.bias', 'bert.encoder.layer.10.attention.self.key.weight', 'bert.encoder.layer.10.attention.self.key.bias', 'bert.encoder.layer.10.attention.self.value.weight', 'bert.encoder.layer.10.attention.self.value.bias', 'bert.encoder.layer.10.attention.output.dense.weight', 'bert.encoder.layer.10.attention.output.dense.bias', 'bert.encoder.layer.10.intermediate.dense.weight', 'bert.encoder.layer.10.intermediate.dense.bias', 'bert.encoder.layer.10.output.dense.weight', 'bert.encoder.layer.10.output.dense.bias', 'bert.encoder.layer.11.attention.self.query.weight', 'bert.encoder.layer.11.attention.self.query.bias', 'bert.encoder.layer.11.attention.self.key.weight', 'bert.encoder.layer.11.attention.self.key.bias', 'bert.encoder.layer.11.attention.self.value.weight', 'bert.encoder.layer.11.attention.self.value.bias', 'bert.encoder.layer.11.attention.output.dense.weight', 'bert.encoder.layer.11.attention.output.dense.bias', 'bert.encoder.layer.11.intermediate.dense.weight', 'bert.encoder.layer.11.intermediate.dense.bias', 'bert.encoder.layer.11.output.dense.weight', 'bert.encoder.layer.11.output.dense.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias']
- This IS expected if you are initializing TextBert from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing TextBert from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2020-12-09T00:33:27 | mmf.trainers.mmf_trainer: Loading optimizer
2020-12-09T00:33:27 | mmf.trainers.mmf_trainer: Loading metrics
WARNING 2020-12-09T00:33:27 | py.warnings: /home/ubuntu/mmf/mmf/utils/build.py:255: UserWarning: No type for scheduler specified even though lr_scheduler is True, setting default to 'Pythia'
  "No type for scheduler specified even though lr_scheduler is True, "

WARNING 2020-12-09T00:33:27 | py.warnings: /home/ubuntu/mmf/mmf/utils/build.py:255: UserWarning: No type for scheduler specified even though lr_scheduler is True, setting default to 'Pythia'
  "No type for scheduler specified even though lr_scheduler is True, "

WARNING 2020-12-09T00:33:27 | py.warnings: /home/ubuntu/mmf/mmf/utils/build.py:261: UserWarning: scheduler attributes has no params defined, defaulting to {}.
  warnings.warn("scheduler attributes has no params defined, defaulting to {}.")

WARNING 2020-12-09T00:33:27 | py.warnings: /home/ubuntu/mmf/mmf/utils/build.py:261: UserWarning: scheduler attributes has no params defined, defaulting to {}.
  warnings.warn("scheduler attributes has no params defined, defaulting to {}.")

2020-12-09T00:33:27 | mmf.utils.checkpoint: Loading checkpoint
WARNING 2020-12-09T00:33:29 | mmf: Key data_parallel is not present in registry, returning default value of None
WARNING 2020-12-09T00:33:29 | mmf: Key distributed is not present in registry, returning default value of None
WARNING 2020-12-09T00:33:29 | mmf: Key data_parallel is not present in registry, returning default value of None
WARNING 2020-12-09T00:33:29 | mmf: Key distributed is not present in registry, returning default value of None
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/ubuntu/mmf/mmf_cli/run.py", line 122, in run
    main(configuration, predict=predict)
  File "/home/ubuntu/mmf/mmf_cli/run.py", line 52, in main
    trainer.load()
  File "/home/ubuntu/mmf/mmf/trainers/mmf_trainer.py", line 46, in load
    self.on_init_start()
  File "/home/ubuntu/mmf/mmf/trainers/core/callback_hook.py", line 15, in on_init_start
    callback.on_init_start(**kwargs)
  File "/home/ubuntu/mmf/mmf/trainers/callbacks/checkpoint.py", line 31, in on_init_start
    self._checkpoint.load_state_dict()
  File "/home/ubuntu/mmf/mmf/utils/checkpoint.py", line 195, in load_state_dict
    load_pretrained=ckpt_config.resume_pretrained,
  File "/home/ubuntu/mmf/mmf/utils/checkpoint.py", line 237, in _load
    state_dict, strict=False
  File "/home/ubuntu/mmf/mmf/models/base_model.py", line 148, in load_state_dict
    return super().load_state_dict(copied_state_dict, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for M4C:
	size mismatch for classifier.module.weight: copying a param with shape torch.Size([82, 768]) from checkpoint, the shape in current model is torch.Size([5000, 768]).
	size mismatch for classifier.module.bias: copying a param with shape torch.Size([82]) from checkpoint, the shape in current model is torch.Size([5000]).

**Comment by sweta125** [comment]
It seems I should specify where to extract the ocrvqa embeddings in checkpoint.pretrained_state_mapping (model.mmt?) but its unclear to me how this should be done based on the documentation here: https://mmf.sh/docs/tutorials/checkpointing/

**Comment by apsdehal** [comment]
Yes, that's correct. So, mapping is used something like this:
if you mention
```
a: b
c: d
```
then a will be loaded from b, and c will be loaded from d. Rest of the state dict keys will be skipped. So, add rest of the keys except classifier and that should work.
