### ISSUE TITLE
Question about opening lmdb file to explore the data.

### ISSUE THREAD

**Issue by MonsKim999** [facebookresearch/mmf#708]
Hi,

I'd like to explore the dataset in detail. 
But I'm not familiar with lmdb file format. I searched how to open and look into this file exactly, but It is not easy to find suitable answer.

Could you help me how to open and give me some examples? (examples as like file.begin().get('bbox'),  file.begin().get('image_id'))

Thank you!

**Comment by apsdehal** [comment]
Hi,
Please check out our feature reader code to understand how we read the LMDBs. https://github.com/facebookresearch/mmf/blob/master/mmf/datasets/databases/readers/feature_readers.py#L217

**Comment by MonsKim999** [comment]
@apsdehal

Thanks a lot.
