### ISSUE TITLE
Visual bert hateful memes model key , how do I add fined tuned visual bert instead of pretrained?

### ISSUE THREAD

**Issue by MikeQ-hash** [facebookresearch/mmf#710]
## ❓ Questions and Help
Hi I have further trained the visual bert model with the hateful memes via command line as shown in the documentation. However I am having difficulty in understanding how I can add that model in main via a python code. 

For example 

model = MMBT.from_pretrained("mmbt.hateful_memes.images") 

This works, but :

model = VisualBERT.from_pretrained('visual_bert.pretrained.hateful_memes')

This does not work. In addition, I tried adding the trained file 'visual_bert_final.pth', however I am uncertain how to call it in?

I have not found any documentation on this. The error message I get is:

Traceback (most recent call last):
  File "try1.py", line 13, in <module>
    model = VisualBERT.from_pretrained('visual_bert.pretrained.hateful_memes')
  File "/home/michael/hackathon/mmf/mmf/models/base_model.py", line 223, in from_pretrained
    output = load_pretrained_model(model_name_or_path, *args, **kwargs)
  File "/home/michael/hackathon/mmf/mmf/utils/checkpoint.py", line 117, in load_pretrained_model
    return _load_pretrained_model(model_name_or_path_or_checkpoint, args, kwargs)
  File "/home/michael/hackathon/mmf/mmf/utils/checkpoint.py", line 71, in _load_pretrained_model
    download_path = download_pretrained_model(model_name_or_path, *args, **kwargs)
  File "/home/michael/hackathon/mmf/mmf/utils/download.py", line 352, in download_pretrained_model
    if "version" not in model_config or "resources" not in model_config:
TypeError: argument of type 'NoneType' is not iterable

**Comment by ytsheng** [comment]
Hi @MikeQ-hash, thank you for using mmf :) 

We are currently working to consolidate all model interfaces. Do you mind sharing what your model folder contains under: $DATA_DIR (typically `~/.cache/torch/mmf/data/models/visual_bert.pretrained.hateful_memes`).

**Comment by MikeQ-hash** [comment]
Hi @ytsheng , thank you for your reply. I spent more time looking into the github and found out that the right way to call visual bert is as follows:

from mmf.common.registry import registry
model_cls = registry.get_model_class('visual_bert')
model_vbert = model_cls.from_pretrained("visual_bert.finetuned.hateful_memes.direct") 

That would take care of the config and model file. Afterwards I would load the weights via pytoch model.load_state_dict(torch.load(PATH/filename.ckpt)). The code runs but I am uncertain if I have managed to load the weights I got from training. Can you confirm that something like that would work? I assumed it would not need be necessary for me to change the model.pth or config.yaml,  because I want exactly the same model but with just a little more fine tuning. Perhaps there is a different way to load from checkpoint within python (I know how to do so via command-line)

I assume that would also be the case with mmbt just with different model label as specified.

**Comment by apsdehal** [comment]
Can you try doing:

```
model.model.load_state_dict("your_path")
```
instead of
```
model.load_state_dict("your_path")
```
in your code?

**Comment by MikeQ-hash** [comment]
Hi all,

I managed to make it work (I double checked the performance on test set)

Here is the code below for mmbt (visual bert requires the respective pre-processing):

```
 filename_pth = './save/mmbt_final.pth'#your pth
    model = MMBT("./save/config.yaml").from_pretrained('mmbt.hateful_memes.images') #note your config path
    ckpt = torch.load(filename_pth)
    own_state = model.state_dict()

    temp = 0
    for name, param in ckpt.items():
        name = 'model.' + name
        if name not in own_state:
            print('fail')
            continue
        temp += 1
        print('succes')
        own_state[name].copy_(param)
    print(temp)

    #image_url = "https://i.imgur.com/tEcsk5q.jpg"  #
    #text = "what are ethiopian kids doing tonight?"

    output = model.classify(filename, text)
    plt.imshow(img)
    plt.axis("off")
    plt.show()
    hateful = "Yes" if output["label"] == 1 else "No"
    print("Hateful as per the model?", hateful)
    print(f"Model's confidence: {output['confidence'] * 100:.3f}%")
```
