### ISSUE TITLE
Question about feature files in open_images file

### ISSUE THREAD

**Issue by JayZhu0104** [facebookresearch/mmf#712]
## ❓ Questions and Help
Hi!
Datasets and required files were downloaded automatically when I ran training. And I don't know the difference between a 'detectron.lmdb' file and a 'resnet152.lmdb' file in "open_images" file.
Is the feature in the detectron.lMDB file is extracted by the ResNeXt-152 or  ResNet-101 based Faster R-CNN model?

**Comment by ytsheng** [comment]
Hi @JayZhu0104 , thanks for using mmf!

Yes, we probably should have renamed them to be specific, but I believe the `detectron.imdb` files are resnet101 based FasterRCNN model.

**Comment by JayZhu0104** [comment]
Thanks for your reply!
