### ISSUE TITLE
Possible typo in models.yaml

### ISSUE THREAD

**Issue by vecxoz** [facebookresearch/mmf#714]
## ❓ Questions and Help

Hi,

It seems like there is a wrong URL and file name in the following lines:
https://github.com/facebookresearch/mmf/blob/master/mmf/configs/zoo/models.yaml#L25-L26

Based on logic it should be `visual_bert.pretrained.coco_ten_pc.tar.gz` instead of `visual_bert.pretrained.coco.tar.gz`. But I’m not sure, maybe it was intended for some purpose?

**Comment by ytsheng** [comment]
Thanks @vecxoz for using mmf!

You have a good eye! #715
