### ISSUE TITLE
How to truncate the dataset for demo running?

### ISSUE THREAD

**Issue by hqsiswiliam** [facebookresearch/mmf#722]
## ❓ Questions and Help
Hi there,

Thanks for the great work, I'd like to ask how to truncate the dataset (for example `COCO`), so I can run part of it on my local machine instead of loading the full dataset.

**Comment by ytsheng** [comment]
Hi @hqsiswiliam, thanks for using mmf!

You can do one of two things:
* If you need to include specific parts of the dataset, you can preprocess the data files available in your $DATA_DIR, typically `~/.cache/torch/mmf/data/datasets/coco/defaults/annotations/<coco_annotation_file>`.
*  We actually have subsets of coco already truncated and they are available [here](https://github.com/facebookresearch/mmf/blob/f6bb22d97f0a1f6abd73e8b3386a5541ac48e0d8/mmf/configs/zoo/models.yaml)

Let us know if there is anything more we can help you with!

**Comment by hqsiswiliam** [comment]
Thank you. If I want to use a subset of coco instead of full, where can I find these files?

**Comment by ytsheng** [comment]
An example of how to find such a file is through looking at the dataset config files for subset of coco... ie., 

If you are looking for 50% of the coco files, you can check out the corresponding [yaml](https://github.com/facebookresearch/mmf/blob/master/projects/pretrain_vl_right/configs/vilbert/masked_coco/fifty_pc.yaml), and find the train annotations that is 50% of the original coco size. To download it, you can use this [link](https://dl.fbaipublicfiles.com/mmf/data/datasets/coco/defaults/annotations/annotations.tar.gz)

Hope this helps!

**Comment by hqsiswiliam** [comment]
Thanks, I will figure it out.

**Comment by ytsheng** [comment]
Also, I forgot that we have the dataset split feature as well if you want to try it out, you can decide what percentage of the train dataset to use. The API is specified in the PR:

https://github.com/facebookresearch/mmf/pull/470
