### ISSUE TITLE
Recall Metrics will result in Recursion error

### ISSUE THREAD

**Issue by hqsiswiliam** [facebookresearch/mmf#725]
## Command
Any running command
## To Reproduce

1. set model metrics to `r@5` (any recall metrics)
2. run command until validation run
3. There will be an error (*provided in Additional context section*)

## Expected behavior

Successfully validating at `r@5`

## Environment
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Zorin OS 15.2
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 440.82
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.6.0
[pip3] torchtext==0.5.0
[pip3] torchvision==0.7.0
[conda] numpy                     1.19.4                   pypi_0    pypi
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchtext                 0.5.0                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi

## Additional context

In `metric.py` file, we have
```python
@registry.register_metric("r@5")
class RecallAt5(RecallAtK):
    """
    Calculate Recall@5 which specifies how many time the chosen candidate
    was among first 5 rank.

    **Key**: ``r@5``.
    """

    def __init__(self):
        super().__init__("r@5")

    def calculate(self, sample_list, model_output, *args, **kwargs):
        """Calculate Recall@5 and return it back.

        Args:
            sample_list (SampleList): SampleList provided by DataLoader for
                                current iteration
            model_output (Dict): Dict returned by model.

        Returns:
            torch.FloatTensor: Recall@5

        """
        return self.calculate(sample_list, model_output, k=5)
```
But please notice that the `self.calculate` call will cause the infinite self-recursion on the method
The error is:
```
RecursionError: maximum recursion depth exceeded in comparison
```
---
Meanwhile, when I tried to do a monkeypatch on this method (I copied and renamed `calculate` in `RecallAtK`, and utilized the newly copied method in `RecallAt5`), I got an error:
```
AttributeError: 'RecallAt5' object has no attribute 'process_ranks'
```
I've searched through the project and found no `process_ranks` function declaration in the project.

**Comment by vedanuj** [comment]
Thanks for raising the bug. We will look into it.
