### ISSUE TITLE
butd demo results  "a close up of a white and white photo"

### ISSUE THREAD

**Issue by mnbv7581** [facebookresearch/mmf#729]
## ❓ Questions and Help

[https://colab.research.google.com/drive/1Z9fsh10rFtgWe4uy8nvU4mQmqdokdIRR?usp=sharing](url)

We implemented butd demo source by modifying the colab demo source. Using maskrcnnn_benchmark api, extract feature from COCO image and create a sample class. After setting with input data, the prediction progressed. Successful execution but learned by coco dataset Even though it is a model weight, the result is always "a close up of a white and white photo". by any chance Is there anything I missed?

```python

 def predict(self, url, question):
    with torch.no_grad():

      detectron_features, image = self.get_detectron_features(url)

      sample = Sample()

      tokens=[]
      ref_list = []
      for _ in range(0,52):
          tokens.append(0)
          
      tokens = torch.tensor(tokens)
      ref_list.append(tokens)

      sample.answers=torch.stack(ref_list)[: 5]
      sample.image_feature_0 = detectron_features
      #sample.image_feature_0 = resnet_features
      sample.image_info_0 = Sample({
          "max_features": torch.tensor(100, dtype=torch.long)
      })
      #sample.image_info_1 = Sample({
      #    "max_features": torch.tensor(196, dtype=torch.long)
      #})

      sample.dataset_name = 'coco'
      sample.dataset_type = 'val'

      sample_list = SampleList([sample])
      sample_list = sample_list.to("cuda")

      captions = self.butd_model(sample_list)["captions"]
      captions = captions[0].type(torch.int32).tolist()
      captions = self.caption_processor(captions)

    gc.collect()
    torch.cuda.empty_cache()
    
    return captions

```

**Comment by ytsheng** [comment]
Hi @mnbv7581, thanks for using mmf!

I believe there was an issue with `max_features` that was recently fixed/merged along with [this](https://github.com/facebookresearch/mmf/pull/700/files) PR. Try it let us know if it works now, if not, please share more code (e.g,, the model loading code) with us so that we can better assist you with debugging! 

Thank you!

**Comment by mnbv7581** [comment]
Thank you for your answers. There was some misunderstanding.  It has been confirmed to be normal for the pre-trained model. We will test again after completing the appropriate learning process.

**Comment by apsdehal** [comment]
Hi @mnbv7581,

Thanks for using MMF and your issue. This colab notebook would be really useful for people coming after you looking for a captioning demo. As you suggested, this is indeed expected. I am going to close this issue resolved for now. If you still face other issues or problems, please open up a new issue.
