### ISSUE TITLE
How to load grid features in pythia VQA 2.0 

### ISSUE THREAD

**Issue by Ifrahmaqsood** [facebookresearch/mmf#742]
## ❓ Questions and Help
I have extracted grid features of coco dataset with restnet50. I want to load it in pythia VQA 2.0. I have three folders of extracted features train2014,val2014,test2015. **In which file do I need to give path of these folders?**

Also, please let me know how would it affect this training command as currently it is taking the default configuration

mmf_run config=projects/mmf/configs/vqa2/defaults.yaml run_type=train_val dataset=vqa2 model=pythia

**Comment by vedanuj** [comment]
The config where you change the paths to your extracted features should be this if you want to use ONLY resnet features to train the pythia model: 

projects/pythia/configs/vqa2/resnet_only.yaml

There are also other configs in that folder if you want to use region_grid features etc.

**Comment by Ifrahmaqsood** [comment]
I am trying to implement paper **In Defense of Grid Features for Visual Question Answering**
I have done pretraining on visual_genome dataset and then loaded the model to extract features on coco dataset. Now my Grid features on resnet50 looks like this.
Each image is saved like this **388155.pth** under the respective folder i-e(train/test/val).

**for resnet-only.yaml config file i changed the following**
includes:
- ./defaults.yaml

dataset_config:
  vqa2:
    use_images: false
    use_features: true
    zoo_requirements:
    - coco.resnet152
    - vqa2.defaults
    **features:
      train:
      - path/to/train2014
      val:
      - path/to/val2014
      test:
      - path/to/test2015**
model_config:
  pythia:
    image_feature_encodings:
    - type: default
      params: {}

**what else do I need to change here.**

Also, it throws an error
**No such file or directory: 'path/to/train2014/COCO_train2014_000000058624.npy'**

but I needed it to take the images with 388155.pth extension and train accordingly.
this is not how my images are named "COCO_train2014_000000058624.npy"

**Comment by Ifrahmaqsood** [comment]
how can i get the annotations for grid features? Any direct link to them? As, I assume that it is causing issue because of annotation files that are saved with these names. I have my own grid features for coco dataset but not the annotation files for them
