### ISSUE TITLE
git clone https://github.com/facebookresearch/mmf.git 

### ISSUE THREAD

**Issue by sandeepmte** [facebookresearch/mmf#743]
## 🐛 Bug

(vqa_v1) F:\Pythia_V1\~\mmf\mmf_cli>python run.py --datasets TextVQA --model lorra --config \configs/vqa/textvqa/lorra.yaml
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from mmf.common.registry import registry
ModuleNotFoundError: No module named 'mmf.common'

**Comment by vedanuj** [comment]
Duplicate of #744

**Comment by sandeepmte** [comment]
[learnpythia-readthedocs-io-en-latest.pdf](https://github.com/facebookresearch/mmf/files/5848124/learnpythia-readthedocs-io-en-latest.pdf)
I am using this pdf documents

**Comment by sandeepmte** [comment]
I try But getting Same Error like this below
(mmf) F:\Pythia_V2\mmf\mmf_cli>python run.py --datasets TextVQA --model lorra --config \configs/vqa/textvqa/lorra.yaml
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from mmf.common.registry import registry
ModuleNotFoundError: No module named 'mmf.common'
