### ISSUE TITLE
git clone https://github.com/facebookresearch/mmf.git

### ISSUE THREAD

**Issue by sandeepmte** [facebookresearch/mmf#744]
## 🐛 Bug
I am using above link to run mmf into my system for vqa (Visual questioning Answering) but i faced below error.
(vqa_v1) F:\Pythia_V1\~\mmf\mmf_cli>python run.py --datasets TextVQA --model lorra --config \configs/vqa/textvqa/lorra.yaml
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from mmf.common.registry import registry
ModuleNotFoundError: No module named 'mmf.common'

**Comment by vedanuj** [comment]
Can you please follow the Issue template for raising Bugs?

**Comment by sandeepmte** [comment]
[learnpythia-readthedocs-io-en-latest.pdf](https://github.com/facebookresearch/mmf/files/5848901/learnpythia-readthedocs-io-en-latest.pdf)

i am follow above pdf
