### ISSUE TITLE
Refer Expression for vilbert

### ISSUE THREAD

**Issue by prashan** [facebookresearch/mmf#745]
## ❓ Questions and Help
Is there a way to run train/eval for vilbert for the Refer Expression task? 
In the original code repo(https://github.com/jiasenlu/vilbert_beta) it could be done by the below command 

```
Train -> (--tasks 4 means 'Refer Expression')
python -m torch.distributed.launch --nproc_per_node=8 --nnodes=1 --node_rank=0 train_tasks.py --bert_model bert-base-uncased --from_pretrained save/bert_base_6_layer_6_connect_freeze_0/pytorch_model_8.bin  --config_file config/bert_base_6layer_6conect.json  --learning_rate 4e-5 --num_workers 16 --tasks 4 --save_name pretrained

Eval -> Under RefCOCO+(--tasks 4 means 'Refer Expression')
python eval_tasks.py --bert_model bert-base-uncased --from_pretrained save/refcoco+_bert_base_6layer_6conect-pretrained/pytorch_model_19.bin --config_file config/bert_base_6layer_6conect.json --task 4
```

can these 2 operations be done using the mmf repo? If so whats the command for that? or should I simply use the old vilbert_beta repo?

**Comment by ytsheng** [comment]
Hi @prashan, thanks for using mmf!

As far as I know, we currently do not have Refer Expression datasets implemented within mmf yet. You can submit a PR to integrate it if you want! We are happy to give it a review. As far as Vilbert, you can use it with some of our other datasets (conceptual caption and coco for example).

**Comment by prashan** [comment]
ok Thanks for your prompt reply. For vilbert Refer Expressions the data/code seems to exist in https://github.com/jiasenlu/vilbert_beta/tree/master/data branch. It seems like it's a matter of porting it over.
Meanwhile i ll try the other datasets(e.g conceptual captions, coco)  you mentioned.

**Comment by vedanuj** [comment]
@prashan PRs are welcome if you want to add the Refer Expression support to MMF. One issue is the Refer Expression repo is still using Python 2 and will need to be updated.
