### ISSUE TITLE
mmf trainer loading datasets hangs with any more than 2 gpus

### ISSUE THREAD

**Issue by g-luo** [facebookresearch/mmf#756]
## ❓ Questions and Help

Hello! I notice that any time I try running mmf with more than 2 gpus, mmf.trainers.mmf_trainer always hangs. Please note that my configs are identical (scaling batch size); the only difference is the number of gpus I make visible via `export CUDA_VISIBLE_DEVICES`. It always hangs at this point:

```
[32m2021-01-29T00:44:18 | mmf.utils.env: [0mImporting from /home/g-luo/remote_home/foil_mmf
[32m2021-01-29T00:44:19 | mmf.utils.configuration: [0mOverriding option config to ./configs/experiments/visualBERT/foil_visualBERT_pretrain.yaml
[32m2021-01-29T00:44:19 | mmf.utils.configuration: [0mOverriding option model to visual_bert_foil
[32m2021-01-29T00:44:19 | mmf.utils.configuration: [0mOverriding option datasets to masked_object
[32m2021-01-29T00:44:19 | mmf.utils.configuration: [0mOverriding option run_type to train
[32m2021-01-29T00:44:19 | mmf.utils.configuration: [0mOverriding option checkpoint.resume_pretrained to False
/home/g-luo/anaconda3/envs/mmf/lib/python3.7/site-packages/omegaconf/dictconfig.py:252: UserWarning: Keys with dot (model.bert) are deprecated and will have different semantic meaning the next major version of OmegaConf (2.1)
See the compact keys issue for more details: https://github.com/omry/omegaconf/issues/152
You can disable this warning by setting the environment variable OC_DISABLE_DOT_ACCESS_WARNING=1
  warnings.warn(message=msg, category=UserWarning)
/home/g-luo/anaconda3/envs/mmf/lib/python3.7/site-packages/omegaconf/dictconfig.py:252: UserWarning: Keys with dot (model.bert) are deprecated and will have different semantic meaning the next major version of OmegaConf (2.1)
See the compact keys issue for more details: https://github.com/omry/omegaconf/issues/152
You can disable this warning by setting the environment variable OC_DISABLE_DOT_ACCESS_WARNING=1
  warnings.warn(message=msg, category=UserWarning)
[32m2021-01-29T00:44:20 | mmf.utils.env: [0mImporting from /home/g-luo/remote_home/foil_mmf
[32m2021-01-29T00:44:21 | mmf.utils.env: [0mImporting from /home/g-luo/remote_home/foil_mmf
[32m2021-01-29T00:44:21 | mmf.utils.env: [0mImporting from /home/g-luo/remote_home/foil_mmf
[32m2021-01-29T00:44:21 | mmf.utils.env: [0mImporting from /home/g-luo/remote_home/foil_mmf
[32m2021-01-29T00:44:21 | mmf.utils.distributed: [0mDistributed Init (Rank 1): tcp://localhost:13613
[32m2021-01-29T00:44:21 | mmf.utils.distributed: [0mDistributed Init (Rank 0): tcp://localhost:13613
[32m2021-01-29T00:44:21 | mmf.utils.distributed: [0mDistributed Init (Rank 3): tcp://localhost:13613
[32m2021-01-29T00:44:21 | mmf.utils.distributed: [0mInitialized Host scylla as Rank 3
[32m2021-01-29T00:44:21 | mmf.utils.distributed: [0mDistributed Init (Rank 2): tcp://localhost:13613
[32m2021-01-29T00:44:21 | mmf.utils.distributed: [0mInitialized Host scylla as Rank 2
[32m2021-01-29T00:44:22 | mmf.utils.distributed: [0mInitialized Host scylla as Rank 1
[32m2021-01-29T00:44:22 | mmf.utils.distributed: [0mInitialized Host scylla as Rank 0
[32m2021-01-29T00:44:24 | mmf: [0mLogging to: ./foil_visualBERT_pretrain_cc/train.log
[32m2021-01-29T00:44:24 | mmf_cli.run: [0mNamespace(config_override=None, local_rank=None, opts=['config=./configs/experiments/visualBERT/foil_visualBERT_pretrain.yaml', 'model=visual_bert_foil', 'dataset=masked_object', 'run_type=train', 'checkpoint.resume_pretrained=False'])
[32m2021-01-29T00:44:24 | mmf_cli.run: [0mTorch version: 1.6.0
[32m2021-01-29T00:44:24 | mmf.utils.general: [0mCUDA Device 0 is: GeForce GTX TITAN X
[32m2021-01-29T00:44:24 | mmf_cli.run: [0mUsing seed 2
[32m2021-01-29T00:44:24 | mmf.trainers.mmf_trainer: [0mLoading datasets
```

**Comment by g-luo** [comment]
Resolved. It was my installed version of torch (1.7.0+cu101); reverting to torch1.6.0 fixed it.

**Comment by vedanuj** [comment]
Please share the command you used and also please paste the error that you get if you interrupt the hanged state.

**Comment by g-luo** [comment]
MMF_USER_DIR="." nohup mmf_run config="./configs/experiments/foil_oscar.yaml" model=oscar dataset=foil run_type=train checkpoint.resume_pretrained=True > tamperednews_oscar_soft_attention_lr5e-5_x1e-2_n12.out &

Traceback if interrupted:
```
[32m2021-02-01T22:44:08 | mmf.utils.env: [0mImporting from /home/g-luo/remote_home/foil_mmf
[32m2021-02-01T22:44:09 | mmf.utils.configuration: [0mOverriding option config to ./configs/experiments/foil_oscar.yaml
[32m2021-02-01T22:44:09 | mmf.utils.configuration: [0mOverriding option model to oscar
[32m2021-02-01T22:44:09 | mmf.utils.configuration: [0mOverriding option datasets to foil
[32m2021-02-01T22:44:09 | mmf.utils.configuration: [0mOverriding option run_type to train
[32m2021-02-01T22:44:09 | mmf.utils.configuration: [0mOverriding option checkpoint.resume_pretrained to True
/home/g-luo/remote_home/mmf/mmf/utils/configuration.py:307: UserWarning: Model oscar's class has no default configuration provided
  warnings.warn(warning)
[32m2021-02-01T22:44:11 | mmf.utils.env: [0mImporting from /home/g-luo/remote_home/foil_mmf
[32m2021-02-01T22:44:11 | mmf.utils.env: [0mImporting from /home/g-luo/remote_home/foil_mmf
[32m2021-02-01T22:44:11 | mmf.utils.distributed: [0mDistributed Init (Rank 0): tcp://localhost:15090
[32m2021-02-01T22:44:11 | mmf.utils.distributed: [0mDistributed Init (Rank 1): tcp://localhost:15090
[32m2021-02-01T22:44:11 | mmf.utils.distributed: [0mInitialized Host scylla as Rank 1
[32m2021-02-01T22:44:11 | mmf.utils.distributed: [0mInitialized Host scylla as Rank 0
[32m2021-02-01T22:44:14 | mmf: [0mLogging to: ./tamperednews_oscar_soft_attention_lr5e-5_x1e-2_n12/train.log
[32m2021-02-01T22:44:14 | mmf_cli.run: [0mNamespace(config_override=None, local_rank=None, opts=['config=./configs/experiments/foil_oscar.yaml', 'model=oscar', 'dataset=foil', 'run_type=train', 'checkpoint.resume_pretrained=True'])
[32m2021-02-01T22:44:14 | mmf_cli.run: [0mTorch version: 1.6.0
[32m2021-02-01T22:44:14 | mmf.utils.general: [0mCUDA Device 0 is: GeForce GTX TITAN X
[32m2021-02-01T22:44:14 | mmf_cli.run: [0mUsing seed 2
[32m2021-02-01T22:44:14 | mmf.trainers.mmf_trainer: [0mLoading datasets
Traceback (most recent call last):
  File "/home/g-luo/anaconda3/envs/mmf/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/g-luo/remote_home/mmf/mmf_cli/run.py", line 118, in run
    nprocs=config.distributed.world_size,
  File "/home/g-luo/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/g-luo/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/g-luo/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGTERM

```

**Comment by g-luo** [comment]
I also notice that this can happen with two GPUs as well, but is resolved when I switch to a different combination of GPUs (ie of 1,2 doesn't work 2,3 will). I wonder if this is a race condition happening somewhere or if it's specific to my hardware.

Thanks for looking into this!

**Comment by vedanuj** [comment]
I have tried this on my end but haven't been able to reproduce this. Is there any way you can check if all your GPUs are healthy? It will also be helpful if you can provide us how to reproduce this with any of the existing mmf model/datasets.

**Comment by apsdehal** [comment]
This was one of the issues that was fixed 2-3 months back in user dir revamp based on issues from @g-luo and Disney. Make sure to rebase your existing MMF with master so that you have latest changes.

**Comment by Ifrahmaqsood** [comment]
I am facing similar issue. when I train my MCAN model with **2 GPUs** it gets stuck on **Loading Datasets**



Here is the result of my **nvidia-smi** command
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:0A:00.0 Off |                    0 |
| N/A   76C    P0    83W / 149W |   4463MiB / 11441MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:0B:00.0 Off |                    0 |
| N/A   54C    P0    92W / 149W |   1210MiB / 11441MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     25847      C   ...ahmaqsood/anaconda3/envs/mmf/bin/python   375MiB |
|    1     25848      C   ...ahmaqsood/anaconda3/envs/mmf/bin/python   375MiB |





**My training command**

(mmf) $ **mmf_run config=projects/movie_mcan/configs/vqa2/defaults.yaml \model=movie_mcan \dataset=vqa2 \run_type=train**
2021-02-09T23:18:58 | mmf.utils.configuration: Overriding option config to projects/movie_mcan/configs/vqa2/defaults.yaml
2021-02-09T23:18:58 | mmf.utils.configuration: Overriding option model to movie_mcan
2021-02-09T23:18:58 | mmf.utils.configuration: Overriding option datasets to vqa2
2021-02-09T23:18:58 | mmf.utils.configuration: Overriding option run_type to train
2021-02-09T23:18:59 | mmf.utils.distributed: Distributed Init (Rank 0): tcp://localhost:14346
2021-02-09T23:18:59 | mmf.utils.distributed: Distributed Init (Rank 1): tcp://localhost:14346
2021-02-09T23:18:59 | mmf.utils.distributed: Initialized Host 127.0.0.1localhost.localdomainlocalhost as Rank 1
2021-02-09T23:18:59 | mmf.utils.distributed: Initialized Host 127.0.0.1localhost.localdomainlocalhost as Rank 0
2021-02-09T23:19:12 | mmf: Logging to: ./save/train.log
2021-02-09T23:19:12 | mmf_cli.run: Namespace(config_override=None, local_rank=None, opts=['config=projects/movie_mcan/configs/vqa2/defaults.yaml', 'model=movie_mcan', 'dataset=vqa2', 'run_type=train'])
2021-02-09T23:19:12 | mmf_cli.run: Torch version: 1.6.0+cu101
2021-02-09T23:19:12 | mmf.utils.general: CUDA Device 0 is: Tesla K80
2021-02-09T23:19:12 | mmf_cli.run: Using seed 12039967
**2021-02-09T23:19:12 | mmf.trainers.mmf_trainer: Loading datasets**

**Comment by g-luo** [comment]
@Ifrahmaqsood I wonder if it's because your PyTorch version is 1.6.0+cu101, as the default mmf installation should be torch==1.6.0. I was also having similar dataloading issues with pytorch 1.7.1+cu101 that resolved when I reverted back to torch==1.6.0

**Comment by Ifrahmaqsood** [comment]
That you @g-luo . My question is, if I go back to torch==1.6 without cuda, then how can I use cuda with pytorch 10.1? I installed it due to cuda dependency

**Comment by g-luo** [comment]
@apsdehal I am currently already running the latest version of mmf (ie installed using the git repo). @vedanuj I believe all my GPUs are healthy as mmf works when training on them individually (vs the issue arises when training on multiple gpus at once). 

This could possibly be because I am using a custom dataset, I'll update this issue as I poke around.

**Comment by g-luo** [comment]
@Ifrahmaqsood MMF should be able to run on your gpus with torch==1.6.0; if you want to have cu101 installed I think @apsdehal or @vedanuj would have a better answer.

**Comment by g-luo** [comment]
Resolved by https://github.com/facebookresearch/mmf/issues/772, ie changing backend from nccl to gloo.
