### ISSUE TITLE
[enhancement] Upgrade to PyTorch 1.2.0

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/mmf#76]
There are some issues related to `flatten_parameters` that are currently preventing this upgrade. I am looking into this.

**Comment by apsdehal** [comment]
Blocked by https://github.com/pytorch/pytorch/issues/21108 for now.

**Comment by vedanuj** [comment]
Pytorch 1.2 Stable is released today. We can update pythia to use 1.2 now. I have been testing with 1.2 nightly and haven't found any issues till now.

**Comment by apsdehal** [comment]
Yup, I have been actually working on this and a lot of other relevant fixes.

**Comment by apsdehal** [comment]
Related https://github.com/pytorch/pytorch/issues/24137

**Comment by vedanuj** [comment]
Upgrade next to Pytorch 1.4
