### ISSUE TITLE
Butd Performance Using Coco Dataset Features

### ISSUE THREAD

**Issue by mnbv7581** [facebookresearch/mmf#763]
## ❓ Questions and Help

We extracted coco dataset features and learned butd with RCNN model that learned coco dataset rather than vg dataset, but the performance is not good. Can I know what parts I need to check?
The current bleu4 score is 0.1157.

**Comment by vedanuj** [comment]
BUTD model uses a Faster RCNN model that is trained with Visual Genome attributes. This was show to improve performance a lot [here](https://arxiv.org/abs/1707.07998). If you are using a COCO trained RCNN model, have you trained the BUTD model with your new features?

**Comment by mnbv7581** [comment]
@vedanuj Yes, I trained with new functions.
