### ISSUE TITLE
Can I train mcan model with  torch==1.4.0+cu100 and torchvision==0.5.0+cu100

### ISSUE THREAD

**Issue by Ifrahmaqsood** [facebookresearch/mmf#765]
## ❓ Questions and Help
I have cuda 10.0 installed on my tesla server which I cannot change due to other members working on same server and due to this version i can only work with **torch==1.4.0+cu100 and torchvision==0.5.0+cu100** if I want to use cuda. Also, it gives an error **DistributionNotFound: The 'torchvision==0.7.0' distribution was not found and is required by mmf** when training with these versions.

However when I install MMF from source, it automatically installs torch version 1.6 and torchvision 0.7 which is not compatible with my **cuda 10.0** . So, it shifts to **CPU** version.

Please suggest should I train my model with CPU or what else could be an option?

Right now my environments looks like this
**python -m torch.utils.collect_env**

Collecting environment information...
PyTorch version: 1.4.0+cu100
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Ubuntu 16.04.7 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
CMake version: version 3.18.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80

Nvidia driver version: 430.64
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.2

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.4.0+cu100
[pip3] torchtext==0.5.0
[pip3] torchvision==0.5.0+cu100
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py36he8ac12f_0
[conda] mkl_fft                   1.2.0            py36h23d657b_0
[conda] mkl_random                1.1.1            py36h0573a6f_0
[conda] torch                     1.4.0+cu100              pypi_0    pypi
[conda] torchtext                 0.5.0                    pypi_0    pypi
[conda] torchvision               0.5.0+cu100              pypi_0    pypi

**Comment by apsdehal** [comment]
Hi @Ifrahmaqsood,

Yes, you can try doing this. Please clone from scratch and update requirements.txt to adjust to your environment if you can't pip install directly. You can also install right version of torch and torchvision for your CUDA version by adding proper version at the end. PyTorch does have 10.1 versions for 1.4. Do this before installing MMF.

Let me know if this doesn't work.

**Comment by Ifrahmaqsood** [comment]
Thank You. The version dependency issue has been resolved.
