### ISSUE TITLE
Multi Sentence BERT Tokenizer

### ISSUE THREAD

**Issue by g-luo** [facebookresearch/mmf#773]
## ❓ Questions and Help

Hello, I was trying to use the multi sentence BERT tokenizer in [bert_processors.py](https://github.com/facebookresearch/mmf/blob/2ff00626ec2bc6b56a543da0dc2869c548e81fec/mmf/datasets/processors/bert_processors.py#L176). I was wondering if the HuggingFace versions of BERT do not support 3+ segment ids, since when I tried using this as an input to the unimodal_text and visual_bert models I got errors such as `CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`` and nan errors in my losses respectively. Additionally, I was wondering if there was an example where someone was able to use 3+ segment ids for their sentences. 

Thanks fo much for your help!

**Comment by ytsheng** [comment]
Hi @g-luo, thanks for using mmf!

I believe we only support 3+ segment ids for models such as `mmf_transformer`. @vedanuj added mmf_transformer to support multimodality [here](https://github.com/facebookresearch/mmf/commit/31f0cc195ba25f69dd58fee6f9c714e7cd7418a1)

Perhaps he could share more. :)

**Comment by g-luo** [comment]
Thanks so much! Does this model preserve the fact that the sentences are distinct and have different segment ids? It seems that the model is summing the embeddings for all the sentences, but not sure where the segment ids are used.

**Comment by ytsheng** [comment]
Are you hoping to concat the sentences together after assigning them different segment IDs? In terms of how to process the input data to model input, the logic resides in processors. For text, it is in [bert_processor.py](https://github.com/facebookresearch/mmf/blob/master/mmf/datasets/processors/bert_processors.py#L177), specifically, please take a look at our `MultiSentenceTokenizer`. You can specify the `fusion_type` in the config to be either concat or stack.

**Comment by g-luo** [comment]
I think on a higher level, I want the transformer to understand that the embeddings are for different segment id types (eg if I am taking the concat of three sentences, each sentence comes from a different distribution). I just wanted to see if this implementation of mmf_transformer accounts for that?

**Comment by vedanuj** [comment]
@g-luo As @ytsheng mentioned, if you can choose to either **concat** the sentences or **stack** the sentences. If **concat** option is chosen then all the sentences are considered from the same source and hence are assigned same segment embedding. If **stack** option is chosen the each sentence has its own position and segment embeddings and the model considers they are from different distribution.

**Comment by g-luo** [comment]
Gotcha; thank you!
