### ISSUE TITLE
Error in Training the M4C Model

### ISSUE THREAD

**Issue by rseraj** [facebookresearch/mmf#777]
## ❓ Questions and Help

1. **Environment:**

python: 3.7.4
pytorch Version: 1.6.0+cu101
CUDA Version: 10.2
 GPU: GeForce GTX 1650 ,4 GPUs

C:\Users\mmf>nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 441.93           Driver Version: 441.93             CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name                 TCC/WDDM | Bus-Id                          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|                  Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1650   WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   36C    P8     5W /  N/A |    134MiB /  4096MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

2. **problem:**
Facing this issue while training the M4C Model
mmf_run config=projects/m4c/configs/textvqa/defaults.yaml :

 C:\Users\mmf>mmf_run config=projects/m4c/configs/textvqa/defaults.yaml
2021-02-14 19:45:05.943514: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
c:\users\mmf\mmf\utils\configuration.py:536: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.
  "Device specified is 'cuda' but cuda is not present. "
Traceback (most recent call last):
  File "c:\python\Anaconda3\Scripts\mmf_run-script.py", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "c:\users\mmf\mmf_cli\run.py", line 91, in run
    configuration = Configuration(args)
  File "c:\users\mmf\mmf\utils\configuration.py", line 220, in __init__
    other_configs = self._build_other_configs()
  File "c:\users\mmf\mmf\utils\configuration.py", line 248, in _build_other_configs
    model_config = self._build_model_config(opts_config)
  File "c:\users\mmf\mmf\utils\configuration.py", line 293, in _build_model_config
    raise KeyError("Required argument 'model' not passed")
KeyError: "Required argument 'model' not passed"

 

@apsdehal 
@ytsheng
Can you please help me with this?

**Comment by ytsheng** [comment]
Hi @Rey74, thanks for using mmf!

Do you mind sharing the full command that you are using? Typically in the `mmf_run` command, we need to pass in the `model` and `dataset` arguments. What you shared `mmf_run config=projects/m4c/configs/textvqa/defaults.yaml` did not have either the `model` nor the `dataset` argument so the code  is just asking you to provide the model you want to use. If you want to use the m4c model, you can specify `model=m4c`, but you'd also need to specify a dataset you wish to use the m4c model on. 

The document about mmf is [here](https://mmf.sh/). Let us know if you have more questions!
