### ISSUE TITLE
Visual question answering

### ISSUE THREAD

**Issue by MiriamFarber** [facebookresearch/mmf#802]
Is there a module in this repository that I can use that gets as an input question and image, and generates an answer as an output?
If not, are there any modules that have the generic structure of receiving image and text as an input, and generating another text as an output?

**Comment by ytsheng** [comment]
Hi @MiriamFarber,

Are you asking if there is a decoder built in that generates texts? People do use `mmf` for VQA, but they use it in a form of multiple choice.
