### ISSUE TITLE
Hardware requirements for Movie_Mcan

### ISSUE THREAD

**Issue by Ifrahmaqsood** [facebookresearch/mmf#803]
## ❓ Questions and Help
Can you please let me know what are the least **Hardware requirements**  for Movie_Mcan model?

Like,
Gpu memory, RAM and Disk space?

**Comment by Ifrahmaqsood** [comment]
@ytsheng I'm using **Coco dataset**. I have 1 GPU with 11 gb memory, RAM of 16 gb and 500gb disk space for training but it keep saying CUDA OUT OF MEMORY even at a **4 batch size**. I'm not sure if it's the RAM issue or the GPU memory

**Comment by vedanuj** [comment]
@Ifrahmaqsood You can use the training.update_frequency feature to accumulate gradients and have an effective batch size of 64 that MovieMcan uses.

**Comment by Ifrahmaqsood** [comment]
@vedanuj thank you for your response
