### ISSUE TITLE
warning while starting training or resuming it from checkpoint

### ISSUE THREAD

**Issue by Ifrahmaqsood** [facebookresearch/mmf#811]
## ❓ Questions and Help
Hi, I am working with **movie_mcan** model. Can you tell me, why does it give such warning. I didn't change anything in the code that could possibly bring this warning.

**When I start or resume training from checkpoint, it shows**

2021-03-12T01:58:18 | mmf.utils.checkpoint: Loading checkpoint
WARNING 2021-03-12T01:58:51 | mmf: Key data_parallel is not present in registry, returning default value of None
WARNING 2021-03-12T01:58:51 | mmf: Key distributed is not present in registry, returning default value of None
WARNING 2021-03-12T01:58:51 | py.warnings: /home/mmf-master/mmf/utils/distributed.py:272: UserWarning: **Please also save or load the state of the optimzer when saving or loading the scheduler.**
  builtin_warn(*args, **kwargs)

WARNING 2021-03-12T01:58:51 | py.warnings: /home/mmf-master/mmf/utils/distributed.py:272: UserWarning: **Please also save or load the state of the optimzer when saving or loading the scheduler.**
  builtin_warn(*args, **kwargs)

**Comment by vedanuj** [comment]
These warnings can be ignored. If there was any issue in loading the checkpoint you would have got errors.
