### ISSUE TITLE
Reinstallation version issue of MMF codes

### ISSUE THREAD

**Issue by csbobby** [facebookresearch/mmf#824]
## ❓ How to solve the version issue of a new installation on previously modified projects
Hi team,
Is there any way to make my previous MMF projects satisfy the new package requirements (PyTorch 1.6 and torchvision 0.7.0)?
I am moving my previously modified MMF projects to the new cluster. So I reinstalled the modified MMF project codes by the commend: 
`pip install --editable .` 
The installation reported the following error in terms of package version (or requested the PyTorch 1.5.0):
`ERROR: Could not find a version that satisfies the requirement torchvision==0.6.0 (from mmf==1.0.0rc12) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2x.1, 0.2.2, 0.2.2.post2, 0.2.2.post3)` 
`ERROR: No matching distribution found for torchvision==0.6.0 (from mmf==1.0.0rc12)`
The behind reason probably related to the package version limit on my new cluster. It only supports PyTorch 1.6 and torchvision 0.7.0.

**Comment by apsdehal** [comment]
Hi,
You can manually clone and edit the version requirements in requirements.txt and then install MMF to get unblocked. We will look for a better long term solution on our side.
