### ISSUE TITLE
How to get test accuracy for movie_mcan model for vqa2

### ISSUE THREAD

**Issue by Ifrahmaqsood** [facebookresearch/mmf#832]
## ❓ Questions and Help
I have used the pretrained model and run the code on **test split** using

**mmf_predict config=projects/movie_mcan/configs/vqa2/defaults.yaml \
  dataset=vqa2 \
  model=movie_mcan \
  run_type=test \
  checkpoint.resume_zoo=movie_mcan.grid.vqa2_vg**
  
  now I have a file named **vqa2_run_test_2021-03-27T19:53:54.json**
  
  
  How can I get the accuracy on vqa2 with this file. Where to submit this file in order to get the accuracy?

**Comment by vedanuj** [comment]
You will have to submit this to the EvalAI VQA server fo VQA2.0. https://eval.ai/web/challenges/challenge-page/830/submission

**Comment by Ifrahmaqsood** [comment]
Thank you
