### ISSUE TITLE
tools/scripts/features/frcnn/extract_features_frcnn.py

### ISSUE THREAD

**Issue by 1144181135** [facebookresearch/mmf#836]
## ❓ Questions and Help
I try to extract bottom up features in a new dataset. The feature extraction in "mmf/tools/scripts/features/extract_features_vmb.py" is achieved by maskrcnn_benchmark but it shows deprecated. I found that the file "tools/scripts/features/frcnn/extract_features_frcnn.py". Can this file extract bottom-up features? If can, where is the MODEL_URL? If not, how to extract features with detectron2 ?

**Comment by vedanuj** [comment]
Hi .. you can use `tools/scripts/features/frcnn/extract_features_frcnn.py` for extracting features. The script will automatically download the model file and config file from MODEL_URL defined in the script if you don't specify it in the run command.

**Comment by hivestrung** [comment]
The script doesn't actually download the model file and config file from MODEL_URL, but I've been putting together an upgrade that has fixed most of those issues and will upload it in the next week or so.

**Comment by hivestrung** [comment]
@1144181135 Please check out my fork https://github.com/hivestrung/mmf/commit/6332a9803721a9a230913b6e2589fed172ae4778
This commit has code that will most likely solve your problems with using MODEL_URL to download the model
