### ISSUE TITLE
Cannot use mmf/utils/inference.py with existing configs

### ISSUE THREAD

**Issue by junqi-jiang** [facebookresearch/mmf#852]
## 1. Cannot use mmf/utils/inference.py with existing configs

I am doing a project that needs an interface to do inference on random images using vilbert and visual_bert models for the hateful_memes challenge. 

In this pull request https://github.com/facebookresearch/mmf/pull/830 an interface was developed. When I tried to instantiate an Inference object with the pretrained visual_bert checkpoint, there were no such section in the config:

self.model_items["config"].image_feature_encodings,

Could you please provide a copy of the checkpoint config file you used or give some suggestions? 

## [SOLVED] 2. Cannot use extract_features_frcnn.py to get image features

Also, I cannot find the lxmert config required for this file. I have manually downloaded one from huggingface but it was in json. [SOLVED: 
https://s3.amazonaws.com/models.huggingface.co/bert/unc-nlp/frcnn-vg-finetuned/config.yaml

]

Cheers

**Comment by junqi-jiang** [comment]
wrong link, it was this pull request https://github.com/facebookresearch/mmf/pull/798 that did the interface

**Comment by hivestrung** [comment]
Seconded. I'm further along and have gotten extract_features_frcnn to work and return features on an arbitrary file, but even then it is not possible to use those features for inference using visual bert.

**Comment by hivestrung** [comment]
@junqi-jiang I've worked on the code and can solve some of your problems with feature extraction using mine: https://github.com/hivestrung/mmf/commit/6332a9803721a9a230913b6e2589fed172ae4778
I still have issues with actually using the features generated by extract_features_frcnn for creating the sample's image_feature_0 field a la `sample.image_feature_0`. 

@vedanuj Would you be able to help advise how we actually use the features?

**Comment by junqi-jiang** [comment]
@hivestrung Thanks! That's some great work to get the URL working. It seems I have downloaded the wrong file for the config lol.

To do inference you can also look at mmf/models/interfaces/mmbt.py and the from_pretrained( ) function in mmf/models/mmbt.py, I have been using that to interface with models that take images as input and I am extending it to vilbert and visualbert. It's quite convenient.

**Comment by vedanuj** [comment]
cc @brettallenyo  Can you please take a look at this?

**Comment by brettallenyo** [comment]
Hi @hivestrung @junqi-jiang I am going to be uploading some models and configs to our model zoo in the coming days so you will be able to download and use those for the `mmf_transformer` and `visual_bert` checkpoints

**Comment by junqi-jiang** [comment]
@brettallenyo I would really appreciate that! Also, I have written an interface for visual_bert and vilbert to predict on raw images and texts, which has solved this issue another way https://github.com/junqi-jiang/mmf/commit/7f96f5b89ae14442656883ca3922d6a702beb85f.
