### ISSUE TITLE
Unimodal (BERT) output_attentions does nothing?

### ISSUE THREAD

**Issue by hivestrung** [facebookresearch/mmf#859]
## ❓ Questions and Help
I want to access the attention weights for the 12 attention heads in BERT to visualise what text is focused on most in making a hateful classification.

I can't seem to get this data from the model. I'm starting with unimodal and will expand to other models once I get this working. Toggling output_attentions in `mmf/mmf/configs/models/unimodal/bert.yaml` doesn't seem to do anything either.

**Comment by hivestrung** [comment]
Solved: it's because in hf_layers:BertEncoderJit the forward function has been modified to have output_attentions and output_hidden_states set by default to False

The rationale given was:
```
Changes to `forward` function::
        Typed inputs and modifies the output to be of Tuple[Tensor] type in scripting
        mode. Due to different possible types when `output_hidden_states` or
        `output_attentions` are enable, we do not support these in scripting mode
```
Lines such as `if not torch.jit.is_scripting() and output_attentions` are used but they are not very effective. I don't know a thing about scripting, but when I was running in inference mode, this flag was False. Yet the whole forward function wasn't outputting the attentions because the forward function by default set it to False, overriding user preferences set in the config.

I personally disagree with this design decision, because with such an abstracted set of interfaces, it's unlikely that anyone would know to pass that specific argument in, especially when one has already stated output_attentions=True in the config.

Secondly, if the rationale is to prevent Type errors when scripting is enabled, there is no reason to overwrite the user preference - just let the no_scripting flag do its job.

**Comment by hivestrung** [comment]
Another note: you would also need to modify the UnimodalText forward function. Currently it doesn't pass through the attentions and hidden states you would need. One fix that works for me is:

```
def forward(self, sample_list):
        # BERT Based Encoders
        args = []
        if "input_ids" in sample_list:
            text = sample_list.input_ids
            args.append(sample_list.input_mask)
            args.append(sample_list.segment_ids)
        else:
            text = sample_list.text

        embedding, hidden_states, attention_weights = self.base(text, *args)
        output = {}
        output["scores"] = self.classifier(embedding)
        if not self.training:
            output["embedding"] = embedding
            output["hidden_states"] = hidden_states
            output["attention_weights"] = attention_weights
        return output
  ```

@vedanuj if you find that fixing this would be helpful, I can initiate a PR, but I don't know if outsiders are really meant to contribute to this repo, plus I do not have access to Fb build tools to check when a PR has created errors.

**Comment by vedanuj** [comment]
Hi @hivestrung  ... we welcome PRs from everyone. Feel free to push a PR for this and we can help test with FB build tools.
