### ISSUE TITLE
[feature] EvalAI Upload Integration

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/mmf#86]
## 🚀 Feature
We currently have a feature for evalai predict which creates predictions in EvalAI format for VQA and TextVQA challenges. It would be great if we can automatically support this using EvalAI CLI tool. https://github.com/Cloud-CV/evalai-cli

## Motivation

Motivation is just ease of usage. Login once and use it always.

## Pitch

Ideally, a parameters or flag `evalai_upload` should be there which should also upload your predictions.

**Comment by LousyLory** [comment]
Hey the following file will help, I think. I guess the option to select submission phase should be used as a flag in the main code, else everything seems to work. I also think this should be called from `./pythia/trainers/base_trainer.py` line 461. Let me know for issues. 

[evalai_submit.txt](https://github.com/facebookresearch/pythia/files/3321529/evalai_submit.txt)

**Comment by yash-gupta01** [comment]
is this issue still open? If yes then I would like to work on this. I am a beginner in the open-source world and would greatly appreciate if you could help me find my way in this issue.
