### ISSUE TITLE
Transformer version 2.3.0 or 3.4.0

### ISSUE THREAD

**Issue by CCYChongyanChen** [facebookresearch/mmf#862]
## ❓ Questions and Help
Hi, I could run the pythia/vilbert code before with transformers version 2.3.0, but after pulling the latest version,  I got error message like "cannot import name 'RobertaAttention' from 'transformers.modeling_roberta'". I checked  https://github.com/facebookresearch/mmf/pull/666 and changed the transformers version to 3.4.0 and now it complains "pkg_resources.DistributionNotFound: The 'transformers==2.3.0' distribution was not found
"

**Comment by apsdehal** [comment]
Hi,
3.4.0 is the current version. After upgrading transformers, you will need to `pip install -e .` MMF again so that it can pick up new deps.

**Comment by CCYChongyanChen** [comment]
Hi, thanks for the reply! 
I clone it from github source and git pull to get the latest update instead of using pip. What should I do after upgrading transformers version? Thanks!

**Comment by apsdehal** [comment]
As I mentioned, inside MMF folder please do `pip install -e .` so that you install MMF.

**Comment by CCYChongyanChen** [comment]
Thanks that solve the problem!
