### ISSUE TITLE
Any support for multi-class classification problem?

### ISSUE THREAD

**Issue by sallypannn** [facebookresearch/mmf#864]
## ❓ Questions and Help
Hi, 

I am trying to implement mmf on a multi-class classification problem. I can only find flags for multi-label but not multi-class. And I did not find such an example in the given project list. May I know if you could provide a multi-class classification example so I could figure out how to properly modify the configuration files? Thanks!

**Comment by apsdehal** [comment]
Hi @sallypannn,

multi class is supported out of the box. You can set `num_labels` to number of your classes in the models that support it and then use `cross_entropy` loss with it. Visual Entailment is an example of dataset which requires multi class classification and here is an example config with VisualBERT model: https://github.com/facebookresearch/mmf/blob/master/projects/visual_bert/configs/visual_entailment/defaults.yaml

**Comment by apsdehal** [comment]
Closing this as I believe this is resolved. If you have other questions, please open up a new issue.

**Comment by sallypannn** [comment]
> Closing this as I believe this is resolved. If you have other questions, please open up a new issue.

Thanks. Problem solved!
