### ISSUE TITLE
Install GPU for mmf

### ISSUE THREAD

**Issue by dxu312** [facebookresearch/mmf#866]
Following the installation instruction on https://mmf.sh/docs, I got a CPU only mmf environment which does pass tests. I tried to follow the pytorch installation instruction from https://pytorch.org/get-started/locally/ to add cudatoolkit, but the tests did not run after that. Is there a way to install mmf with GPU on windows?

**Comment by apsdehal** [comment]
Hi,
Can you share what exact command you followed to install PyTorch?

Also, please share the output `python -m torch.utils.collect_env`.

**Comment by dxu312** [comment]
Yes, I used "conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge" to install pytorch with cuda which worked for me before. This ran successfully but obviously the versions of pytorch/torchvision wouldn't comply to mmf default. I wnder if the tests didn't run due to version conflicts. However if I modify the command with specific versions such as "pytorch=1.8.1" and "torchtext=0.5.0", it can't run.
I've reset my system and now am trying to install mmf in WSL ubuntu rather than in windows directly, so I don't have the output of the old installation. I'd appreciate if you can let me know what command to have mmf to recognize GPU. I followed the installation instruction on https://mmf.sh/docs this time again and passed the tests now, only that it's still a CPU version.

**Comment by dxu312** [comment]
Solved by installing previous pytorch version to avoid conflicts with MMF default setting
