### ISSUE TITLE
[enhancement] Add an light config

### ISSUE THREAD

**Issue by wesfox** [facebookresearch/mmf#87]
## 🚀 Feature

Add a light config

## Motivation

I'm trying to use this awesome framework to see how easy it is to build things on top of Pythia. The big issue that I'm struggling with is understanding the configurations available. To move forward, I decided to create by myself a simple config based on the base config [provided](https://github.com/facebookresearch/pythia/blob/master/pythia/common/defaults/configs/base.yml) without any link to the Pythia model itself.
What do you think about adding a light and straightforward configuration?
This would significantly help interested people to get a better understanding of how this framework works.

## Pitch

Add an easy to understand, lightweight, ready to use config.

## Alternatives

The base config is a good start but needs a lot of work and a heavy understanding process to get usability from it.

**Comment by apsdehal** [comment]
I believe by adding a tutorial on how to add new dataset and a new model to Pythia should resolve this concern. Most of the configuration parameters which you don't need to use you can ignore safely. I will update the issue when I update the documentation for the same.

**Comment by wesfox** [comment]
Great idea! When do you plan to do so?
As I said I'm working on it for personal and business purposes. I can send you my feedbacks on my understanding of Pythia, would you be interested?

**Comment by apsdehal** [comment]
Yup, sure. 

I plan to update the documentation by Monday.

**Comment by mandliya** [comment]
@apsdehal Thank you so much! Appreciate it. I had tough time to plug in another model to Pythia. I was trying to get use a different OCR for TextVQA and see if it improves accuracy. A tutorial like that would be super helpful!
