### ISSUE TITLE
New install - pytest .\tests\trainers\lightning\test_loss.py fails

### ISSUE THREAD

**Issue by skakar-git** [facebookresearch/mmf#876]
## ❓ Questions and Help
**Environment**
`PyTorch version: 1.8.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Education
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] pytorch-lightning==1.2.7
[pip3] torch==1.8.1+cpu
[pip3] torchaudio==0.8.1
[pip3] torchmetrics==0.2.0
[pip3] torchtext==0.5.0
[pip3] torchvision==0.9.1+cpu
[conda] numpy                     1.20.2                   pypi_0    pypi
[conda] pytorch-lightning         1.2.7                    pypi_0    pypi
[conda] torch                     1.8.1+cpu                pypi_0    pypi
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchmetrics              0.2.0                    pypi_0    pypi
[conda] torchtext                 0.5.0                    pypi_0    pypi
[conda] torchvision               0.9.1+cpu                pypi_0    pypi`

I installed mmf from source on my Windows 10 machine and ran `pytest .\tests\`. All tests but one passed. I would appreciate any help with this. The one that fails is `pytest .\test\trainers\lightening\test_loss.py` with the following stdout:

`================================================= test session starts =================================================
platform win32 -- Python 3.7.10, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: C:\Users\xxxx\DLProject\mmf
collected 1 item

tests\trainers\lightning\test_loss.py F                                                                          [100%]

====================================================== FAILURES =======================================================
_______________________ TestLightningTrainerLoss.test_loss_computation_parity_with_mmf_trainer ________________________

self = <tests.trainers.lightning.test_loss.TestLightningTrainerLoss testMethod=test_loss_computation_parity_with_mmf_trainer>

    def test_loss_computation_parity_with_mmf_trainer(self):
        # compute mmf_trainer training losses
        def _on_update_end(report, meter, should_log):
            self.mmf_losses.append(report["losses"]["loss"].item())

        mmf_trainer = get_mmf_trainer(
            max_updates=5, max_epochs=None, on_update_end_fn=_on_update_end
        )
        mmf_trainer.evaluation_loop = MagicMock(return_value=(None, None))
        mmf_trainer.training_loop()

        # compute lightning_trainer training losses
        trainer = get_lightning_trainer(callback=self, max_steps=5)
>       trainer.trainer.fit(trainer.model, trainer.data_module.train_loader)

tests\trainers\lightning\test_loss.py:29:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\anaconda3\envs\mmf\lib\site-packages\pytorch_lightning\trainer\trainer.py:499: in fit
    self.dispatch()
..\..\anaconda3\envs\mmf\lib\site-packages\pytorch_lightning\trainer\trainer.py:546: in dispatch
    self.accelerator.start_training(self)
..\..\anaconda3\envs\mmf\lib\site-packages\pytorch_lightning\accelerators\accelerator.py:73: in start_training
    self.training_type_plugin.start_training(trainer)
..\..\anaconda3\envs\mmf\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py:114: in start_training
    self._results = trainer.run_train()
..\..\anaconda3\envs\mmf\lib\site-packages\pytorch_lightning\trainer\trainer.py:637: in run_train
    self.train_loop.run_training_epoch()
..\..\anaconda3\envs\mmf\lib\site-packages\pytorch_lightning\trainer\training_loop.py:505: in run_training_epoch
    self.on_train_batch_end(epoch_output, batch_end_outputs, batch, batch_idx, dataloader_idx)
..\..\anaconda3\envs\mmf\lib\site-packages\pytorch_lightning\trainer\training_loop.py:207: in on_train_batch_end
    self.trainer.call_hook('on_train_batch_end', batch_end_outputs, batch, batch_idx, dataloader_idx)
..\..\anaconda3\envs\mmf\lib\site-packages\pytorch_lightning\trainer\trainer.py:1091: in call_hook
    trainer_hook(*args, **kwargs)
..\..\anaconda3\envs\mmf\lib\site-packages\pytorch_lightning\trainer\callback_hook.py:155: in on_train_batch_end
    callback.on_train_batch_end(self, self.lightning_module, outputs, batch, batch_idx, dataloader_idx)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.trainers.lightning.test_loss.TestLightningTrainerLoss testMethod=test_loss_computation_parity_with_mmf_trainer>
trainer = <pytorch_lightning.trainer.trainer.Trainer object at 0x000001B7EB70B9C8>
pl_module = SimpleLightningModel(
  (classifier): Linear(in_features=1, out_features=1, bias=True)
)
outputs = [[{'extra': {'losses': {'loss': tensor(0.0566, grad_fn=<MseLossBackward>)}, 'logits': tensor([[-0.2380]], grad_fn=<Add...List([('test', tensor([[0.]])), ('dataset_name', 'simple'), ('dataset_type', 'train')])}, 'minimize': tensor(0.0566)}]]
batch = SampleList([('test', tensor([[0.]])), ('dataset_name', 'simple'), ('dataset_type', 'train')]), batch_idx = 0
dataloader_idx = 0

    def on_train_batch_end(
        self, trainer, pl_module, outputs, batch, batch_idx, dataloader_idx
    ):
>       report = Report(outputs["input_batch"], outputs)
E       TypeError: list indices must be integers or slices, not str

tests\trainers\lightning\test_loss.py:34: TypeError
------------------------------------------------ Captured stdout call -------------------------------------------------
Epoch 0:   0%|          | 0/100 [00:05<?, ?it/s]
-------------------------------------------------- Captured log call --------------------------------------------------
INFO     pytorch_lightning.utilities.distributed:distributed.py:56 GPU available: False, used: False
INFO     pytorch_lightning.utilities.distributed:distributed.py:56 TPU available: False, using: 0 TPU cores
INFO     pytorch_lightning.core.lightning:lightning.py:1463
  | Name       | Type   | Params
--------------------------------------
0 | classifier | Linear | 2
--------------------------------------
2         Trainable params
0         Non-trainable params
2         Total params
0.000     Total estimated model params size (MB)
================================================== warnings summary ===================================================
..\..\anaconda3\envs\mmf\lib\site-packages\fsspec\__init__.py:47
  c:\users\xxxx\anaconda3\envs\mmf\lib\site-packages\fsspec\__init__.py:47: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
    for spec in entry_points.get("fsspec.specs", []):

..\..\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:572
  c:\users\xxxx\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:572: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    (np.object, string),

..\..\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:573
  c:\users\xxxx\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:573: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    (np.bool, bool),

..\..\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:597
  c:\users\xxxx\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:597: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    types_pb2.DT_STRING: np.object,

..\..\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:601
  c:\users\xxxx\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:601: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    types_pb2.DT_BOOL: np.bool,

..\..\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:618
  c:\users\xxxx\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:618: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    types_pb2.DT_STRING_REF: np.object,

..\..\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:623
  c:\users\xxxx\anaconda3\envs\mmf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:623: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    types_pb2.DT_BOOL_REF: np.bool,

..\..\anaconda3\envs\mmf\lib\site-packages\tensorboard\util\tensor_util.py:113
  c:\users\xxxx\anaconda3\envs\mmf\lib\site-packages\tensorboard\util\tensor_util.py:113: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.object: SlowAppendObjectArrayToTensorProto,

..\..\anaconda3\envs\mmf\lib\site-packages\tensorboard\util\tensor_util.py:114
  c:\users\xxxx\anaconda3\envs\mmf\lib\site-packages\tensorboard\util\tensor_util.py:114: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.bool: SlowAppendBoolArrayToTensorProto,

..\..\anaconda3\envs\mmf\lib\site-packages\transformers\modeling_deberta.py:18
  c:\users\xxxx\anaconda3\envs\mmf\lib\site-packages\transformers\modeling_deberta.py:18: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Sequence

tests/trainers/lightning/test_loss.py::TestLightningTrainerLoss::test_loss_computation_parity_with_mmf_trainer
  C:\Users\xxxx\DLProject\mmf\mmf\datasets\multi_datamodule.py:63: UserWarning: 'multitasking' config not defined. Disabling any form of multitasking
    "'multitasking' config not defined. Disabling any form of multitasking"

tests/trainers/lightning/test_loss.py::TestLightningTrainerLoss::test_loss_computation_parity_with_mmf_trainer
  C:\Users\xxxx\DLProject\mmf\mmf\common\sample.py:427: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    if isinstance(sample_list, collections.Mapping):

tests/trainers/lightning/test_loss.py::TestLightningTrainerLoss::test_loss_computation_parity_with_mmf_trainer
  C:\Users\xxxx\DLProject\mmf\mmf\models\base_model.py:250: UserWarning: 'losses' already present in model output. No calculation will be done in base model.
    "'losses' already present in model output. "

tests/trainers/lightning/test_loss.py::TestLightningTrainerLoss::test_loss_computation_parity_with_mmf_trainer
  C:\Users\xxxx\DLProject\mmf\mmf\common\report.py:101: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    if isinstance(self[key], collections.MutableSequence):

tests/trainers/lightning/test_loss.py::TestLightningTrainerLoss::test_loss_computation_parity_with_mmf_trainer
  c:\users\xxxx\anaconda3\envs\mmf\lib\site-packages\pytorch_lightning\utilities\distributed.py:52: UserWarning: you defined a validation_step but have no val_dataloader. Skipping validation loop
    warnings.warn(*args, **kwargs)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================================== short test summary info ===============================================
FAILED tests/trainers/lightning/test_loss.py::TestLightningTrainerLoss::test_loss_computation_parity_with_mmf_trainer
=========================================== 1 failed, 15 warnings in 17.45s ===========================================`

**Comment by apsdehal** [comment]
Thanks for reporting this. Looking into it.

**Comment by skakar-git** [comment]
Thank you @apsdehal. A friend who is working independently on this but on GCP with linux has the same error. So it seems the issue is platform independent.

**Comment by apsdehal** [comment]
Open up a PR to fix. In general, the test is broken due to other reasons and shouldn't affect anything on user side.
