### ISSUE TITLE
How to collate bounding boxes of differenz sizes ?

### ISSUE THREAD

**Issue by pzdkn** [facebookresearch/mmf#878]
## ❓ Questions and Help
I am training VilBert on a custom dataset that uses F-RCNN features. I followed the guidelines to implement a custom dataset and use the FeatureDatabase to fetch the features.

However, since the number of bbox proposals vary, I have problems when the bboxes are collated to a SampleList.  What is the recommended way of collating a list of bboxes that vary in sizes? Should I just pad them? Could you give me a pointer to the place in the code that handles this?

Thanks!

**Comment by apsdehal** [comment]
Hi,
Yes, the expected way is to pad them. Checkout  BBoxProcessor at `https://github.com/facebookresearch/mmf/blob/master/mmf/datasets/processors/processors.py#L860` which automatically pads the bboxes upto a certain length. You can create a processor like that for your custom needs.
