### ISSUE TITLE
Only download test dataset with pretrained model

### ISSUE THREAD

**Issue by CCYChongyanChen** [facebookresearch/mmf#884]
## 🚀 Feature

When set to "test" mode, only download test dataset.

## Motivation
Currently, even set to the test mode, the train/val dataset are also downloaded.
For example, running"mmf_predict config=projects/vilbert/configs/vqa2/defaults.yaml \
    model=vilbert \
    dataset=vqa2 \
    run_type=test \
    checkpoint.resume_zoo=vilbert.pretrained.vqa2\
       training.num_workers=0", coco_train2017, trainval2014 are also downloaded. 
It would be burden to download so much dataset that is not used in testing....

Thanks!

**Comment by apsdehal** [comment]
Hi,
This is something that is actually dependent on how the dataset owner builds their zoo and not really in control of MMF. If the zoo files comes in as a single tar package then MMF can’t really split them beforehand anyways which is the case for VQA. Therefore, unfortunately, this is something we can’t fix as of now. We can look into splitting VQA files into multiple tar files into future but that is a separate issue and not related to MMF as a feature.

**Comment by CCYChongyanChen** [comment]
@apsdehal 
For vqa2, I believe the train_val and test dataset are separated as different tar package. But when running the model in the test mode with a pre-trained model, the code still download the train_val dataset.
