### ISSUE TITLE
Could you please provide source for making .npy annotation files?

### ISSUE THREAD

**Issue by ifmaq1** [facebookresearch/mmf#885]
I want to use 10k images from vqa2 dataset. I want to calculate grid features of them and train on movie_mcan model. For this, I want to make their annotations file. Can you provide the way through which you made i-e **imdb_val2014.npy** file?

**Comment by apsdehal** [comment]
Hi,
We don’t have exact source for that as it is very easy to create these annotation files from original json files. You can load the annotation file with `annotations = np.load("<file.npy>", allow_pickle=True)`. Now if you want to observe the samples; they start from index 1 (index 0 is metadata field which is not used anywhere as of now). 

if you want to create a subset from this of let’s say 1k images, you can do something like
```
import random

choices = [annotations[0]] + random.choices(annotations, k=1000)
np.save("my_annotations.npy", choices)`
```

let me know if something is not clear.

**Comment by ifmaq1** [comment]
@apsdehal yes it worked. Thank you for your response
