### ISSUE TITLE
How to visualize train.log file with tensorboard?

### ISSUE THREAD

**Issue by dinhanhx** [facebookresearch/mmf#890]
## ❓ Questions and Help

How can I use tensorboard to visualize `train.log` in `save` folder produced by this command `mmf_run config=projects/hateful_memes/configs/mmbt/defaults.yaml model=mmbt dataset=hateful_memes`?

**Comment by apsdehal** [comment]
Hi,
First you will need to enable tensorboard by `training.tensorboard=True`. This will enable tensorboard logging into `<save_dir>/logs` folder. Now, you can run tensorboard there with `tensorboard --port 5901 --logdir .`.

**Comment by dinhanhx** [comment]
> Hi,
> First you will need to enable tensorboard by `training.tensorboard=True`. This will enable tensorboard logging into `<save_dir>/logs` folder. Now, you can run tensorboard there with `tensorboard --port 5901 --logdir .`.

So this means if I forget to enable before training, I can't visualize with tensorboard?

**Comment by dinhanhx** [comment]
In my opinion, there should be a way to convert `train.log` file to something that Tensorboard can read.

**Comment by apsdehal** [comment]
For the moment, yeah it is not possible as the events for tensorboard are generate at runtime. You can indeed log them back in or use some other tool to plot the curves by reading train.log. Here is some sample code to read and write a file to plotly: https://gist.github.com/apsdehal/1d348bb5c1a179c430f9676d4c2972f0

**Comment by dinhanhx** [comment]
> For the moment, yeah it is not possible as the events for tensorboard are generate at runtime. You can indeed log them back in or use some other tool to plot the curves by reading train.log. Here is some sample code to read and write a file to plotly: https://gist.github.com/apsdehal/1d348bb5c1a179c430f9676d4c2972f0

Thank you, it's certainly useful, I will use it.

**Comment by apsdehal** [comment]
Closing this as resolved with the script provided.
