### ISSUE TITLE
Positional Embedding of M4C

### ISSUE THREAD

**Issue by HenryJunW** [facebookresearch/mmf#892]
## ❓ Questions and Help
Hello, I have a question about the positional embedding of M4C model. 

From my understanding of the code, we only have positional embedding for the input question and decoded words, right? For the visual object and OCR token embedding, we don't have the positional embedding. Is that because we already include the box position information for the object embedding and ocr embedding? 

Looking forward to your answer, thanks!

**Comment by ronghanghu** [comment]
> For the visual object and OCR token embedding, we don't have the positional embedding.

Yes, you are right! Unlike question words and decoded words, the bounding boxes and OCR tokens do not have a natural ordering, so we did not add a sequence index-based positional embedding to them. The positional information of visual objects and OCR tokens are contained in their bounding box embeddings.

**Comment by apsdehal** [comment]
Closing as resolved.
