### ISSUE TITLE
What's the roadmap of mmf?

### ISSUE THREAD

**Issue by butterluo** [facebookresearch/mmf#897]
## ❓ Questions and Help
What's the roadmap of mmf? When will it release the v1.0 and what features will be included in v1.0?

**Comment by apsdehal** [comment]
Hi,
Thanks for asking about the roadmap. We do have a roadmap which is not public. It focuses on usability aspects of MMF. We will likely release 1.0 once lightning and hydra integrations are done. We are also planning to support regular pip release to allow better use of mmf as library. Let me know if you any specific questions about MMF or any feature you would like to see and I would be happy to answer those.

**Comment by butterluo** [comment]
Thank you!  :)
