### ISSUE TITLE
Error during pip install from source on Colab

### ISSUE THREAD

**Issue by skakar-git** [facebookresearch/mmf#898]
Platform: Colab

`pip install --editable .` completes the task with two errors:

```
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
ERROR: pytorch-lightning 1.2.7 has requirement PyYAML!=5.4.*,>=5.1, but you'll have pyyaml 5.4.1 which is incompatible.
```
While the first error is always there, I am able to ignore it and proceed with unzipping the dataset as well as with `mmf_run`. So far ignoring this error has not caused a problem.

The second error is transient - often there, sometimes not. If it is there, then unzipping of the dataset with `mmf_convert_hm` fails with:

`pkg_resources.DistributionNotFound: The 'PyYAML!=5.4.*,>=5.1' distribution was not found and is required by pytorch-lightning`

I have spent lot of time trying to fix this but other than getting occasionally lucky with pip install when this error doesn't appear, I haven't had much success. Appreciate any help you can give.

**Update**
Adding PyYAML==5.3.1 to the requirements.txt seems to have fixed the problem.

**Comment by apsdehal** [comment]
Hi,
Yes, on colab you need to upgrade the pyyaml to a latest version. Feel free to close the issue if you feel it is resolved.
