### ISSUE TITLE
Mmf_hm_example notebook runtime error - mat dim mismatch 

### ISSUE THREAD

**Issue by zli12** [facebookresearch/mmf#899]
## ❓ Questions and Help
Hi we’re running the example notebook (https://colab.research.google.com/github/facebookresearch/mmf/blob/notebooks/notebooks/mmf_hm_example.ipynb) but hit runtime error below when running the ’ Train your model’ part. I wonder if this this notebook is out of date or there something wrong with the it?

RuntimeError Traceback (most recent call last)
in ()
7 “training.num_workers=0”
8 ]
----> 9 run(opts=opts)

14 frames
/usr/local/lib/python3.7/dist-packages/mmf_cli/run.py in run(opts, predict)
131 else:
132 config.device_id = 0
→ 133 main(configuration, predict=predict)
134
135

/usr/local/lib/python3.7/dist-packages/mmf_cli/run.py in main(configuration, init_distributed, predict)
54 trainer.inference()
55 else:
—> 56 trainer.train()
57
58

/usr/local/lib/python3.7/dist-packages/mmf/trainers/mmf_trainer.py in train(self)
139
140 self.on_train_start()
→ 141 self.training_loop()
142 self.on_train_end()
143

/usr/local/lib/python3.7/dist-packages/mmf/trainers/core/training_loop.py in training_loop(self)
31 logger.info(“Starting training…”)
32 self.model.train()
—> 33 self.run_training_epoch()
34 self.after_training_loop()
35

/usr/local/lib/python3.7/dist-packages/mmf/trainers/core/training_loop.py in run_training_epoch(self)
89 self.profile(“Batch load time”)
90
—> 91 report = self.run_training_batch(batch, num_batches_for_this_update)
92 report = report.detach()
93

/usr/local/lib/python3.7/dist-packages/mmf/trainers/core/training_loop.py in run_training_batch(self, batch, loss_divisor)
163
164 def run_training_batch(self, batch: Dict[str, Tensor], loss_divisor: int) → None:
→ 165 report = self._forward(batch)
166 # Since losses are batch averaged in MMF, this makes sure the
167 # scaling is right.

/usr/local/lib/python3.7/dist-packages/mmf/trainers/core/training_loop.py in _forward(self, batch)
180
181 with torch.cuda.amp.autocast(enabled=self.training_config.fp16):
→ 182 model_output = self.model(prepared_batch)
183 report = Report(prepared_batch, model_output)
184

/usr/local/lib/python3.7/dist-packages/mmf/models/base_model.py in call(self, sample_list, *args, **kwargs)
234 sample_list = to_device(sample_list, get_current_device())
235
→ 236 model_output = super().call(sample_list, *args, **kwargs)
237
238 # Don’t do anything fancy to output if it is pretrained

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
887 result = self._slow_forward(*input, **kwargs)
888 else:
→ 889 result = self.forward(*input, **kwargs)
890 for hook in itertools.chain(
891 _global_forward_hooks.values(),

in forward(self, sample_list)
88 image = sample_list[“image”]
89
—> 90 text_features = self.relu(self.language_module(text))
91 image_features = self.relu(self.vision_module(image))
92

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
887 result = self._slow_forward(*input, **kwargs)
888 else:
→ 889 result = self.forward(*input, **kwargs)
890 for hook in itertools.chain(
891 _global_forward_hooks.values(),

/usr/local/lib/python3.7/dist-packages/mmf/modules/embeddings.py in forward(self, x)
213
214 def forward(self, x):
→ 215 return self.layers(x)
216
217

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
887 result = self._slow_forward(*input, **kwargs)
888 else:
→ 889 result = self.forward(*input, **kwargs)
890 for hook in itertools.chain(
891 _global_forward_hooks.values(),

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py in forward(self, input)
92
93 def forward(self, input: Tensor) → Tensor:
—> 94 return F.linear(input, self.weight, self.bias)
95
96 def extra_repr(self) → str:

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py in linear(input, weight, bias)
1751 if has_torch_function_variadic(input, weight):
1752 return handle_torch_function(linear, (input, weight), input, weight, bias=bias)
→ 1753 return torch._C._nn.linear(input, weight, bias)
1754
1755

RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by apsdehal** [comment]
Hi,
We fixed the colab notebook. Please reload the notebook and it should run well now. Let us know in a new issue if any new issues persist.
