### ISSUE TITLE
CLEVR pretrained

### ISSUE THREAD

**Issue by violetteshev** [facebookresearch/mmf#911]
Hi,

Thanks for this amazing library. Is there any model pretrained on CLEVR available? The docs mentioned cnn_lstm trained on clevr, but I couldn't find it in the model zoo.

**Comment by ytsheng** [comment]
Hi @violetteshev,

It does not look like we have the cnn_lstm pretrained checkpoint available anymore. My teammate @apsdehal was the last one that integrated the cnn_lstm, perhaps he can share more pointers.

The clevr dataset can be downloaded here: https://dl.fbaipublicfiles.com/clevr/CLEVR_v1.0.zip

This PR should hopefully be helpful: https://github.com/facebookresearch/mmf/pull/103

**Comment by violetteshev** [comment]
Ok, thank you.
