### ISSUE TITLE
Valueerror when finetuning ViLBERT CC on Hateful Memes dataset and with BCE loss

### ISSUE THREAD

**Issue by skakar-git** [facebookresearch/mmf#915]
Platform: Colab

Finetuning VilBERT CC on Hateful Memes dataset and with binary cross entropy loss raises following error:

```
File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 2755, in binary_cross_entropy
    "Please ensure they have the same size.".format(target.size(), input.size())
ValueError: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 2])) is deprecated. Please ensure they have the same size.
```
I think I understand what the error means but don't know how to fix it. Is BCE Loss the wrong loss to use for this purpose?

**Comment by ytsheng** [comment]
Hi @skakar-git, thanks for using mmf,

Do you mind sharing your command line so that I can try to repo on my end? Thank you!

**Comment by skakar-git** [comment]
Thank you - it is vanilla command line:

```
!mmf_run config=projects/hateful_memes/configs/vilbert/from_cc.yaml  \
model=vilbert \
dataset=hateful_memes \
run_type=train_val \
```

In addition, in defaults.yaml:

```
model_config:
  vilbert:
    training_head_type: classification
    num_labels: 2
    losses:
    - bce
  ```

**Comment by apsdehal** [comment]
bce can't be used directly as it expects targets with N X C format. Either do that with targets or use cross_entropy which is what is default in MMF.
