### ISSUE TITLE
GAN style training

### ISSUE THREAD

**Issue by shubhamagarwal92** [facebookresearch/mmf#92]
## ❓ Questions and Help

How easy is it to code a GAN style model for image generation using Pythia? Do you have any pointers/docs as to how I can configure the trainer? In future do you plan to fully implement a structure similar to Allennlp where by we just need to create a dataset reader and config file for our use case?

**Comment by zhiqwang** [comment]
Or combine the structure of [`fairseq`](https://github.com/pytorch/fairseq) ?
