### ISSUE TITLE
KRISP resource requirement

### ISSUE THREAD

**Issue by ifmaq1** [facebookresearch/mmf#977]
## ❓ Questions and Help
Hi, 
**1-)**Recently the **Krisp** model has been added for **OKVQA** to MMF. Can you please let me know how much resources does it need including the dataset, external knowledge and model? **In terms of RAM and hardisk.** 

**2-)**Also, when I am running command 

 **mmf_run config=code/mmf_fork_pr/mmf/projects/krisp/configs/krisp/okvqa/train_val.yaml run_type=train_val dataset=okvqa model=krisp**
 
 **it says** 
 _FileNotFoundError: [Errno 2] No such file or directory: '/**home/mmf-krisp/code/mmf_fork_pr/mmf/projects/krisp/configs/krisp/okvqa/train_val.yaml'_**
 
clearly there has been no such path made till now.

and when I change the path to 

**mmf_run config=projects/krisp/configs/krisp/okvqa/train_val.yaml run_type=train_val dataset=okvqa model=krisp**

it displays

**[ Checksum not provided, skipping for features.tar.gz]**
[ Downloading: https://dl.fbaipublicfiles.com/mmf/data/datasets/okvqa/defaults/features/features_fc6.tar.gz to /home/.cache/torch/mmf/data/datasets/okvqa/defaults/features/features.tar.gz ]

**Comment by ytsheng** [comment]
Hi @ifmaq1, thanks for using mmf,

1. I will defer to @apsdehal as he has more experience on it.
2. No checksum is fine, the download will still happen. The path: `projects/krisp/configs/krisp/okvqa/train_val.yaml` should be the right path to use for this, I do not think we have ever used the prefix: `code/mmf_fork_pr`

**Comment by apsdehal** [comment]
@KMarino Can you answer 1) in this?

**Comment by KMarino** [comment]
For disk space, the main constraint is the features file which is about 300Gb if I’m remembering correctly. Everything else is pretty negligible. For RAM, I do not recall off the top of my head, but I don’t remember it having a huge overhead compared to normal mmf models. Let me know if you have RAM issues though

**Comment by ifmaq1** [comment]
Thank you for your responses. @KMarino can you please tell me how many **gpus** you used and how long the **training** took.

**Comment by KMarino** [comment]
On a four gpu machine, I think it was around 12-24 hours. May depend a lot on your CPU performance though

**Comment by ifmaq1** [comment]
@KMarino thanks for providing information
