### ISSUE TITLE
zsh: command not found: mmf_run

### ISSUE THREAD

**Issue by nan1104** [facebookresearch/mmf#985]
## 🐛 Bug
I have finished installation and passing pytest. 
But when I want to test the following comand
mmf_run config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=train_val
i meet ”zsh: command not found: mmf_run“
## Command
mmf_run config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=train_val

**Comment by ytsheng** [comment]
Hi,  @nan1104, thanks for using mmf,

Could you check to see if you are under a conda environment? Also, it would be useful to share the directory structure you have and which directory you are in?

Thanks

**Comment by nan1104** [comment]
Thanks. I find that this is no longer a problem. It may have been my conda environment problem before.

**Comment by fengmingfeng** [comment]
I also occured this problem? I think you should add the mmf to environment variable?
for example:
import os
os.environ['PYTHONPATH'] += ":/content/mmf/"
then we will solve this problem.
