### ISSUE TITLE
Unexpected Performance of KRISP

### ISSUE THREAD

**Issue by Fen9** [facebookresearch/mmf#988]
## ❓ Questions and Help
Dear authors,

Thank you for sharing the code and I really enjoy it. I try to run the KRISP code following all the provided instructions but I found the performance does not match the number that is claimed in the paper. The accuracy that I got is around 31.73% and it seems like it is the performance of the KRISP without the MMBERT pre-trained.

Would you like to share how to incorporate the MMBERT pre-trained into the entire model? I really appreciate your help.

**Comment by KMarino** [comment]
Do you mean the result with VQA pretraining? Yeah, for that number you have to train on VQA first, that config file is here: https://github.com/facebookresearch/mmf/blob/master/projects/krisp/configs/krisp/vqa2/krisp_pretrain.yaml

**Comment by KMarino** [comment]
Also, make sure you actually run your final model through evaluation and run the result file through a VQA eval. Because if batching, the eval at the end of training is not necessarily the correct number because it cuts off the end of the eval set.

**Comment by Fen9** [comment]
Thank you for reply, and yes, I am referring to the pre-trained of the MMBERT on VQA2.0. If I am understanding it correctly, I first need to use the config you mentioned to train the MMBERT. Then after this training is completed, I use the config that is provided in the README?

**Comment by KMarino** [comment]
Right

**Comment by Fen9** [comment]
Thank you very much. I appreciate it. I will come back and close the issue once I got the claimed numbers.

**Comment by Fen9** [comment]
BTW, does the pre-training of MMBERT use the knowledge graph?

**Comment by Fen9** [comment]
Dear authors,

I tried to run the pre-training for the krisp using "mmf_run config=mmf/projects/krisp/configs/krisp/vqa2/krisp_pretrain.yaml dataset=vqa2 model=krisp" but I got stuck at "Loading Model". Do you happen to have any evidence?

Thanks

**Comment by Fen9** [comment]
Just confirm, the command the run the pre-training is "mmf_run config=mmf/projects/krisp/configs/krisp/vqa2/krisp_pretrain.yaml dataset=vqa2 model=krisp"?. It will be stuck at "Loading Model" for half-hour and output the following error:


Do you happen to have any pieces of evidence on it? Thanks.

**Comment by KMarino** [comment]
Apologies if I'm late on answering you, I'm actually defending my thesis this week.

Yes, so first thing if you aren't doing this already is to run with a batch size of one on CPU only and put a breakpoint right before the error and try to investigate it. 

I'm not totally sure why you're getting that particular error either; maybe that field should be called "question_id" rather than "id" but I did run this without errors before, so not sure why it's bugging out here. 

Multi-processing does sometimes make the errors unhelpful or non-sensical, so I would run it the way I said above and that should hopefully make it more clear.

**Comment by apsdehal** [comment]
Generally, this can happen due to a lot of reasons related to memory. I would suggest running on single GPU by doing `export CUDA_VISIBLE_DEVICES=0` before running the job and adding `training.num_workers=0` at the end of the command to debug the error.

**Comment by Fen9** [comment]
Thank you for the quick reply.

After applying @apsdehal's suggestion, a new problem pops up. It seems like it is from the KRISP graph reasoning module.

Traceback (most recent call last):
  File "/home/ubuntu/krisp/venv/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/ubuntu/krisp/mmf/mmf_cli/run.py", line 133, in run
    main(configuration, predict=predict)
  File "/home/ubuntu/krisp/mmf/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/home/ubuntu/krisp/mmf/mmf/trainers/mmf_trainer.py", line 142, in train
    self.training_loop()
  File "/home/ubuntu/krisp/mmf/mmf/trainers/core/training_loop.py", line 33, in training_loop
    self.run_training_epoch()
  File "/home/ubuntu/krisp/mmf/mmf/trainers/core/training_loop.py", line 91, in run_training_epoch
    report = self.run_training_batch(batch, num_batches_for_this_update)
  File "/home/ubuntu/krisp/mmf/mmf/trainers/core/training_loop.py", line 166, in run_training_batch
    report = self._forward(batch)
  File "/home/ubuntu/krisp/mmf/mmf/trainers/core/training_loop.py", line 178, in _forward
    model_output = self.model(prepared_batch)
  File "/home/ubuntu/krisp/mmf/mmf/models/base_model.py", line 273, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "/home/ubuntu/krisp/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/krisp/mmf/mmf/models/krisp.py", line 183, in forward
    graph_output = self.graph_module(sample_list)
  File "/home/ubuntu/krisp/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/krisp/mmf/projects/krisp/graphnetwork_module.py", line 956, in forward
    qids = sample_list["id"]
KeyError: 'id'

Thanks

**Comment by Fen9** [comment]
@apsdehal , I've tried your suggestion. However, the same bug appears.

**Comment by KMarino** [comment]
Can you provide more debug information? Did you set a pdb set_trace and look at the contents of that dictionary like I suggested above?

**Comment by Fen9** [comment]
I change line 956 "id" to "question_id". It works. But it needs to be trained for 500h. Is it correct? One more question, could you upload the trained parameters for the full model. Thanks.

**Comment by KMarino** [comment]
I think that's because the evaluation interval is set too frequently. Try training.evaluation_interval=88000. That should end up at a reasonable training time

**Comment by ChanningPing** [comment]
I'm also running the visual_bert with VQA 2.0 pretraining, and the ETA is very long. Will the checkpoint of the pretrained visual_bert with VQA-2.0 be released?

**Comment by KMarino** [comment]
Try the evaluation_interval trick from above

I am working on releasing checkpoints, I just have quite a lot on my plate this week

**Comment by Fen9** [comment]
Thanks @KMarino. The training time is now down to 90h. Looking forward to the checkpoints from you.

**Comment by KMarino** [comment]
Will do my best to get those out as soon as I can.

Maybe @apsdehal has more suggestions about reducing your training time. Mine was FAR lower that that. Make sure you are using all your CPU compute. Also, hopefully you removed training.num_workers=0.

**Comment by KMarino** [comment]
Also, the estimated time sometimes is wrong for the first few iterations, so it might actually be something more reasonable

**Comment by Fen9** [comment]
@KMarino Thanks for the reply. May I ask what command did you call to pre-train? I tried to specify the value of training.num_workers to a larger number, but it didn't work. It is still very slow.

**Comment by Fen9** [comment]
@KMarino, thank you for your replys. I've gone through the training and got the number that is closed to the reported number in the paper. I am closing this issue.
