### ISSUE TITLE
Use MMBT model for feature extraction

### ISSUE THREAD

**Issue by ilmissigno** [facebookresearch/mmf#992]
## ❓ Questions and Help
Hi everyone, first of all I congratulate the team for the realization of this fantastic framework. I am using MMBT for my master's thesis regarding Previously Fact-Checking Detection. I would like to know if it is possible to use MMBT to perform Feature Extraction of multimodal features. If so, how can I do it? Thanks a lot to everyone!

**Comment by apsdehal** [comment]
Just in case for future readers, `fused_feature_only` flag in MMBT config can be set to `True` to extract out features only from MMBT. https://github.com/facebookresearch/mmf/blob/master/mmf/models/mmbt.py#L583
