### ISSUE TITLE
Technical queries - M4C model and datasets

### ISSUE THREAD

**Issue by Mano2610** [facebookresearch/mmf#997]
@Mano2610 You might want to try out the ST-VQA dataset (https://rrc.cvc.uab.es/?ch=11&com=downloads). It can also be downloaded automatically in MMF.

_Originally posted by @ronghanghu in https://github.com/facebookresearch/mmf/issues/810#issuecomment-868855210_

@ronghanghu - Can you please confirm the code below to run the STVQA dataset in mmf,

mmf_run config=projects/m4c/configs/textvqa/defaults.yaml
datasets=stvqa
model=m4c
run_type=train

Do I need to change the config as well as below,

mmf_run config=projects/m4c/configs/stvqa/defaults.yaml

**Comment by ronghanghu** [comment]
@Mano2610 yes, the config should also be changed to `projects/m4c/configs/stvqa/defaults.yaml` to train M4C on the ST-VQA dataset

**Comment by apsdehal** [comment]
Closing as resolved. Please open up a new issue for further inquiries.
